<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class AssoRaceTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('asso_race')->delete();
        
        \DB::table('asso_race')->insert(array (
            0 => 
            array (
                'id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 4,
                'race_mere_id' => 5,
                'race_produit_id' => 5,
                'taille_conditions' => 0,
                'automatique' => 1,
                'commentaire' => 'Welsh toutes sections',
                'approbation' => 0,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => 100.0,
            ),
            1 => 
            array (
                'id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 5,
                'race_mere_id' => 4,
                'race_produit_id' => 5,
                'taille_conditions' => 0,
                'automatique' => 1,
                'commentaire' => 'Welsh toutes sections',
                'approbation' => 0,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => 100.0,
            ),
            2 => 
            array (
                'id' => 3,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 4,
                'race_mere_id' => 6,
                'race_produit_id' => 6,
                'taille_conditions' => 0,
                'automatique' => 1,
                'commentaire' => 'Welsh toutes sections',
                'approbation' => 0,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => 100.0,
            ),
            3 => 
            array (
                'id' => 4,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 4,
                'race_mere_id' => 7,
                'race_produit_id' => 6,
                'taille_conditions' => 0,
                'automatique' => 1,
                'commentaire' => 'Welsh toutes sections',
                'approbation' => 0,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => 100.0,
            ),
            4 => 
            array (
                'id' => 5,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 6,
                'race_mere_id' => 4,
                'race_produit_id' => 6,
                'taille_conditions' => 0,
                'automatique' => 1,
                'commentaire' => 'Welsh toutes sections',
                'approbation' => 0,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => 100.0,
            ),
            5 => 
            array (
                'id' => 6,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 7,
                'race_mere_id' => 4,
                'race_produit_id' => 6,
                'taille_conditions' => 0,
                'automatique' => 1,
                'commentaire' => 'Welsh toutes sections',
                'approbation' => 0,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => 100.0,
            ),
            6 => 
            array (
                'id' => 7,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 5,
                'race_mere_id' => 6,
                'race_produit_id' => 6,
                'taille_conditions' => 0,
                'automatique' => 1,
                'commentaire' => 'Welsh toutes sections',
                'approbation' => 0,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => 100.0,
            ),
            7 => 
            array (
                'id' => 8,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 6,
                'race_mere_id' => 5,
                'race_produit_id' => 6,
                'taille_conditions' => 0,
                'automatique' => 1,
                'commentaire' => 'Welsh toutes sections',
                'approbation' => 0,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => 100.0,
            ),
            8 => 
            array (
                'id' => 9,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 5,
                'race_mere_id' => 7,
                'race_produit_id' => 6,
                'taille_conditions' => 1,
                'automatique' => 1,
                'commentaire' => 'Welsh toutes sections',
                'approbation' => 0,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => 100.0,
            ),
            9 => 
            array (
                'id' => 10,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 7,
                'race_mere_id' => 5,
                'race_produit_id' => 6,
                'taille_conditions' => 1,
                'automatique' => 1,
                'commentaire' => 'Welsh toutes sections',
                'approbation' => 0,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => 100.0,
            ),
            10 => 
            array (
                'id' => 11,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 5,
                'race_mere_id' => 7,
                'race_produit_id' => 7,
                'taille_conditions' => 1,
                'automatique' => 1,
                'commentaire' => 'Welsh toutes sections',
                'approbation' => 0,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => 100.0,
            ),
            11 => 
            array (
                'id' => 12,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 7,
                'race_mere_id' => 5,
                'race_produit_id' => 7,
                'taille_conditions' => 1,
                'automatique' => 1,
                'commentaire' => 'Welsh toutes sections',
                'approbation' => 0,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => 100.0,
            ),
            12 => 
            array (
                'id' => 13,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 8,
                'race_mere_id' => NULL,
                'race_produit_id' => 9,
                'taille_conditions' => 0,
                'automatique' => 0,
                'commentaire' => 'DSA 50% min',
                'approbation' => 0,
                'pourCentArabe' => 50.0,
                'pourCentWelsh' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => NULL,
                'race_mere_id' => 8,
                'race_produit_id' => 9,
                'taille_conditions' => 0,
                'automatique' => 0,
                'commentaire' => 'DSA 50% min',
                'approbation' => 0,
                'pourCentArabe' => 50.0,
                'pourCentWelsh' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 8,
                'race_mere_id' => 4,
                'race_produit_id' => 11,
                'taille_conditions' => 0,
                'automatique' => 0,
                'commentaire' => 'FS',
                'approbation' => 1,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 8,
                'race_mere_id' => 5,
                'race_produit_id' => 11,
                'taille_conditions' => 0,
                'automatique' => 0,
                'commentaire' => 'FS',
                'approbation' => 1,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 8,
                'race_mere_id' => 6,
                'race_produit_id' => 11,
                'taille_conditions' => 0,
                'automatique' => 0,
                'commentaire' => 'FS',
                'approbation' => 1,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 8,
                'race_mere_id' => 7,
                'race_produit_id' => 11,
                'taille_conditions' => 0,
                'automatique' => 0,
                'commentaire' => 'FS',
                'approbation' => 1,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 4,
                'race_mere_id' => NULL,
                'race_produit_id' => 10,
                'taille_conditions' => 0,
                'automatique' => 0,
                'commentaire' => 'WPB',
                'approbation' => 0,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => 12.5,
            ),
            19 => 
            array (
                'id' => 20,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => NULL,
                'race_mere_id' => 4,
                'race_produit_id' => 10,
                'taille_conditions' => 0,
                'automatique' => 0,
                'commentaire' => 'WPB',
                'approbation' => 0,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => 12.5,
            ),
            20 => 
            array (
                'id' => 21,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 5,
                'race_mere_id' => NULL,
                'race_produit_id' => 10,
                'taille_conditions' => 0,
                'automatique' => 0,
                'commentaire' => 'WPB',
                'approbation' => 0,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => 12.5,
            ),
            21 => 
            array (
                'id' => 22,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => NULL,
                'race_mere_id' => 5,
                'race_produit_id' => 10,
                'taille_conditions' => 0,
                'automatique' => 0,
                'commentaire' => 'WPB',
                'approbation' => 0,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => 12.5,
            ),
            22 => 
            array (
                'id' => 23,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 6,
                'race_mere_id' => NULL,
                'race_produit_id' => 10,
                'taille_conditions' => 0,
                'automatique' => 0,
                'commentaire' => 'WPB',
                'approbation' => 0,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => 12.5,
            ),
            23 => 
            array (
                'id' => 24,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => NULL,
                'race_mere_id' => 6,
                'race_produit_id' => 10,
                'taille_conditions' => 0,
                'automatique' => 0,
                'commentaire' => 'WPB',
                'approbation' => 0,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => 12.5,
            ),
            24 => 
            array (
                'id' => 25,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 7,
                'race_mere_id' => NULL,
                'race_produit_id' => 10,
                'taille_conditions' => 0,
                'automatique' => 0,
                'commentaire' => 'WPB',
                'approbation' => 0,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => 12.5,
            ),
            25 => 
            array (
                'id' => 26,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => NULL,
                'race_mere_id' => 7,
                'race_produit_id' => 10,
                'taille_conditions' => 0,
                'automatique' => 0,
                'commentaire' => 'WPB',
                'approbation' => 0,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => 12.5,
            ),
            26 => 
            array (
                'id' => 27,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 8,
                'race_mere_id' => 10,
                'race_produit_id' => 11,
                'taille_conditions' => 1,
                'automatique' => 0,
                'commentaire' => 'FS',
                'approbation' => 1,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => NULL,
            ),
            27 => 
            array (
                'id' => 28,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 11,
                'race_mere_id' => 4,
                'race_produit_id' => 11,
                'taille_conditions' => 0,
                'automatique' => 0,
                'commentaire' => 'FS',
                'approbation' => 1,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => NULL,
            ),
            28 => 
            array (
                'id' => 29,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 11,
                'race_mere_id' => 5,
                'race_produit_id' => 11,
                'taille_conditions' => 0,
                'automatique' => 0,
                'commentaire' => 'FS',
                'approbation' => 1,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => NULL,
            ),
            29 => 
            array (
                'id' => 30,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 11,
                'race_mere_id' => 6,
                'race_produit_id' => 11,
                'taille_conditions' => 0,
                'automatique' => 0,
                'commentaire' => 'FS',
                'approbation' => 1,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => NULL,
            ),
            30 => 
            array (
                'id' => 31,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 11,
                'race_mere_id' => 7,
                'race_produit_id' => 11,
                'taille_conditions' => 0,
                'automatique' => 0,
                'commentaire' => 'FS',
                'approbation' => 1,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => NULL,
            ),
            31 => 
            array (
                'id' => 32,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 5,
                'race_mere_id' => 11,
                'race_produit_id' => 11,
                'taille_conditions' => 0,
                'automatique' => 0,
                'commentaire' => 'FS',
                'approbation' => 1,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => NULL,
            ),
            32 => 
            array (
                'id' => 33,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 4,
                'race_mere_id' => 11,
                'race_produit_id' => 11,
                'taille_conditions' => 0,
                'automatique' => 0,
                'commentaire' => 'FS',
                'approbation' => 1,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => NULL,
            ),
            33 => 
            array (
                'id' => 34,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 6,
                'race_mere_id' => 11,
                'race_produit_id' => 11,
                'taille_conditions' => 0,
                'automatique' => 0,
                'commentaire' => 'FS',
                'approbation' => 1,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => NULL,
            ),
            34 => 
            array (
                'id' => 35,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 7,
                'race_mere_id' => 11,
                'race_produit_id' => 11,
                'taille_conditions' => 0,
                'automatique' => 0,
                'commentaire' => 'FS',
                'approbation' => 1,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => NULL,
            ),
            35 => 
            array (
                'id' => 37,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 8,
                'race_mere_id' => 11,
                'race_produit_id' => 11,
                'taille_conditions' => 0,
                'automatique' => 0,
                'commentaire' => 'FS',
                'approbation' => 1,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => NULL,
            ),
            36 => 
            array (
                'id' => 38,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 3,
                'race_mere_id' => NULL,
                'race_produit_id' => 3,
                'taille_conditions' => 1,
                'automatique' => 0,
                'commentaire' => 'miniature',
                'approbation' => 0,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => NULL,
            ),
            37 => 
            array (
                'id' => 39,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => NULL,
                'race_mere_id' => 3,
                'race_produit_id' => 3,
                'taille_conditions' => 1,
                'automatique' => 0,
                'commentaire' => 'miniature',
                'approbation' => 0,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => NULL,
            ),
            38 => 
            array (
                'id' => 40,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 8,
                'race_mere_id' => 9,
                'race_produit_id' => 9,
                'taille_conditions' => 0,
                'automatique' => 0,
                'commentaire' => 'DSA > 50%',
                'approbation' => 0,
                'pourCentArabe' => 50.0,
                'pourCentWelsh' => NULL,
            ),
            39 => 
            array (
                'id' => 41,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 9,
                'race_mere_id' => 8,
                'race_produit_id' => 9,
                'taille_conditions' => 0,
                'automatique' => 0,
                'commentaire' => 'DSA > 50%',
                'approbation' => 0,
                'pourCentArabe' => 50.0,
                'pourCentWelsh' => NULL,
            ),
            40 => 
            array (
                'id' => 42,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 10,
                'race_mere_id' => 4,
                'race_produit_id' => 10,
                'taille_conditions' => 0,
                'automatique' => 0,
                'commentaire' => 'WPB',
                'approbation' => 0,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => 12.5,
            ),
            41 => 
            array (
                'id' => 43,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 10,
                'race_mere_id' => 5,
                'race_produit_id' => 10,
                'taille_conditions' => 0,
                'automatique' => 0,
                'commentaire' => 'WPB',
                'approbation' => 0,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => 12.5,
            ),
            42 => 
            array (
                'id' => 44,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 10,
                'race_mere_id' => 6,
                'race_produit_id' => 10,
                'taille_conditions' => 0,
                'automatique' => 0,
                'commentaire' => 'WPB',
                'approbation' => 0,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => 12.5,
            ),
            43 => 
            array (
                'id' => 45,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 10,
                'race_mere_id' => 7,
                'race_produit_id' => 10,
                'taille_conditions' => 0,
                'automatique' => 0,
                'commentaire' => 'WPB',
                'approbation' => 0,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => 12.5,
            ),
            44 => 
            array (
                'id' => 46,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 4,
                'race_mere_id' => 10,
                'race_produit_id' => 10,
                'taille_conditions' => 0,
                'automatique' => 0,
                'commentaire' => 'WPB',
                'approbation' => 0,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => 12.5,
            ),
            45 => 
            array (
                'id' => 47,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 5,
                'race_mere_id' => 10,
                'race_produit_id' => 10,
                'taille_conditions' => 0,
                'automatique' => 0,
                'commentaire' => 'WPB',
                'approbation' => 0,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => 12.5,
            ),
            46 => 
            array (
                'id' => 48,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 6,
                'race_mere_id' => 10,
                'race_produit_id' => 10,
                'taille_conditions' => 0,
                'automatique' => 0,
                'commentaire' => 'WPB',
                'approbation' => 0,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => 12.5,
            ),
            47 => 
            array (
                'id' => 49,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 7,
                'race_mere_id' => 10,
                'race_produit_id' => 10,
                'taille_conditions' => 0,
                'automatique' => 0,
                'commentaire' => 'WPB',
                'approbation' => 0,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => 12.5,
            ),
            48 => 
            array (
                'id' => 50,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 7,
                'race_mere_id' => 6,
                'race_produit_id' => 7,
                'taille_conditions' => 1,
                'automatique' => 1,
                'commentaire' => 'Welsh toutes sections',
                'approbation' => 0,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => 100.0,
            ),
            49 => 
            array (
                'id' => 51,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 6,
                'race_mere_id' => 7,
                'race_produit_id' => 7,
                'taille_conditions' => 1,
                'automatique' => 1,
                'commentaire' => 'Welsh toutes sections',
                'approbation' => 0,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => 100.0,
            ),
            50 => 
            array (
                'id' => 52,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 7,
                'race_mere_id' => 6,
                'race_produit_id' => 6,
                'taille_conditions' => 1,
                'automatique' => 1,
                'commentaire' => 'Welsh toutes sections',
                'approbation' => 0,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => 100.0,
            ),
            51 => 
            array (
                'id' => 53,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 6,
                'race_mere_id' => 7,
                'race_produit_id' => 6,
                'taille_conditions' => 1,
                'automatique' => 1,
                'commentaire' => 'Welsh toutes sections',
                'approbation' => 0,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => 100.0,
            ),
            52 => 
            array (
                'id' => 55,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 11,
                'race_mere_id' => 8,
                'race_produit_id' => 11,
                'taille_conditions' => 1,
                'automatique' => 0,
                'commentaire' => 'FS',
                'approbation' => 1,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => NULL,
            ),
            53 => 
            array (
                'id' => 56,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 11,
                'race_mere_id' => 10,
                'race_produit_id' => 11,
                'taille_conditions' => 1,
                'automatique' => 0,
                'commentaire' => 'FS',
                'approbation' => 1,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => NULL,
            ),
            54 => 
            array (
                'id' => 58,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 10,
                'race_mere_id' => 11,
                'race_produit_id' => 11,
                'taille_conditions' => 0,
                'automatique' => 0,
                'commentaire' => 'FS',
                'approbation' => 1,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => NULL,
            ),
            55 => 
            array (
                'id' => 72,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 4,
                'race_mere_id' => 10,
                'race_produit_id' => 11,
                'taille_conditions' => 1,
                'automatique' => 0,
                'commentaire' => 'FS',
                'approbation' => 1,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => NULL,
            ),
            56 => 
            array (
                'id' => 73,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 5,
                'race_mere_id' => 10,
                'race_produit_id' => 11,
                'taille_conditions' => 1,
                'automatique' => 0,
                'commentaire' => 'FS',
                'approbation' => 1,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => NULL,
            ),
            57 => 
            array (
                'id' => 74,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 6,
                'race_mere_id' => 10,
                'race_produit_id' => 11,
                'taille_conditions' => 1,
                'automatique' => 0,
                'commentaire' => 'FS',
                'approbation' => 1,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => NULL,
            ),
            58 => 
            array (
                'id' => 75,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 7,
                'race_mere_id' => 10,
                'race_produit_id' => 11,
                'taille_conditions' => 1,
                'automatique' => 0,
                'commentaire' => 'FS',
                'approbation' => 1,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => NULL,
            ),
            59 => 
            array (
                'id' => 76,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 4,
                'race_mere_id' => 8,
                'race_produit_id' => 11,
                'taille_conditions' => 1,
                'automatique' => 0,
                'commentaire' => 'FS',
                'approbation' => 1,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => NULL,
            ),
            60 => 
            array (
                'id' => 77,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 5,
                'race_mere_id' => 8,
                'race_produit_id' => 11,
                'taille_conditions' => 1,
                'automatique' => 0,
                'commentaire' => 'FS',
                'approbation' => 1,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => NULL,
            ),
            61 => 
            array (
                'id' => 78,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 6,
                'race_mere_id' => 8,
                'race_produit_id' => 11,
                'taille_conditions' => 1,
                'automatique' => 0,
                'commentaire' => 'FS',
                'approbation' => 1,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => NULL,
            ),
            62 => 
            array (
                'id' => 79,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 7,
                'race_mere_id' => 8,
                'race_produit_id' => 11,
                'taille_conditions' => 1,
                'automatique' => 0,
                'commentaire' => 'FS',
                'approbation' => 1,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => NULL,
            ),
            63 => 
            array (
                'id' => 81,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => NULL,
                'race_mere_id' => NULL,
                'race_produit_id' => 10,
                'taille_conditions' => 0,
                'automatique' => 0,
                'commentaire' => 'WPB',
                'approbation' => 0,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => 12.5,
            ),
            64 => 
            array (
                'id' => 82,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => NULL,
                'race_mere_id' => NULL,
                'race_produit_id' => 9,
                'taille_conditions' => 0,
                'automatique' => 0,
                'commentaire' => 'DSA',
                'approbation' => 0,
                'pourCentArabe' => 50.0,
                'pourCentWelsh' => NULL,
            ),
            65 => 
            array (
                'id' => 83,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => NULL,
                'race_mere_id' => NULL,
                'race_produit_id' => 3,
                'taille_conditions' => 1,
                'automatique' => 0,
                'commentaire' => 'miniarure',
                'approbation' => 0,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => NULL,
            ),
            66 => 
            array (
                'id' => 84,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 12,
                'race_mere_id' => 11,
                'race_produit_id' => 11,
                'taille_conditions' => 0,
                'automatique' => 0,
                'commentaire' => 'FS',
                'approbation' => 1,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => NULL,
            ),
            67 => 
            array (
                'id' => 85,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 11,
                'race_mere_id' => 12,
                'race_produit_id' => 11,
                'taille_conditions' => 0,
                'automatique' => 0,
                'commentaire' => 'FS',
                'approbation' => 1,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => NULL,
            ),
            68 => 
            array (
                'id' => 86,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 12,
                'race_mere_id' => 8,
                'race_produit_id' => 11,
                'taille_conditions' => 0,
                'automatique' => 0,
                'commentaire' => 'FS',
                'approbation' => 1,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => NULL,
            ),
            69 => 
            array (
                'id' => 87,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 8,
                'race_mere_id' => 12,
                'race_produit_id' => 11,
                'taille_conditions' => 0,
                'automatique' => 0,
                'commentaire' => 'FS',
                'approbation' => 1,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => NULL,
            ),
            70 => 
            array (
                'id' => 88,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 12,
                'race_mere_id' => 10,
                'race_produit_id' => 11,
                'taille_conditions' => 1,
                'automatique' => 0,
                'commentaire' => 'FS',
                'approbation' => 1,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => NULL,
            ),
            71 => 
            array (
                'id' => 89,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 12,
                'race_mere_id' => 7,
                'race_produit_id' => 11,
                'taille_conditions' => 1,
                'automatique' => 0,
                'commentaire' => 'FS',
                'approbation' => 1,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => NULL,
            ),
            72 => 
            array (
                'id' => 90,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 12,
                'race_mere_id' => 6,
                'race_produit_id' => 11,
                'taille_conditions' => 0,
                'automatique' => 0,
                'commentaire' => 'FS',
                'approbation' => 1,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => NULL,
            ),
            73 => 
            array (
                'id' => 91,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 12,
                'race_mere_id' => 4,
                'race_produit_id' => 11,
                'taille_conditions' => 0,
                'automatique' => 0,
                'commentaire' => 'FS',
                'approbation' => 1,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => NULL,
            ),
            74 => 
            array (
                'id' => 92,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 12,
                'race_mere_id' => 5,
                'race_produit_id' => 11,
                'taille_conditions' => 0,
                'automatique' => 0,
                'commentaire' => 'FS',
                'approbation' => 1,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => NULL,
            ),
            75 => 
            array (
                'id' => 93,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 4,
                'race_mere_id' => 12,
                'race_produit_id' => 11,
                'taille_conditions' => 0,
                'automatique' => 0,
                'commentaire' => 'FS',
                'approbation' => 1,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => NULL,
            ),
            76 => 
            array (
                'id' => 94,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 5,
                'race_mere_id' => 12,
                'race_produit_id' => 11,
                'taille_conditions' => 0,
                'automatique' => 0,
                'commentaire' => 'FS',
                'approbation' => 1,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => NULL,
            ),
            77 => 
            array (
                'id' => 95,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 7,
                'race_mere_id' => 12,
                'race_produit_id' => 11,
                'taille_conditions' => 1,
                'automatique' => 0,
                'commentaire' => 'FS',
                'approbation' => 1,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => NULL,
            ),
            78 => 
            array (
                'id' => 96,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 6,
                'race_mere_id' => 12,
                'race_produit_id' => 11,
                'taille_conditions' => 0,
                'automatique' => 0,
                'commentaire' => 'FS',
                'approbation' => 1,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => NULL,
            ),
            79 => 
            array (
                'id' => 97,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 13,
                'race_mere_id' => 14,
                'race_produit_id' => 14,
                'taille_conditions' => 0,
                'automatique' => 1,
                'commentaire' => 'Pottok B',
                'approbation' => 0,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => NULL,
            ),
            80 => 
            array (
                'id' => 98,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 14,
                'race_mere_id' => 13,
                'race_produit_id' => 14,
                'taille_conditions' => 0,
                'automatique' => 1,
                'commentaire' => 'Pottok B',
                'approbation' => 0,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => NULL,
            ),
            81 => 
            array (
                'id' => 99,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 13,
                'race_mere_id' => 4,
                'race_produit_id' => 14,
                'taille_conditions' => 1,
                'automatique' => 0,
                'commentaire' => 'Pottok B',
                'approbation' => 0,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => NULL,
            ),
            82 => 
            array (
                'id' => 100,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 13,
                'race_mere_id' => 5,
                'race_produit_id' => 14,
                'taille_conditions' => 1,
                'automatique' => 0,
                'commentaire' => 'Pottok B',
                'approbation' => 0,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => NULL,
            ),
            83 => 
            array (
                'id' => 101,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 13,
                'race_mere_id' => 6,
                'race_produit_id' => 14,
                'taille_conditions' => 1,
                'automatique' => 0,
                'commentaire' => 'Pottok B',
                'approbation' => 0,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => NULL,
            ),
            84 => 
            array (
                'id' => 102,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 13,
                'race_mere_id' => 7,
                'race_produit_id' => 14,
                'taille_conditions' => 1,
                'automatique' => 0,
                'commentaire' => 'Pottok B',
                'approbation' => 0,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => NULL,
            ),
            85 => 
            array (
                'id' => 103,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 13,
                'race_mere_id' => 10,
                'race_produit_id' => 14,
                'taille_conditions' => 1,
                'automatique' => 0,
                'commentaire' => 'Pottok B',
                'approbation' => 0,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => NULL,
            ),
            86 => 
            array (
                'id' => 104,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 4,
                'race_mere_id' => 13,
                'race_produit_id' => 14,
                'taille_conditions' => 1,
                'automatique' => 0,
                'commentaire' => 'Pottok B',
                'approbation' => 1,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => NULL,
            ),
            87 => 
            array (
                'id' => 105,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 5,
                'race_mere_id' => 13,
                'race_produit_id' => 14,
                'taille_conditions' => 1,
                'automatique' => 0,
                'commentaire' => 'Pottok B',
                'approbation' => 1,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => NULL,
            ),
            88 => 
            array (
                'id' => 106,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 6,
                'race_mere_id' => 13,
                'race_produit_id' => 14,
                'taille_conditions' => 1,
                'automatique' => 0,
                'commentaire' => 'Pottok B',
                'approbation' => 1,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => NULL,
            ),
            89 => 
            array (
                'id' => 107,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 7,
                'race_mere_id' => 13,
                'race_produit_id' => 14,
                'taille_conditions' => 1,
                'automatique' => 0,
                'commentaire' => 'Pottok B',
                'approbation' => 1,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => NULL,
            ),
            90 => 
            array (
                'id' => 108,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 13,
                'race_mere_id' => 12,
                'race_produit_id' => 14,
                'taille_conditions' => 1,
                'automatique' => 0,
                'commentaire' => 'Pottok B',
                'approbation' => 0,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => NULL,
            ),
            91 => 
            array (
                'id' => 109,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 13,
                'race_mere_id' => 9,
                'race_produit_id' => 14,
                'taille_conditions' => 1,
                'automatique' => 0,
                'commentaire' => 'Pottok B',
                'approbation' => 0,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => NULL,
            ),
            92 => 
            array (
                'id' => 110,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 13,
                'race_mere_id' => 8,
                'race_produit_id' => 14,
                'taille_conditions' => 1,
                'automatique' => 0,
                'commentaire' => 'Pottok B',
                'approbation' => 0,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => NULL,
            ),
            93 => 
            array (
                'id' => 111,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 13,
                'race_mere_id' => 11,
                'race_produit_id' => 14,
                'taille_conditions' => 1,
                'automatique' => 0,
                'commentaire' => 'Pottok B',
                'approbation' => 0,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => NULL,
            ),
            94 => 
            array (
                'id' => 112,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 12,
                'race_mere_id' => 13,
                'race_produit_id' => 14,
                'taille_conditions' => 1,
                'automatique' => 0,
                'commentaire' => 'Pottok B',
                'approbation' => 1,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => NULL,
            ),
            95 => 
            array (
                'id' => 113,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 9,
                'race_mere_id' => 13,
                'race_produit_id' => 14,
                'taille_conditions' => 1,
                'automatique' => 0,
                'commentaire' => 'Pottok B',
                'approbation' => 1,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => NULL,
            ),
            96 => 
            array (
                'id' => 114,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 11,
                'race_mere_id' => 13,
                'race_produit_id' => 14,
                'taille_conditions' => 1,
                'automatique' => 0,
                'commentaire' => 'Pottok B',
                'approbation' => 1,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => NULL,
            ),
            97 => 
            array (
                'id' => 115,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 8,
                'race_mere_id' => 13,
                'race_produit_id' => 14,
                'taille_conditions' => 1,
                'automatique' => 0,
                'commentaire' => 'Pottok B',
                'approbation' => 1,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => NULL,
            ),
            98 => 
            array (
                'id' => 116,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 14,
                'race_mere_id' => 11,
                'race_produit_id' => 11,
                'taille_conditions' => 0,
                'automatique' => 0,
                'commentaire' => 'FS',
                'approbation' => 1,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => NULL,
            ),
            99 => 
            array (
                'id' => 117,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 11,
                'race_mere_id' => 13,
                'race_produit_id' => 11,
                'taille_conditions' => 0,
                'automatique' => 0,
                'commentaire' => 'FS',
                'approbation' => 1,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => NULL,
            ),
            100 => 
            array (
                'id' => 118,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 11,
                'race_mere_id' => 14,
                'race_produit_id' => 11,
                'taille_conditions' => 0,
                'automatique' => 0,
                'commentaire' => 'FS',
                'approbation' => 1,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => NULL,
            ),
            101 => 
            array (
                'id' => 119,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 13,
                'race_mere_id' => 11,
                'race_produit_id' => 11,
                'taille_conditions' => 0,
                'automatique' => 0,
                'commentaire' => 'FS',
                'approbation' => 1,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => NULL,
            ),
            102 => 
            array (
                'id' => 120,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 4,
                'race_mere_id' => 13,
                'race_produit_id' => 11,
                'taille_conditions' => 0,
                'automatique' => 0,
                'commentaire' => 'FS',
                'approbation' => 1,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => NULL,
            ),
            103 => 
            array (
                'id' => 121,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 5,
                'race_mere_id' => 13,
                'race_produit_id' => 11,
                'taille_conditions' => 0,
                'automatique' => 0,
                'commentaire' => 'FS',
                'approbation' => 1,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => NULL,
            ),
            104 => 
            array (
                'id' => 122,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 4,
                'race_mere_id' => 14,
                'race_produit_id' => 11,
                'taille_conditions' => 0,
                'automatique' => 0,
                'commentaire' => 'FS',
                'approbation' => 1,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => NULL,
            ),
            105 => 
            array (
                'id' => 123,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 5,
                'race_mere_id' => 14,
                'race_produit_id' => 11,
                'taille_conditions' => 0,
                'automatique' => 0,
                'commentaire' => 'FS',
                'approbation' => 1,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => NULL,
            ),
            106 => 
            array (
                'id' => 124,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 6,
                'race_mere_id' => 13,
                'race_produit_id' => 11,
                'taille_conditions' => 0,
                'automatique' => 0,
                'commentaire' => 'FS',
                'approbation' => 1,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => NULL,
            ),
            107 => 
            array (
                'id' => 125,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 6,
                'race_mere_id' => 14,
                'race_produit_id' => 11,
                'taille_conditions' => 0,
                'automatique' => 0,
                'commentaire' => 'FS',
                'approbation' => 1,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => NULL,
            ),
            108 => 
            array (
                'id' => 126,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 7,
                'race_mere_id' => 13,
                'race_produit_id' => 11,
                'taille_conditions' => 0,
                'automatique' => 0,
                'commentaire' => 'FS',
                'approbation' => 1,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => NULL,
            ),
            109 => 
            array (
                'id' => 127,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 7,
                'race_mere_id' => 14,
                'race_produit_id' => 11,
                'taille_conditions' => 0,
                'automatique' => 0,
                'commentaire' => 'FS',
                'approbation' => 1,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => NULL,
            ),
            110 => 
            array (
                'id' => 128,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 8,
                'race_mere_id' => 14,
                'race_produit_id' => 11,
                'taille_conditions' => 1,
                'automatique' => 0,
                'commentaire' => 'FS',
                'approbation' => 1,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => NULL,
            ),
            111 => 
            array (
                'id' => 129,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 8,
                'race_mere_id' => 13,
                'race_produit_id' => 11,
                'taille_conditions' => 1,
                'automatique' => 0,
                'commentaire' => 'FS',
                'approbation' => 1,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => NULL,
            ),
            112 => 
            array (
                'id' => 130,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 10,
                'race_mere_id' => 13,
                'race_produit_id' => 11,
                'taille_conditions' => 1,
                'automatique' => 0,
                'commentaire' => 'FS',
                'approbation' => 1,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => NULL,
            ),
            113 => 
            array (
                'id' => 131,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 10,
                'race_mere_id' => 14,
                'race_produit_id' => 11,
                'taille_conditions' => 1,
                'automatique' => 0,
                'commentaire' => 'FS',
                'approbation' => 1,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => NULL,
            ),
            114 => 
            array (
                'id' => 132,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 12,
                'race_mere_id' => 13,
                'race_produit_id' => 11,
                'taille_conditions' => 0,
                'automatique' => 0,
                'commentaire' => 'FS',
                'approbation' => 1,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => NULL,
            ),
            115 => 
            array (
                'id' => 133,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 12,
                'race_mere_id' => 14,
                'race_produit_id' => 11,
                'taille_conditions' => 0,
                'automatique' => 0,
                'commentaire' => 'FS',
                'approbation' => 1,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => NULL,
            ),
            116 => 
            array (
                'id' => 134,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 13,
                'race_mere_id' => 4,
                'race_produit_id' => 11,
                'taille_conditions' => 0,
                'automatique' => 0,
                'commentaire' => 'FS',
                'approbation' => 1,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => NULL,
            ),
            117 => 
            array (
                'id' => 135,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 14,
                'race_mere_id' => 4,
                'race_produit_id' => 11,
                'taille_conditions' => 0,
                'automatique' => 0,
                'commentaire' => 'FS',
                'approbation' => 1,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => NULL,
            ),
            118 => 
            array (
                'id' => 136,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 13,
                'race_mere_id' => 5,
                'race_produit_id' => 11,
                'taille_conditions' => 0,
                'automatique' => 0,
                'commentaire' => 'FS',
                'approbation' => 1,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => NULL,
            ),
            119 => 
            array (
                'id' => 137,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 14,
                'race_mere_id' => 5,
                'race_produit_id' => 11,
                'taille_conditions' => 0,
                'automatique' => 0,
                'commentaire' => 'FS',
                'approbation' => 1,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => NULL,
            ),
            120 => 
            array (
                'id' => 138,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 13,
                'race_mere_id' => 6,
                'race_produit_id' => 11,
                'taille_conditions' => 0,
                'automatique' => 0,
                'commentaire' => 'FS',
                'approbation' => 1,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => NULL,
            ),
            121 => 
            array (
                'id' => 139,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 14,
                'race_mere_id' => 6,
                'race_produit_id' => 11,
                'taille_conditions' => 0,
                'automatique' => 0,
                'commentaire' => 'FS',
                'approbation' => 1,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => NULL,
            ),
            122 => 
            array (
                'id' => 140,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 13,
                'race_mere_id' => 7,
                'race_produit_id' => 11,
                'taille_conditions' => 0,
                'automatique' => 0,
                'commentaire' => 'FS',
                'approbation' => 1,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => NULL,
            ),
            123 => 
            array (
                'id' => 141,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 14,
                'race_mere_id' => 7,
                'race_produit_id' => 11,
                'taille_conditions' => 0,
                'automatique' => 0,
                'commentaire' => 'FS',
                'approbation' => 1,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => NULL,
            ),
            124 => 
            array (
                'id' => 142,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 13,
                'race_mere_id' => 10,
                'race_produit_id' => 11,
                'taille_conditions' => 1,
                'automatique' => 0,
                'commentaire' => 'FS',
                'approbation' => 1,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => NULL,
            ),
            125 => 
            array (
                'id' => 143,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 14,
                'race_mere_id' => 10,
                'race_produit_id' => 11,
                'taille_conditions' => 1,
                'automatique' => 0,
                'commentaire' => 'FS',
                'approbation' => 1,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => NULL,
            ),
            126 => 
            array (
                'id' => 144,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 13,
                'race_mere_id' => 12,
                'race_produit_id' => 11,
                'taille_conditions' => 0,
                'automatique' => 0,
                'commentaire' => 'FS',
                'approbation' => 1,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => NULL,
            ),
            127 => 
            array (
                'id' => 145,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 14,
                'race_mere_id' => 12,
                'race_produit_id' => 11,
                'taille_conditions' => 0,
                'automatique' => 0,
                'commentaire' => 'FS',
                'approbation' => 1,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => NULL,
            ),
            128 => 
            array (
                'id' => 146,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 15,
                'race_mere_id' => 8,
                'race_produit_id' => 15,
                'taille_conditions' => 0,
                'automatique' => 0,
                'commentaire' => 'Pintabian',
                'approbation' => 0,
                'pourCentArabe' => 99.0,
                'pourCentWelsh' => NULL,
            ),
            129 => 
            array (
                'id' => 147,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 8,
                'race_mere_id' => 15,
                'race_produit_id' => 15,
                'taille_conditions' => 0,
                'automatique' => 0,
                'commentaire' => 'Pintabian',
                'approbation' => 0,
                'pourCentArabe' => 99.0,
                'pourCentWelsh' => NULL,
            ),
            130 => 
            array (
                'id' => 148,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 8,
                'race_mere_id' => 9,
                'race_produit_id' => 15,
                'taille_conditions' => 0,
                'automatique' => 0,
                'commentaire' => 'Pintabian',
                'approbation' => 0,
                'pourCentArabe' => 99.0,
                'pourCentWelsh' => NULL,
            ),
            131 => 
            array (
                'id' => 149,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => NULL,
                'race_mere_id' => 15,
                'race_produit_id' => 8,
                'taille_conditions' => 0,
                'automatique' => 0,
                'commentaire' => 'Pintabian',
                'approbation' => 0,
                'pourCentArabe' => 99.0,
                'pourCentWelsh' => NULL,
            ),
            132 => 
            array (
                'id' => 150,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => NULL,
                'race_mere_id' => 15,
                'race_produit_id' => 9,
                'taille_conditions' => 0,
                'automatique' => 0,
                'commentaire' => 'Pintabian',
                'approbation' => 0,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => NULL,
            ),
            133 => 
            array (
                'id' => 154,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 8,
                'race_mere_id' => 18,
                'race_produit_id' => 19,
                'taille_conditions' => 0,
                'automatique' => 0,
                'commentaire' => 'AA',
                'approbation' => 0,
                'pourCentArabe' => 50.0,
                'pourCentWelsh' => NULL,
            ),
            134 => 
            array (
                'id' => 155,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 8,
                'race_mere_id' => 19,
                'race_produit_id' => 19,
                'taille_conditions' => 0,
                'automatique' => 0,
                'commentaire' => 'AA',
                'approbation' => 0,
                'pourCentArabe' => 56.25,
                'pourCentWelsh' => NULL,
            ),
            135 => 
            array (
                'id' => 156,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 18,
                'race_mere_id' => 8,
                'race_produit_id' => 19,
                'taille_conditions' => 0,
                'automatique' => 0,
                'commentaire' => 'AA',
                'approbation' => 0,
                'pourCentArabe' => 50.0,
                'pourCentWelsh' => NULL,
            ),
            136 => 
            array (
                'id' => 157,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 18,
                'race_mere_id' => 19,
                'race_produit_id' => 19,
                'taille_conditions' => 0,
                'automatique' => 0,
                'commentaire' => 'AA',
                'approbation' => 0,
                'pourCentArabe' => 12.5,
                'pourCentWelsh' => NULL,
            ),
        ));
        
        
    }
}