<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class CompetitionsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('competitions')->delete();
        
        \DB::table('competitions')->insert(array (
            0 => 
            array (
                'id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'Concours qualificatif Modèle et Allures Welsh Mountain',
                'type' => 'Modèle et Allures Tous',
                'prix_inscription' => 20,
                'prix_premier' => 100,
                'qualificatif' => 1,
                'race_id' => 4,
                'tous_poneys_sport' => 0,
                'tous_chevaux_sport' => 0,
            ),
            1 => 
            array (
                'id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'Concours qualificatif Modèle et Allures Shetland',
                'type' => 'Modèle et Allures Tous',
                'prix_inscription' => 15,
                'prix_premier' => 75,
                'qualificatif' => 1,
                'race_id' => 2,
                'tous_poneys_sport' => 0,
                'tous_chevaux_sport' => 0,
            ),
            2 => 
            array (
                'id' => 3,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'Concours qualificatif Modèle et Allures Connemara',
                'type' => 'Modèle et Allures Tous',
                'prix_inscription' => 20,
                'prix_premier' => 100,
                'qualificatif' => 1,
                'race_id' => 12,
                'tous_poneys_sport' => 0,
                'tous_chevaux_sport' => 0,
            ),
            3 => 
            array (
                'id' => 4,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'Concours qualificatif Modèle et Allures Pur-sang Arabe',
                'type' => 'Modèle et Allures Tous',
                'prix_inscription' => 30,
                'prix_premier' => 200,
                'qualificatif' => 1,
                'race_id' => 8,
                'tous_poneys_sport' => 0,
                'tous_chevaux_sport' => 0,
            ),
            4 => 
            array (
                'id' => 5,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'Concours qualificatif Modèle Et Allures Miniature',
                'type' => 'Modèle et Allures Tous',
                'prix_inscription' => 20,
                'prix_premier' => 100,
                'qualificatif' => 1,
                'race_id' => 3,
                'tous_poneys_sport' => 0,
                'tous_chevaux_sport' => 0,
            ),
            5 => 
            array (
                'id' => 6,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'Concours Modèle et Allures qualificatif Français de Selle',
                'type' => 'Modèle et Allures Tous',
                'prix_inscription' => 20,
                'prix_premier' => 100,
                'qualificatif' => 1,
                'race_id' => 11,
                'tous_poneys_sport' => 0,
                'tous_chevaux_sport' => 0,
            ),
            6 => 
            array (
                'id' => 7,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'Concours qualificatif Modèle et Allures Pottok A',
                'type' => 'Modèle et Allures mâles',
                'prix_inscription' => 15,
                'prix_premier' => 100,
                'qualificatif' => 1,
                'race_id' => 13,
                'tous_poneys_sport' => 0,
                'tous_chevaux_sport' => 0,
            ),
            7 => 
            array (
                'id' => 8,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'Concours qualificatif Modèle et Allures Welsh Pony',
                'type' => 'Modèle et Allures Tous',
                'prix_inscription' => 20,
                'prix_premier' => 100,
                'qualificatif' => 1,
                'race_id' => 5,
                'tous_poneys_sport' => 0,
                'tous_chevaux_sport' => 0,
            ),
            8 => 
            array (
                'id' => 9,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'Concours qualificatif Modèle et Allures Welsh Pony Type Cob',
                'type' => 'Modèle et Allures Tous',
                'prix_inscription' => 20,
                'prix_premier' => 100,
                'qualificatif' => 1,
                'race_id' => 6,
                'tous_poneys_sport' => 0,
                'tous_chevaux_sport' => 0,
            ),
            9 => 
            array (
                'id' => 10,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'Concours qualificatif Modèle et Allures Welsh Cob',
                'type' => 'Modèle et Allures Tous',
                'prix_inscription' => 20,
                'prix_premier' => 100,
                'qualificatif' => 1,
                'race_id' => 7,
                'tous_poneys_sport' => 0,
                'tous_chevaux_sport' => 0,
            ),
            10 => 
            array (
                'id' => 11,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'Concours qualificatif Modèle et Allures Welsh Part-Breed',
                'type' => 'Modèle et Allures Tous',
                'prix_inscription' => 20,
                'prix_premier' => 100,
                'qualificatif' => 1,
                'race_id' => 10,
                'tous_poneys_sport' => 0,
                'tous_chevaux_sport' => 0,
            ),
            11 => 
            array (
                'id' => 12,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'Concours qualificatif Modèle et Allures Pottok B',
                'type' => 'Modèle et Allures mâles',
                'prix_inscription' => 20,
                'prix_premier' => 100,
                'qualificatif' => 1,
                'race_id' => 14,
                'tous_poneys_sport' => 0,
                'tous_chevaux_sport' => 0,
            ),
            12 => 
            array (
                'id' => 13,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'Concours qualificatif Modèle et Allures Demi-sang Arabe',
                'type' => 'Modèle et Allures Tous',
                'prix_inscription' => 20,
                'prix_premier' => 100,
                'qualificatif' => 1,
                'race_id' => 9,
                'tous_poneys_sport' => 0,
                'tous_chevaux_sport' => 0,
            ),
            13 => 
            array (
                'id' => 14,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'Concours qualificatif Modèle et Allures Poneys',
                'type' => 'Modèle et Allures Tous',
                'prix_inscription' => 20,
                'prix_premier' => 100,
                'qualificatif' => 1,
                'race_id' => NULL,
                'tous_poneys_sport' => 0,
                'tous_chevaux_sport' => 0,
            ),
            14 => 
            array (
                'id' => 16,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'Concours qualificatif Modèle et Allures Welsh Mountain',
                'type' => 'Modèle et Allures Tous',
                'prix_inscription' => 20,
                'prix_premier' => 150,
                'qualificatif' => 1,
                'race_id' => 4,
                'tous_poneys_sport' => 0,
                'tous_chevaux_sport' => 0,
            ),
            15 => 
            array (
                'id' => 17,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'Concours qualificatif Modèle et Allures Shetland',
                'type' => 'Modèle et Allures Tous',
                'prix_inscription' => 15,
                'prix_premier' => 100,
                'qualificatif' => 1,
                'race_id' => 2,
                'tous_poneys_sport' => 0,
                'tous_chevaux_sport' => 0,
            ),
            16 => 
            array (
                'id' => 18,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'Concours qualificatif Modèle et Allures Connemara',
                'type' => 'Modèle et Allures Tous',
                'prix_inscription' => 20,
                'prix_premier' => 150,
                'qualificatif' => 1,
                'race_id' => 12,
                'tous_poneys_sport' => 0,
                'tous_chevaux_sport' => 0,
            ),
            17 => 
            array (
                'id' => 19,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'Concours qualificatif Modèle et Allures Pur-sang Arabe',
                'type' => 'Modèle et Allures Tous',
                'prix_inscription' => 50,
                'prix_premier' => 300,
                'qualificatif' => 1,
                'race_id' => 8,
                'tous_poneys_sport' => 0,
                'tous_chevaux_sport' => 0,
            ),
            18 => 
            array (
                'id' => 20,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'Concours qualificatif Modèle Et Allures Miniature',
                'type' => 'Modèle et Allures Tous',
                'prix_inscription' => 20,
                'prix_premier' => 150,
                'qualificatif' => 1,
                'race_id' => 3,
                'tous_poneys_sport' => 0,
                'tous_chevaux_sport' => 0,
            ),
            19 => 
            array (
                'id' => 21,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'Concours qualificatif Modèle et Allures Français de Selle',
                'type' => 'Modèle et Allures Tous',
                'prix_inscription' => 20,
                'prix_premier' => 200,
                'qualificatif' => 1,
                'race_id' => 11,
                'tous_poneys_sport' => 0,
                'tous_chevaux_sport' => 0,
            ),
            20 => 
            array (
                'id' => 22,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'Concours qualificatif Modèle et Allures Pottok A',
                'type' => 'Modèle et Allures femelles',
                'prix_inscription' => 15,
                'prix_premier' => 150,
                'qualificatif' => 1,
                'race_id' => 13,
                'tous_poneys_sport' => 0,
                'tous_chevaux_sport' => 0,
            ),
            21 => 
            array (
                'id' => 23,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'Concours qualificatif Modèle et Allures Welsh Pony',
                'type' => 'Modèle et Allures Tous',
                'prix_inscription' => 20,
                'prix_premier' => 150,
                'qualificatif' => 1,
                'race_id' => 5,
                'tous_poneys_sport' => 0,
                'tous_chevaux_sport' => 0,
            ),
            22 => 
            array (
                'id' => 24,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'Concours qualificatif Modèle et Allures Welsh Pony Type Cob',
                'type' => 'Modèle et Allures Tous',
                'prix_inscription' => 20,
                'prix_premier' => 150,
                'qualificatif' => 1,
                'race_id' => 6,
                'tous_poneys_sport' => 0,
                'tous_chevaux_sport' => 0,
            ),
            23 => 
            array (
                'id' => 25,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'Concours qualificatif Modèle et Allures Welsh Cob',
                'type' => 'Modèle et Allures Tous',
                'prix_inscription' => 20,
                'prix_premier' => 200,
                'qualificatif' => 1,
                'race_id' => 7,
                'tous_poneys_sport' => 0,
                'tous_chevaux_sport' => 0,
            ),
            24 => 
            array (
                'id' => 26,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'Concours qualificatif Modèle et Allures Welsh Part-Breed',
                'type' => 'Modèle et Allures Tous',
                'prix_inscription' => 20,
                'prix_premier' => 150,
                'qualificatif' => 1,
                'race_id' => 10,
                'tous_poneys_sport' => 0,
                'tous_chevaux_sport' => 0,
            ),
            25 => 
            array (
                'id' => 27,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'Concours qualificatif Modèle et Allures Pottok B',
                'type' => 'Modèle et Allures femelles',
                'prix_inscription' => 20,
                'prix_premier' => 150,
                'qualificatif' => 1,
                'race_id' => 14,
                'tous_poneys_sport' => 0,
                'tous_chevaux_sport' => 0,
            ),
            26 => 
            array (
                'id' => 28,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'Concours qualificatif Modèle et Allures Demi-sang Arabe',
                'type' => 'Modèle et Allures Tous',
                'prix_inscription' => 25,
                'prix_premier' => 200,
                'qualificatif' => 1,
                'race_id' => 9,
                'tous_poneys_sport' => 0,
                'tous_chevaux_sport' => 0,
            ),
            27 => 
            array (
                'id' => 29,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'Concours qualificatif poneys ',
                'type' => 'Modèle et Allures Tous',
                'prix_inscription' => 25,
                'prix_premier' => 200,
                'qualificatif' => 1,
                'race_id' => NULL,
                'tous_poneys_sport' => 1,
                'tous_chevaux_sport' => 0,
            ),
            28 => 
            array (
                'id' => 30,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'Championnat Modèle et Allures Welsh Mountain',
                'type' => 'Modèle et Allures Tous',
                'prix_inscription' => 30,
                'prix_premier' => 300,
                'qualificatif' => 0,
                'race_id' => 4,
                'tous_poneys_sport' => 0,
                'tous_chevaux_sport' => 0,
            ),
            29 => 
            array (
                'id' => 31,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'Championnat Modèle et Allures Shetland',
                'type' => 'Modèle et Allures Tous',
                'prix_inscription' => 30,
                'prix_premier' => 300,
                'qualificatif' => 0,
                'race_id' => 2,
                'tous_poneys_sport' => 0,
                'tous_chevaux_sport' => 0,
            ),
            30 => 
            array (
                'id' => 32,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'Championnat Modèle et Allures Connemara',
                'type' => 'Modèle et Allures Tous',
                'prix_inscription' => 30,
                'prix_premier' => 300,
                'qualificatif' => 0,
                'race_id' => 12,
                'tous_poneys_sport' => 0,
                'tous_chevaux_sport' => 0,
            ),
            31 => 
            array (
                'id' => 33,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'Championnat Modèle et Allures Shetland',
                'type' => 'Modèle et Allures Tous',
                'prix_inscription' => 40,
                'prix_premier' => 400,
                'qualificatif' => 0,
                'race_id' => 2,
                'tous_poneys_sport' => 0,
                'tous_chevaux_sport' => 0,
            ),
            32 => 
            array (
                'id' => 34,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'Championnat Modèle et Allures Welsh Mountain',
                'type' => 'Modèle et Allures Tous',
                'prix_inscription' => 40,
                'prix_premier' => 500,
                'qualificatif' => 0,
                'race_id' => 4,
                'tous_poneys_sport' => 0,
                'tous_chevaux_sport' => 0,
            ),
            33 => 
            array (
                'id' => 35,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'Championnat Modèle et Allures Connemara',
                'type' => 'Modèle et Allures Tous',
                'prix_inscription' => 40,
                'prix_premier' => 500,
                'qualificatif' => 0,
                'race_id' => 12,
                'tous_poneys_sport' => 0,
                'tous_chevaux_sport' => 0,
            ),
            34 => 
            array (
                'id' => 36,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'Championnat Modèle et Allures Pur-sang Arabe',
                'type' => 'Modèle et Allures Tous',
                'prix_inscription' => 40,
                'prix_premier' => 500,
                'qualificatif' => 0,
                'race_id' => 8,
                'tous_poneys_sport' => 0,
                'tous_chevaux_sport' => 0,
            ),
            35 => 
            array (
                'id' => 37,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'Championnat Modèle et Allures Pur-sang Arabe',
                'type' => 'Modèle et Allures Tous',
                'prix_inscription' => 50,
                'prix_premier' => 1000,
                'qualificatif' => 0,
                'race_id' => 8,
                'tous_poneys_sport' => 0,
                'tous_chevaux_sport' => 0,
            ),
            36 => 
            array (
                'id' => 38,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'Championnat Modèle Et Allures Miniature',
                'type' => 'Modèle et Allures Tous',
                'prix_inscription' => 25,
                'prix_premier' => 250,
                'qualificatif' => 0,
                'race_id' => 3,
                'tous_poneys_sport' => 0,
                'tous_chevaux_sport' => 0,
            ),
            37 => 
            array (
                'id' => 39,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'Championnat Modèle Et Allures Miniature',
                'type' => 'Modèle et Allures Tous',
                'prix_inscription' => 40,
                'prix_premier' => 400,
                'qualificatif' => 0,
                'race_id' => 3,
                'tous_poneys_sport' => 0,
                'tous_chevaux_sport' => 0,
            ),
            38 => 
            array (
                'id' => 40,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'Championnat Modèle et Allures Français de Selle',
                'type' => 'Modèle et Allures Tous',
                'prix_inscription' => 40,
                'prix_premier' => 600,
                'qualificatif' => 0,
                'race_id' => 11,
                'tous_poneys_sport' => 0,
                'tous_chevaux_sport' => 0,
            ),
            39 => 
            array (
                'id' => 41,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'Championnat Modèle et Allures Riding Pony Breeds',
                'type' => 'Modèle et Allures Tous',
                'prix_inscription' => 50,
                'prix_premier' => 1000,
                'qualificatif' => 0,
                'race_id' => 11,
                'tous_poneys_sport' => 0,
                'tous_chevaux_sport' => 0,
            ),
            40 => 
            array (
                'id' => 42,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'Championnat Modèle et Allures Pottok A',
                'type' => 'Modèle et Allures mâles',
                'prix_inscription' => 20,
                'prix_premier' => 400,
                'qualificatif' => 0,
                'race_id' => 13,
                'tous_poneys_sport' => 0,
                'tous_chevaux_sport' => 0,
            ),
            41 => 
            array (
                'id' => 43,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'Championnat Modèle et Allures Pottok B',
                'type' => 'Modèle et Allures mâles',
                'prix_inscription' => 20,
                'prix_premier' => 400,
                'qualificatif' => 0,
                'race_id' => 14,
                'tous_poneys_sport' => 0,
                'tous_chevaux_sport' => 0,
            ),
            42 => 
            array (
                'id' => 44,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'Championnat Modèle et Allures Demi-sang Arabe',
                'type' => 'Modèle et Allures Tous',
                'prix_inscription' => 40,
                'prix_premier' => 400,
                'qualificatif' => 0,
                'race_id' => 9,
                'tous_poneys_sport' => 0,
                'tous_chevaux_sport' => 0,
            ),
            43 => 
            array (
                'id' => 45,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'International Modèle et Allures Demi-sang Arabe',
                'type' => 'Modèle et Allures Tous',
                'prix_inscription' => 50,
                'prix_premier' => 700,
                'qualificatif' => 0,
                'race_id' => 9,
                'tous_poneys_sport' => 0,
                'tous_chevaux_sport' => 0,
            ),
            44 => 
            array (
                'id' => 46,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'Championnat Modèle et Allures Welsh Pony',
                'type' => 'Modèle et Allures Tous',
                'prix_inscription' => 40,
                'prix_premier' => 300,
                'qualificatif' => 0,
                'race_id' => 5,
                'tous_poneys_sport' => 0,
                'tous_chevaux_sport' => 0,
            ),
            45 => 
            array (
                'id' => 47,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'Championnat Modèle et Allures Welsh Pony',
                'type' => 'Modèle et Allures Tous',
                'prix_inscription' => 40,
                'prix_premier' => 500,
                'qualificatif' => 0,
                'race_id' => 5,
                'tous_poneys_sport' => 0,
                'tous_chevaux_sport' => 0,
            ),
            46 => 
            array (
                'id' => 48,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'Championnat Modèle et Allures Welsh Pony Type Cob',
                'type' => 'Modèle et Allures Tous',
                'prix_inscription' => 40,
                'prix_premier' => 300,
                'qualificatif' => 0,
                'race_id' => 6,
                'tous_poneys_sport' => 0,
                'tous_chevaux_sport' => 0,
            ),
            47 => 
            array (
                'id' => 49,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'Championnat Modèle et Allures Welsh Pony Type Cob',
                'type' => 'Modèle et Allures Tous',
                'prix_inscription' => 40,
                'prix_premier' => 500,
                'qualificatif' => 0,
                'race_id' => 6,
                'tous_poneys_sport' => 0,
                'tous_chevaux_sport' => 0,
            ),
            48 => 
            array (
                'id' => 50,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'Championnats Modèle et Allures Welsh Cob',
                'type' => 'Modèle et Allures Tous',
                'prix_inscription' => 40,
                'prix_premier' => 500,
                'qualificatif' => 0,
                'race_id' => 7,
                'tous_poneys_sport' => 0,
                'tous_chevaux_sport' => 0,
            ),
            49 => 
            array (
                'id' => 51,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'Championnat Modèle et Allures Welsh Cob',
                'type' => 'Modèle et Allures Tous',
                'prix_inscription' => 40,
                'prix_premier' => 1000,
                'qualificatif' => 0,
                'race_id' => 7,
                'tous_poneys_sport' => 0,
                'tous_chevaux_sport' => 0,
            ),
            50 => 
            array (
                'id' => 52,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'Championnat Modèle et Allures Welsh Part-Breed',
                'type' => 'Modèle et Allures Tous',
                'prix_inscription' => 40,
                'prix_premier' => 300,
                'qualificatif' => 0,
                'race_id' => 10,
                'tous_poneys_sport' => 0,
                'tous_chevaux_sport' => 0,
            ),
            51 => 
            array (
                'id' => 53,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'Championnat Modèle et Allures Welsh Part-Breed',
                'type' => 'Modèle et Allures Tous',
                'prix_inscription' => 40,
                'prix_premier' => 600,
                'qualificatif' => 0,
                'race_id' => 10,
                'tous_poneys_sport' => 0,
                'tous_chevaux_sport' => 0,
            ),
            52 => 
            array (
                'id' => 54,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'Concours Dressage Poney',
                'type' => 'Dressage poneys',
                'prix_inscription' => 10,
                'prix_premier' => 0,
                'qualificatif' => 1,
                'race_id' => NULL,
                'tous_poneys_sport' => 0,
                'tous_chevaux_sport' => 0,
            ),
            53 => 
            array (
                'id' => 55,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'concours Dressage Poney E',
                'type' => 'Dressage poneys E',
                'prix_inscription' => 10,
                'prix_premier' => 0,
                'qualificatif' => 1,
                'race_id' => NULL,
                'tous_poneys_sport' => 0,
                'tous_chevaux_sport' => 0,
            ),
            54 => 
            array (
                'id' => 56,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'Concours Dressage Poney',
                'type' => 'Dressage poneys',
                'prix_inscription' => 20,
                'prix_premier' => 0,
                'qualificatif' => 1,
                'race_id' => NULL,
                'tous_poneys_sport' => 0,
                'tous_chevaux_sport' => 0,
            ),
            55 => 
            array (
                'id' => 57,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'Concours Dressage Poney E',
                'type' => 'Dressage poneys E',
                'prix_inscription' => 25,
                'prix_premier' => 0,
                'qualificatif' => 1,
                'race_id' => NULL,
                'tous_poneys_sport' => 0,
                'tous_chevaux_sport' => 0,
            ),
            56 => 
            array (
                'id' => 58,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'Concours dressage Amateur',
                'type' => 'Dressage chevaux',
                'prix_inscription' => 15,
                'prix_premier' => 100,
                'qualificatif' => 1,
                'race_id' => NULL,
                'tous_poneys_sport' => 0,
                'tous_chevaux_sport' => 0,
            ),
            57 => 
            array (
                'id' => 59,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'Concours dressage Amateur',
                'type' => 'Dressage chevaux',
                'prix_inscription' => 25,
                'prix_premier' => 250,
                'qualificatif' => 1,
                'race_id' => NULL,
                'tous_poneys_sport' => 0,
                'tous_chevaux_sport' => 0,
            ),
            58 => 
            array (
                'id' => 60,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'Concours dressage Amateur',
                'type' => 'Dressage chevaux',
                'prix_inscription' => 40,
                'prix_premier' => 500,
                'qualificatif' => 0,
                'race_id' => NULL,
                'tous_poneys_sport' => 0,
                'tous_chevaux_sport' => 0,
            ),
            59 => 
            array (
                'id' => 61,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'Concours Dressage Pro',
                'type' => 'Dressage chevaux',
                'prix_inscription' => 50,
                'prix_premier' => 1000,
                'qualificatif' => 0,
                'race_id' => NULL,
                'tous_poneys_sport' => 0,
                'tous_chevaux_sport' => 0,
            ),
            60 => 
            array (
                'id' => 62,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'Concours Dressage Poney ',
                'type' => 'Dressage poneys',
                'prix_inscription' => 40,
                'prix_premier' => 0,
                'qualificatif' => 0,
                'race_id' => NULL,
                'tous_poneys_sport' => 0,
                'tous_chevaux_sport' => 0,
            ),
            61 => 
            array (
                'id' => 63,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'Concours Dressage Poney E',
                'type' => 'Dressage poneys E',
                'prix_inscription' => 40,
                'prix_premier' => 0,
                'qualificatif' => 0,
                'race_id' => NULL,
                'tous_poneys_sport' => 0,
                'tous_chevaux_sport' => 0,
            ),
            62 => 
            array (
                'id' => 66,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'Championnat Modèles et Allures Pottok B',
                'type' => 'Modèle et Allures femelles',
                'prix_inscription' => 20,
                'prix_premier' => 400,
                'qualificatif' => 0,
                'race_id' => 14,
                'tous_poneys_sport' => 0,
                'tous_chevaux_sport' => 0,
            ),
            63 => 
            array (
                'id' => 67,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'CChampionnat 2 et 3 ans AA',
                'type' => 'Modèle et Allures jeunes',
                'prix_inscription' => 40,
                'prix_premier' => 500,
                'qualificatif' => 0,
                'race_id' => 19,
                'tous_poneys_sport' => 0,
                'tous_chevaux_sport' => 0,
            ),
            64 => 
            array (
                'id' => 69,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'Concours qualificatif Modèle et Allures AA',
                'type' => 'Modèle et Allures Tous',
                'prix_inscription' => 25,
                'prix_premier' => 200,
                'qualificatif' => 1,
                'race_id' => 19,
                'tous_poneys_sport' => 0,
                'tous_chevaux_sport' => 0,
            ),
            65 => 
            array (
                'id' => 70,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'Concours qualificatif Selle Français',
                'type' => 'Modèle et Allures Tous',
                'prix_inscription' => 25,
                'prix_premier' => 200,
                'qualificatif' => 1,
                'race_id' => 21,
                'tous_poneys_sport' => 0,
                'tous_chevaux_sport' => 0,
            ),
            66 => 
            array (
                'id' => 71,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'Championnat mâles 2 et 3 ans SF',
                'type' => 'Modèle et Allures mâles',
                'prix_inscription' => 40,
                'prix_premier' => 500,
                'qualificatif' => 0,
                'race_id' => 21,
                'tous_poneys_sport' => 0,
                'tous_chevaux_sport' => 0,
            ),
            67 => 
            array (
                'id' => 72,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'cChampionnat femelles SF',
                'type' => 'Modèle et Allures femelles',
                'prix_inscription' => 40,
                'prix_premier' => 500,
                'qualificatif' => 0,
                'race_id' => 21,
                'tous_poneys_sport' => 0,
                'tous_chevaux_sport' => 0,
            ),
            68 => 
            array (
                'id' => 73,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'Qualificatif mâles SF 2 et 3 ans ',
                'type' => 'Modèle et Allures mâles',
                'prix_inscription' => 20,
                'prix_premier' => 200,
                'qualificatif' => 1,
                'race_id' => 21,
                'tous_poneys_sport' => 0,
                'tous_chevaux_sport' => 0,
            ),
            69 => 
            array (
                'id' => 74,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'Qualificatif femelles 2 et 3 ans SF',
                'type' => 'Modèle et Allures femelles',
                'prix_inscription' => 20,
                'prix_premier' => 200,
                'qualificatif' => 1,
                'race_id' => 21,
                'tous_poneys_sport' => 0,
                'tous_chevaux_sport' => 0,
            ),
            70 => 
            array (
                'id' => 75,
                'created_at' => NULL,
                'updated_at' => NULL,
            'nom' => 'Approbation PS pour produire en SF (qualificatif)',
                'type' => 'Modèle et Allures mâles',
                'prix_inscription' => 20,
                'prix_premier' => 200,
                'qualificatif' => 1,
                'race_id' => 18,
                'tous_poneys_sport' => 0,
                'tous_chevaux_sport' => 0,
            ),
            71 => 
            array (
                'id' => 76,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'Approbation PS pour SF',
                'type' => 'Modèle et Allures mâles',
                'prix_inscription' => 40,
                'prix_premier' => 500,
                'qualificatif' => 0,
                'race_id' => 18,
                'tous_poneys_sport' => 0,
                'tous_chevaux_sport' => 0,
            ),
            72 => 
            array (
                'id' => 77,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'Championnat Modèle et Allures Pottok A',
                'type' => 'Modèle et Allures femelles',
                'prix_inscription' => 20,
                'prix_premier' => 400,
                'qualificatif' => 0,
                'race_id' => 13,
                'tous_poneys_sport' => 0,
                'tous_chevaux_sport' => 0,
            ),
            73 => 
            array (
                'id' => 78,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'Concours Dressage Pro',
                'type' => 'Dressage chevaux',
                'prix_inscription' => 50,
                'prix_premier' => 3000,
                'qualificatif' => 0,
                'race_id' => NULL,
                'tous_poneys_sport' => 0,
                'tous_chevaux_sport' => 0,
            ),
            74 => 
            array (
                'id' => 79,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'Championnat Modèle et Allures Poneys Dressage',
                'type' => 'Modèle et Allures Dressage',
                'prix_inscription' => 30,
                'prix_premier' => 300,
                'qualificatif' => 0,
                'race_id' => NULL,
                'tous_poneys_sport' => 1,
                'tous_chevaux_sport' => 0,
            ),
            75 => 
            array (
                'id' => 80,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'Concours Modèle et Allures Chevaux Dressage',
                'type' => 'Modèle et Allures Dressage',
                'prix_inscription' => 60,
                'prix_premier' => 500,
                'qualificatif' => 0,
                'race_id' => NULL,
                'tous_poneys_sport' => 0,
                'tous_chevaux_sport' => 1,
            ),
            76 => 
            array (
                'id' => 81,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'Concours qualificatif Modèle et Allures Poneys Dressage',
                'type' => 'Modèle et Allures Dressage',
                'prix_inscription' => 20,
                'prix_premier' => 150,
                'qualificatif' => 1,
                'race_id' => NULL,
                'tous_poneys_sport' => 1,
                'tous_chevaux_sport' => 0,
            ),
            77 => 
            array (
                'id' => 82,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'Concours Modèle et Allures Chevaux Dressage',
                'type' => 'Modèle et Allures Dressage',
                'prix_inscription' => 30,
                'prix_premier' => 250,
                'qualificatif' => 1,
                'race_id' => NULL,
                'tous_poneys_sport' => 0,
                'tous_chevaux_sport' => 1,
            ),
            78 => 
            array (
                'id' => 83,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'Concours International Modèle et Allures Lusitaniens',
                'type' => 'Modèle et Allures Tous',
                'prix_inscription' => 100,
                'prix_premier' => 1000,
                'qualificatif' => 0,
                'race_id' => 23,
                'tous_poneys_sport' => 0,
                'tous_chevaux_sport' => 0,
            ),
            79 => 
            array (
                'id' => 84,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'Concours National Modèle et Allures Lusitaniens',
                'type' => 'Modèle et Allures Tous',
                'prix_inscription' => 60,
                'prix_premier' => 700,
                'qualificatif' => 0,
                'race_id' => 23,
                'tous_poneys_sport' => 0,
                'tous_chevaux_sport' => 0,
            ),
            80 => 
            array (
                'id' => 85,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'Concours Régional Modèle et Allures Lusitaniens',
                'type' => 'Modèle et Allures Tous',
                'prix_inscription' => 40,
                'prix_premier' => 400,
                'qualificatif' => 1,
                'race_id' => 23,
                'tous_poneys_sport' => 0,
                'tous_chevaux_sport' => 0,
            ),
            81 => 
            array (
                'id' => 86,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'Labellisation SF des juments',
                'type' => 'Modèle et Allures femelles',
                'prix_inscription' => 40,
                'prix_premier' => 400,
                'qualificatif' => 1,
                'race_id' => NULL,
                'tous_poneys_sport' => 0,
                'tous_chevaux_sport' => 1,
            ),
            82 => 
            array (
                'id' => 87,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'Criterium dressage OC',
                'type' => 'Modèle et Allures Dressage',
                'prix_inscription' => 30,
                'prix_premier' => 300,
                'qualificatif' => 1,
                'race_id' => 1,
                'tous_poneys_sport' => 0,
                'tous_chevaux_sport' => 0,
            ),
            83 => 
            array (
                'id' => 88,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'Criterium National dressage OC',
                'type' => 'Modèle et Allures Dressage',
                'prix_inscription' => 40,
                'prix_premier' => 400,
                'qualificatif' => 0,
                'race_id' => 1,
                'tous_poneys_sport' => 0,
                'tous_chevaux_sport' => 0,
            ),
            84 => 
            array (
                'id' => 89,
                'created_at' => NULL,
                'updated_at' => NULL,
            'nom' => 'Approbation TF pour produire en SF (qualificatif)',
                'type' => 'Modèle et Allures mâles',
                'prix_inscription' => 20,
                'prix_premier' => 200,
                'qualificatif' => 1,
                'race_id' => 20,
                'tous_poneys_sport' => 0,
                'tous_chevaux_sport' => 0,
            ),
            85 => 
            array (
                'id' => 90,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'Approbation TF pour produire en SF',
                'type' => 'Modèle et Allures mâles',
                'prix_inscription' => 20,
                'prix_premier' => 200,
                'qualificatif' => 0,
                'race_id' => 20,
                'tous_poneys_sport' => 0,
                'tous_chevaux_sport' => 0,
            ),
        ));
        
        
    }
}