<?php

use Illuminate\Database\Seeder;

class AnimauxTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('animaux')->delete();
        
        \DB::table('animaux')->insert(array (
            0 => 
            array (
                'id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'Mignonne',
                'affixe_id' => 1,
                'couleur' => NULL,
                'taille_cm' => 99,
                'race_id' => 2,
                'sexe' => 'femelle',
                'date_achat' => '1970-01-11',
                'date_naissance' => '1966-05-13',
                'a_vendre' => 0,
                'prix' => NULL,
                'elevage_id' => 1,
                'fondateur' => 1,
                'foetus' => 0,
                'consang' => 0.0,
                'sire_id' => NULL,
                'dam_id' => NULL,
                'taille_additive' => 99,
            ),
            1 => 
            array (
                'id' => 3,
                'created_at' => NULL,
                'updated_at' => '2020-05-22 20:52:57',
                'nom' => 'Popeye',
                'affixe_id' => 3,
                'couleur' => NULL,
                'taille_cm' => 102,
                'race_id' => 2,
                'sexe' => 'mâle',
                'date_achat' => '1970-02-11',
                'date_naissance' => '1969-04-15',
                'a_vendre' => 0,
                'prix' => NULL,
                'elevage_id' => 1,
                'fondateur' => 1,
                'foetus' => 0,
                'consang' => 0.0,
                'sire_id' => NULL,
                'dam_id' => NULL,
                'taille_additive' => 102,
            ),
            2 => 
            array (
                'id' => 4,
                'created_at' => NULL,
                'updated_at' => '2020-02-16 17:13:00',
                'nom' => 'Diana',
                'affixe_id' => 4,
                'couleur' => NULL,
                'taille_cm' => 114,
                'race_id' => 4,
                'sexe' => 'femelle',
                'date_achat' => NULL,
                'date_naissance' => '1965-04-12',
                'a_vendre' => 0,
                'prix' => 1500,
                'elevage_id' => 4,
                'fondateur' => 1,
                'foetus' => 0,
                'consang' => 0.0,
                'sire_id' => NULL,
                'dam_id' => NULL,
                'taille_additive' => 114,
            ),
            3 => 
            array (
                'id' => 5,
                'created_at' => NULL,
                'updated_at' => '2020-05-22 20:55:11',
                'nom' => 'Molly',
                'affixe_id' => 3,
                'couleur' => NULL,
                'taille_cm' => 106,
                'race_id' => 2,
                'sexe' => 'femelle',
                'date_achat' => '1970-02-16',
                'date_naissance' => '1969-06-16',
                'a_vendre' => 0,
                'prix' => NULL,
                'elevage_id' => 1,
                'fondateur' => 1,
                'foetus' => 0,
                'consang' => 0.0,
                'sire_id' => NULL,
                'dam_id' => NULL,
                'taille_additive' => 106,
            ),
            4 => 
            array (
                'id' => 6,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => ' Myrrdhin',
                'affixe_id' => 5,
                'couleur' => NULL,
                'taille_cm' => 117,
                'race_id' => 4,
                'sexe' => 'mâle',
                'date_achat' => NULL,
                'date_naissance' => '1967-02-13',
                'a_vendre' => 0,
                'prix' => NULL,
                'elevage_id' => 4,
                'fondateur' => 1,
                'foetus' => 0,
                'consang' => 0.0,
                'sire_id' => NULL,
                'dam_id' => NULL,
                'taille_additive' => 117,
            ),
            5 => 
            array (
                'id' => 7,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'Keridwen',
                'affixe_id' => 5,
                'couleur' => NULL,
                'taille_cm' => 111,
                'race_id' => 4,
                'sexe' => 'femelle',
                'date_achat' => NULL,
                'date_naissance' => '1966-05-18',
                'a_vendre' => 0,
                'prix' => NULL,
                'elevage_id' => 4,
                'fondateur' => 1,
                'foetus' => 0,
                'consang' => 0.0,
                'sire_id' => NULL,
                'dam_id' => NULL,
                'taille_additive' => 121,
            ),
            6 => 
            array (
                'id' => 8,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'Django',
                'affixe_id' => NULL,
                'couleur' => NULL,
                'taille_cm' => 77,
                'race_id' => 3,
                'sexe' => 'mâle',
                'date_achat' => NULL,
                'date_naissance' => '1967-05-23',
                'a_vendre' => 0,
                'prix' => NULL,
                'elevage_id' => 5,
                'fondateur' => 1,
                'foetus' => 0,
                'consang' => 0.0,
                'sire_id' => NULL,
                'dam_id' => NULL,
                'taille_additive' => 101,
            ),
            7 => 
            array (
                'id' => 9,
                'created_at' => NULL,
                'updated_at' => '2020-05-22 20:52:56',
                'nom' => 'Owen',
                'affixe_id' => 4,
                'couleur' => NULL,
                'taille_cm' => 118,
                'race_id' => 4,
                'sexe' => 'mâle',
                'date_achat' => NULL,
                'date_naissance' => '1969-03-21',
                'a_vendre' => 0,
                'prix' => NULL,
                'elevage_id' => 4,
                'fondateur' => 1,
                'foetus' => 0,
                'consang' => 0.0,
                'sire_id' => NULL,
                'dam_id' => NULL,
                'taille_additive' => 118,
            ),
            8 => 
            array (
                'id' => 10,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => ' Lizzy',
                'affixe_id' => 11,
                'couleur' => NULL,
                'taille_cm' => 113,
                'race_id' => 4,
                'sexe' => 'femelle',
                'date_achat' => NULL,
                'date_naissance' => '1966-04-21',
                'a_vendre' => 0,
                'prix' => NULL,
                'elevage_id' => 4,
                'fondateur' => 1,
                'foetus' => 0,
                'consang' => 0.0,
                'sire_id' => NULL,
                'dam_id' => NULL,
                'taille_additive' => 113,
            ),
            9 => 
            array (
                'id' => 11,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => ' Hero',
                'affixe_id' => 8,
                'couleur' => NULL,
                'taille_cm' => 120,
                'race_id' => 4,
                'sexe' => 'mâle',
                'date_achat' => NULL,
                'date_naissance' => '1966-05-31',
                'a_vendre' => 0,
                'prix' => NULL,
                'elevage_id' => 4,
                'fondateur' => 1,
                'foetus' => 0,
                'consang' => 0.0,
                'sire_id' => NULL,
                'dam_id' => NULL,
                'taille_additive' => 120,
            ),
            10 => 
            array (
                'id' => 12,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'Comet',
                'affixe_id' => 12,
                'couleur' => NULL,
                'taille_cm' => 119,
                'race_id' => 4,
                'sexe' => 'mâle',
                'date_achat' => NULL,
                'date_naissance' => '1965-04-18',
                'a_vendre' => 0,
                'prix' => NULL,
                'elevage_id' => 4,
                'fondateur' => 1,
                'foetus' => 0,
                'consang' => 0.0,
                'sire_id' => NULL,
                'dam_id' => NULL,
                'taille_additive' => 119,
            ),
            11 => 
            array (
                'id' => 13,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'Daffodil',
                'affixe_id' => 7,
                'couleur' => NULL,
                'taille_cm' => 109,
                'race_id' => 4,
                'sexe' => 'femelle',
                'date_achat' => NULL,
                'date_naissance' => '1966-03-24',
                'a_vendre' => 0,
                'prix' => NULL,
                'elevage_id' => 4,
                'fondateur' => 1,
                'foetus' => 0,
                'consang' => 0.0,
                'sire_id' => NULL,
                'dam_id' => NULL,
                'taille_additive' => 129,
            ),
            12 => 
            array (
                'id' => 14,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => ' Davy',
                'affixe_id' => 6,
                'couleur' => NULL,
                'taille_cm' => 112,
                'race_id' => 4,
                'sexe' => 'mâle',
                'date_achat' => NULL,
                'date_naissance' => '1965-04-25',
                'a_vendre' => 0,
                'prix' => NULL,
                'elevage_id' => 4,
                'fondateur' => 1,
                'foetus' => 0,
                'consang' => 0.0,
                'sire_id' => NULL,
                'dam_id' => NULL,
                'taille_additive' => 122,
            ),
            13 => 
            array (
                'id' => 17,
                'created_at' => NULL,
                'updated_at' => '2020-05-22 20:55:11',
                'nom' => 'Poppy',
                'affixe_id' => 2,
                'couleur' => NULL,
                'taille_cm' => 91,
                'race_id' => 2,
                'sexe' => 'femelle',
                'date_achat' => NULL,
                'date_naissance' => '1969-06-25',
                'a_vendre' => 0,
                'prix' => NULL,
                'elevage_id' => 1,
                'fondateur' => 1,
                'foetus' => 0,
                'consang' => 0.0,
                'sire_id' => NULL,
                'dam_id' => NULL,
                'taille_additive' => 101,
            ),
            14 => 
            array (
                'id' => 18,
                'created_at' => NULL,
                'updated_at' => '2020-05-22 20:52:56',
                'nom' => 'Millie',
                'affixe_id' => 9,
                'couleur' => NULL,
                'taille_cm' => 99,
                'race_id' => 2,
                'sexe' => 'femelle',
                'date_achat' => NULL,
                'date_naissance' => '1969-03-22',
                'a_vendre' => 0,
                'prix' => NULL,
                'elevage_id' => 1,
                'fondateur' => 1,
                'foetus' => 0,
                'consang' => 0.0,
                'sire_id' => NULL,
                'dam_id' => NULL,
                'taille_additive' => 99,
            ),
            15 => 
            array (
                'id' => 19,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'Calliope',
                'affixe_id' => 8,
                'couleur' => NULL,
                'taille_cm' => 112,
                'race_id' => 4,
                'sexe' => 'femelle',
                'date_achat' => NULL,
                'date_naissance' => '1965-05-25',
                'a_vendre' => 0,
                'prix' => NULL,
                'elevage_id' => 4,
                'fondateur' => 1,
                'foetus' => 0,
                'consang' => 0.0,
                'sire_id' => NULL,
                'dam_id' => NULL,
                'taille_additive' => 112,
            ),
            16 => 
            array (
                'id' => 20,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'Brutus',
                'affixe_id' => 15,
                'couleur' => NULL,
                'taille_cm' => 103,
                'race_id' => 2,
                'sexe' => 'mâle',
                'date_achat' => NULL,
                'date_naissance' => '1965-03-29',
                'a_vendre' => 0,
                'prix' => NULL,
                'elevage_id' => 1,
                'fondateur' => 1,
                'foetus' => 0,
                'consang' => 0.0,
                'sire_id' => NULL,
                'dam_id' => NULL,
                'taille_additive' => 103,
            ),
            17 => 
            array (
                'id' => 21,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'Primrose',
                'affixe_id' => 16,
                'couleur' => NULL,
                'taille_cm' => 95,
                'race_id' => 2,
                'sexe' => 'femelle',
                'date_achat' => NULL,
                'date_naissance' => '1967-03-25',
                'a_vendre' => 0,
                'prix' => NULL,
                'elevage_id' => 1,
                'fondateur' => 1,
                'foetus' => 0,
                'consang' => 0.0,
                'sire_id' => NULL,
                'dam_id' => NULL,
                'taille_additive' => 105,
            ),
            18 => 
            array (
                'id' => 22,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'Andy',
                'affixe_id' => 16,
                'couleur' => NULL,
                'taille_cm' => 98,
                'race_id' => 2,
                'sexe' => 'mâle',
                'date_achat' => NULL,
                'date_naissance' => '1966-03-25',
                'a_vendre' => 0,
                'prix' => NULL,
                'elevage_id' => 1,
                'fondateur' => 1,
                'foetus' => 0,
                'consang' => 0.0,
                'sire_id' => NULL,
                'dam_id' => NULL,
                'taille_additive' => 98,
            ),
            19 => 
            array (
                'id' => 23,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'Lily',
                'affixe_id' => 15,
                'couleur' => NULL,
                'taille_cm' => 87,
                'race_id' => 2,
                'sexe' => 'femelle',
                'date_achat' => NULL,
                'date_naissance' => '1966-03-28',
                'a_vendre' => 0,
                'prix' => NULL,
                'elevage_id' => 1,
                'fondateur' => 1,
                'foetus' => 0,
                'consang' => 0.0,
                'sire_id' => NULL,
                'dam_id' => NULL,
                'taille_additive' => 109,
            ),
            20 => 
            array (
                'id' => 24,
                'created_at' => NULL,
                'updated_at' => '2020-05-22 20:52:40',
                'nom' => 'Beryl',
                'affixe_id' => 13,
                'couleur' => NULL,
                'taille_cm' => 94,
                'race_id' => 2,
                'sexe' => 'femelle',
                'date_achat' => NULL,
                'date_naissance' => '1968-05-28',
                'a_vendre' => 0,
                'prix' => NULL,
                'elevage_id' => 1,
                'fondateur' => 1,
                'foetus' => 0,
                'consang' => 0.0,
                'sire_id' => NULL,
                'dam_id' => NULL,
                'taille_additive' => 114,
            ),
            21 => 
            array (
                'id' => 25,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'Mistigri',
                'affixe_id' => 2,
                'couleur' => NULL,
                'taille_cm' => 97,
                'race_id' => 2,
                'sexe' => 'mâle',
                'date_achat' => NULL,
                'date_naissance' => '1966-04-28',
                'a_vendre' => 0,
                'prix' => NULL,
                'elevage_id' => 1,
                'fondateur' => 1,
                'foetus' => 0,
                'consang' => 0.0,
                'sire_id' => NULL,
                'dam_id' => NULL,
                'taille_additive' => 107,
            ),
            22 => 
            array (
                'id' => 26,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'Bobine',
                'affixe_id' => 17,
                'couleur' => NULL,
                'taille_cm' => 101,
                'race_id' => 2,
                'sexe' => 'femelle',
                'date_achat' => NULL,
                'date_naissance' => '1967-06-28',
                'a_vendre' => 0,
                'prix' => NULL,
                'elevage_id' => 1,
                'fondateur' => 1,
                'foetus' => 0,
                'consang' => 0.0,
                'sire_id' => NULL,
                'dam_id' => NULL,
                'taille_additive' => 101,
            ),
            23 => 
            array (
                'id' => 27,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'Rose',
                'affixe_id' => 10,
                'couleur' => NULL,
                'taille_cm' => 91,
                'race_id' => 2,
                'sexe' => 'jeune femelle',
                'date_achat' => NULL,
                'date_naissance' => '1970-06-28',
                'a_vendre' => 0,
                'prix' => NULL,
                'elevage_id' => 1,
                'fondateur' => 1,
                'foetus' => 0,
                'consang' => 0.0,
                'sire_id' => NULL,
                'dam_id' => NULL,
                'taille_additive' => 113,
            ),
            24 => 
            array (
                'id' => 28,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'Viking',
                'affixe_id' => 18,
                'couleur' => NULL,
                'taille_cm' => 89,
                'race_id' => 2,
                'sexe' => 'jeune mâle',
                'date_achat' => NULL,
                'date_naissance' => '1970-03-28',
                'a_vendre' => 0,
                'prix' => NULL,
                'elevage_id' => 1,
                'fondateur' => 1,
                'foetus' => 0,
                'consang' => 0.0,
                'sire_id' => NULL,
                'dam_id' => NULL,
                'taille_additive' => 111,
            ),
            25 => 
            array (
                'id' => 29,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'Ruby',
                'affixe_id' => 18,
                'couleur' => NULL,
                'taille_cm' => 96,
                'race_id' => 2,
                'sexe' => 'femelle',
                'date_achat' => NULL,
                'date_naissance' => '1965-03-28',
                'a_vendre' => 0,
                'prix' => NULL,
                'elevage_id' => 1,
                'fondateur' => 1,
                'foetus' => 0,
                'consang' => 0.0,
                'sire_id' => NULL,
                'dam_id' => NULL,
                'taille_additive' => 106,
            ),
            26 => 
            array (
                'id' => 30,
                'created_at' => NULL,
                'updated_at' => '2020-05-22 20:52:57',
                'nom' => 'Odin',
                'affixe_id' => 13,
                'couleur' => NULL,
                'taille_cm' => 98,
                'race_id' => 2,
                'sexe' => 'mâle',
                'date_achat' => NULL,
                'date_naissance' => '1969-04-29',
                'a_vendre' => 0,
                'prix' => NULL,
                'elevage_id' => 1,
                'fondateur' => 1,
                'foetus' => 0,
                'consang' => 0.0,
                'sire_id' => NULL,
                'dam_id' => NULL,
                'taille_additive' => 108,
            ),
            27 => 
            array (
                'id' => 31,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'Salsa',
                'affixe_id' => 19,
                'couleur' => NULL,
                'taille_cm' => 103,
                'race_id' => 2,
                'sexe' => 'jeune femelle',
                'date_achat' => NULL,
                'date_naissance' => '1970-03-29',
                'a_vendre' => 0,
                'prix' => NULL,
                'elevage_id' => 1,
                'fondateur' => 1,
                'foetus' => 0,
                'consang' => 0.0,
                'sire_id' => NULL,
                'dam_id' => NULL,
                'taille_additive' => 103,
            ),
            28 => 
            array (
                'id' => 32,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'Captain',
                'affixe_id' => 1,
                'couleur' => NULL,
                'taille_cm' => 88,
                'race_id' => 2,
                'sexe' => 'mâle',
                'date_achat' => NULL,
                'date_naissance' => '1966-05-29',
                'a_vendre' => 0,
                'prix' => NULL,
                'elevage_id' => 1,
                'fondateur' => 1,
                'foetus' => 0,
                'consang' => 0.0,
                'sire_id' => NULL,
                'dam_id' => NULL,
                'taille_additive' => 98,
            ),
            29 => 
            array (
                'id' => 33,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'Pitchoun',
                'affixe_id' => 19,
                'couleur' => NULL,
                'taille_cm' => 107,
                'race_id' => 2,
                'sexe' => 'mâle',
                'date_achat' => NULL,
                'date_naissance' => '1965-04-29',
                'a_vendre' => 0,
                'prix' => NULL,
                'elevage_id' => 1,
                'fondateur' => 1,
                'foetus' => 0,
                'consang' => 0.0,
                'sire_id' => NULL,
                'dam_id' => NULL,
                'taille_additive' => 107,
            ),
            30 => 
            array (
                'id' => 34,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'Sonia',
                'affixe_id' => 20,
                'couleur' => NULL,
                'taille_cm' => 105,
                'race_id' => 2,
                'sexe' => 'femelle',
                'date_achat' => NULL,
                'date_naissance' => '1965-03-29',
                'a_vendre' => 0,
                'prix' => NULL,
                'elevage_id' => 1,
                'fondateur' => 1,
                'foetus' => 0,
                'consang' => 0.0,
                'sire_id' => NULL,
                'dam_id' => NULL,
                'taille_additive' => 105,
            ),
            31 => 
            array (
                'id' => 35,
                'created_at' => NULL,
                'updated_at' => '2020-05-22 20:55:11',
                'nom' => 'Alezane',
                'affixe_id' => 21,
                'couleur' => NULL,
                'taille_cm' => 104,
                'race_id' => 2,
                'sexe' => 'femelle',
                'date_achat' => NULL,
                'date_naissance' => '1969-06-29',
                'a_vendre' => 0,
                'prix' => NULL,
                'elevage_id' => 1,
                'fondateur' => 1,
                'foetus' => 0,
                'consang' => 0.0,
                'sire_id' => NULL,
                'dam_id' => NULL,
                'taille_additive' => 108,
            ),
            32 => 
            array (
                'id' => 36,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'Sally',
                'affixe_id' => 22,
                'couleur' => NULL,
                'taille_cm' => 103,
                'race_id' => 2,
                'sexe' => 'femelle',
                'date_achat' => NULL,
                'date_naissance' => '1965-03-14',
                'a_vendre' => 0,
                'prix' => NULL,
                'elevage_id' => 1,
                'fondateur' => 1,
                'foetus' => 0,
                'consang' => 0.0,
                'sire_id' => NULL,
                'dam_id' => NULL,
                'taille_additive' => 105,
            ),
            33 => 
            array (
                'id' => 37,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'Poupette',
                'affixe_id' => NULL,
                'couleur' => NULL,
                'taille_cm' => 63,
                'race_id' => 3,
                'sexe' => 'femelle',
                'date_achat' => NULL,
                'date_naissance' => '1965-04-05',
                'a_vendre' => 0,
                'prix' => NULL,
                'elevage_id' => 5,
                'fondateur' => 1,
                'foetus' => 0,
                'consang' => 0.0,
                'sire_id' => NULL,
                'dam_id' => NULL,
                'taille_additive' => 98,
            ),
            34 => 
            array (
                'id' => 38,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'Thumbellina',
                'affixe_id' => NULL,
                'couleur' => NULL,
                'taille_cm' => 45,
                'race_id' => 3,
                'sexe' => 'femelle',
                'date_achat' => NULL,
                'date_naissance' => '1966-04-09',
                'a_vendre' => 0,
                'prix' => NULL,
                'elevage_id' => 5,
                'fondateur' => 1,
                'foetus' => 0,
                'consang' => 0.0,
                'sire_id' => NULL,
                'dam_id' => NULL,
                'taille_additive' => 93,
            ),
            35 => 
            array (
                'id' => 39,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'Tom Pouce',
                'affixe_id' => NULL,
                'couleur' => NULL,
                'taille_cm' => 55,
                'race_id' => 3,
                'sexe' => 'mâle',
                'date_achat' => NULL,
                'date_naissance' => '1966-04-09',
                'a_vendre' => 0,
                'prix' => NULL,
                'elevage_id' => 5,
                'fondateur' => 1,
                'foetus' => 0,
                'consang' => 0.0,
                'sire_id' => NULL,
                'dam_id' => NULL,
                'taille_additive' => 91,
            ),
            36 => 
            array (
                'id' => 40,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'Honey',
                'affixe_id' => NULL,
                'couleur' => NULL,
                'taille_cm' => 65,
                'race_id' => 3,
                'sexe' => 'femelle',
                'date_achat' => NULL,
                'date_naissance' => '1967-05-11',
                'a_vendre' => 0,
                'prix' => NULL,
                'elevage_id' => 5,
                'fondateur' => 1,
                'foetus' => 0,
                'consang' => 0.0,
                'sire_id' => NULL,
                'dam_id' => NULL,
                'taille_additive' => 85,
            ),
            37 => 
            array (
                'id' => 41,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'Lady Rose',
                'affixe_id' => 28,
                'couleur' => NULL,
                'taille_cm' => 125,
                'race_id' => 5,
                'sexe' => 'femelle',
                'date_achat' => NULL,
                'date_naissance' => '1968-05-11',
                'a_vendre' => 0,
                'prix' => NULL,
                'elevage_id' => 4,
                'fondateur' => 1,
                'foetus' => 0,
                'consang' => 0.0,
                'sire_id' => NULL,
                'dam_id' => NULL,
                'taille_additive' => 125,
            ),
            38 => 
            array (
                'id' => 42,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'Flicka',
                'affixe_id' => 36,
                'couleur' => NULL,
                'taille_cm' => 119,
                'race_id' => 4,
                'sexe' => 'femelle',
                'date_achat' => NULL,
                'date_naissance' => '1967-05-11',
                'a_vendre' => 0,
                'prix' => NULL,
                'elevage_id' => 4,
                'fondateur' => 1,
                'foetus' => 0,
                'consang' => 0.0,
                'sire_id' => NULL,
                'dam_id' => NULL,
                'taille_additive' => 119,
            ),
            39 => 
            array (
                'id' => 43,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'Superstar',
                'affixe_id' => 27,
                'couleur' => NULL,
                'taille_cm' => 135,
                'race_id' => 5,
                'sexe' => 'mâle',
                'date_achat' => NULL,
                'date_naissance' => '1968-05-11',
                'a_vendre' => 0,
                'prix' => NULL,
                'elevage_id' => 4,
                'fondateur' => 1,
                'foetus' => 0,
                'consang' => 0.0,
                'sire_id' => NULL,
                'dam_id' => NULL,
                'taille_additive' => 135,
            ),
            40 => 
            array (
                'id' => 44,
                'created_at' => NULL,
                'updated_at' => '2020-05-22 20:52:57',
                'nom' => 'Swanlake',
                'affixe_id' => 27,
                'couleur' => NULL,
                'taille_cm' => 132,
                'race_id' => 5,
                'sexe' => 'femelle',
                'date_achat' => NULL,
                'date_naissance' => '1969-05-11',
                'a_vendre' => 0,
                'prix' => NULL,
                'elevage_id' => 4,
                'fondateur' => 1,
                'foetus' => 0,
                'consang' => 0.0,
                'sire_id' => NULL,
                'dam_id' => NULL,
                'taille_additive' => 132,
            ),
            41 => 
            array (
                'id' => 45,
                'created_at' => NULL,
                'updated_at' => '2020-05-22 20:52:57',
                'nom' => 'Serenade',
                'affixe_id' => 35,
                'couleur' => NULL,
                'taille_cm' => 116,
                'race_id' => 4,
                'sexe' => 'femelle',
                'date_achat' => NULL,
                'date_naissance' => '1969-05-11',
                'a_vendre' => 0,
                'prix' => NULL,
                'elevage_id' => 4,
                'fondateur' => 1,
                'foetus' => 0,
                'consang' => 0.0,
                'sire_id' => NULL,
                'dam_id' => NULL,
                'taille_additive' => 116,
            ),
            42 => 
            array (
                'id' => 46,
                'created_at' => NULL,
                'updated_at' => '2020-05-22 20:52:57',
                'nom' => 'Sunset',
                'affixe_id' => 29,
                'couleur' => NULL,
                'taille_cm' => 110,
                'race_id' => 4,
                'sexe' => 'mâle',
                'date_achat' => NULL,
                'date_naissance' => '1969-05-11',
                'a_vendre' => 0,
                'prix' => NULL,
                'elevage_id' => 4,
                'fondateur' => 1,
                'foetus' => 0,
                'consang' => 0.0,
                'sire_id' => NULL,
                'dam_id' => NULL,
                'taille_additive' => 120,
            ),
            43 => 
            array (
                'id' => 47,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'Ivy',
                'affixe_id' => 29,
                'couleur' => NULL,
                'taille_cm' => 110,
                'race_id' => 4,
                'sexe' => 'femelle',
                'date_achat' => NULL,
                'date_naissance' => '1967-05-11',
                'a_vendre' => 0,
                'prix' => NULL,
                'elevage_id' => 4,
                'fondateur' => 1,
                'foetus' => 0,
                'consang' => 0.0,
                'sire_id' => NULL,
                'dam_id' => NULL,
                'taille_additive' => 110,
            ),
            44 => 
            array (
                'id' => 48,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'Masquerade',
                'affixe_id' => 37,
                'couleur' => NULL,
                'taille_cm' => 136,
                'race_id' => 5,
                'sexe' => 'mâle',
                'date_achat' => NULL,
                'date_naissance' => '1968-05-11',
                'a_vendre' => 0,
                'prix' => NULL,
                'elevage_id' => 4,
                'fondateur' => 1,
                'foetus' => 0,
                'consang' => 0.0,
                'sire_id' => NULL,
                'dam_id' => NULL,
                'taille_additive' => 136,
            ),
            45 => 
            array (
                'id' => 49,
                'created_at' => NULL,
                'updated_at' => '2020-05-22 20:52:38',
                'nom' => 'Surprise ',
                'affixe_id' => 37,
                'couleur' => NULL,
                'taille_cm' => 133,
                'race_id' => 5,
                'sexe' => 'femelle',
                'date_achat' => NULL,
                'date_naissance' => '1968-05-11',
                'a_vendre' => 0,
                'prix' => NULL,
                'elevage_id' => 4,
                'fondateur' => 1,
                'foetus' => 0,
                'consang' => 0.0,
                'sire_id' => NULL,
                'dam_id' => NULL,
                'taille_additive' => 133,
            ),
            46 => 
            array (
                'id' => 50,
                'created_at' => NULL,
                'updated_at' => '2020-05-12 14:38:36',
                'nom' => 'Messaoud II',
                'affixe_id' => NULL,
                'couleur' => NULL,
                'taille_cm' => 151,
                'race_id' => 8,
                'sexe' => 'mâle',
                'date_achat' => '1970-04-01',
                'date_naissance' => '1967-05-11',
                'a_vendre' => 0,
                'prix' => 100,
                'elevage_id' => 7,
                'fondateur' => 1,
                'foetus' => 0,
                'consang' => 0.0,
                'sire_id' => NULL,
                'dam_id' => NULL,
                'taille_additive' => 151,
            ),
            47 => 
            array (
                'id' => 51,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'Carolina',
                'affixe_id' => 6,
                'couleur' => NULL,
                'taille_cm' => 114,
                'race_id' => 4,
                'sexe' => 'femelle',
                'date_achat' => NULL,
                'date_naissance' => '1968-05-12',
                'a_vendre' => 0,
                'prix' => NULL,
                'elevage_id' => 4,
                'fondateur' => 1,
                'foetus' => 0,
                'consang' => 0.0,
                'sire_id' => NULL,
                'dam_id' => NULL,
                'taille_additive' => 114,
            ),
            48 => 
            array (
                'id' => 52,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'Samira',
                'affixe_id' => NULL,
                'couleur' => NULL,
                'taille_cm' => 148,
                'race_id' => 8,
                'sexe' => 'femelle',
                'date_achat' => NULL,
                'date_naissance' => '1968-05-12',
                'a_vendre' => 0,
                'prix' => NULL,
                'elevage_id' => 7,
                'fondateur' => 1,
                'foetus' => 0,
                'consang' => 0.0,
                'sire_id' => NULL,
                'dam_id' => NULL,
                'taille_additive' => 148,
            ),
            49 => 
            array (
                'id' => 53,
                'created_at' => NULL,
                'updated_at' => '2020-05-22 20:55:08',
                'nom' => 'Jalila',
                'affixe_id' => NULL,
                'couleur' => NULL,
                'taille_cm' => 153,
                'race_id' => 8,
                'sexe' => 'femelle',
                'date_achat' => NULL,
                'date_naissance' => '1969-05-12',
                'a_vendre' => 0,
                'prix' => NULL,
                'elevage_id' => 7,
                'fondateur' => 1,
                'foetus' => 0,
                'consang' => 0.0,
                'sire_id' => NULL,
                'dam_id' => NULL,
                'taille_additive' => 153,
            ),
            50 => 
            array (
                'id' => 54,
                'created_at' => NULL,
                'updated_at' => '2020-05-22 20:55:08',
                'nom' => 'Touthmosis',
                'affixe_id' => NULL,
                'couleur' => NULL,
                'taille_cm' => 154,
                'race_id' => 8,
                'sexe' => 'mâle',
                'date_achat' => NULL,
                'date_naissance' => '1969-05-12',
                'a_vendre' => 0,
                'prix' => NULL,
                'elevage_id' => 7,
                'fondateur' => 1,
                'foetus' => 0,
                'consang' => 0.0,
                'sire_id' => NULL,
                'dam_id' => NULL,
                'taille_additive' => 154,
            ),
            51 => 
            array (
                'id' => 55,
                'created_at' => '2020-05-22 20:52:38',
                'updated_at' => '2020-05-22 20:52:56',
                'nom' => 'Fohifi',
                'affixe_id' => 1,
                'couleur' => NULL,
                'taille_cm' => 102,
                'race_id' => 2,
                'sexe' => 'jeune mâle',
                'date_achat' => NULL,
                'date_naissance' => '1971-04-01',
                'a_vendre' => 0,
                'prix' => NULL,
                'elevage_id' => 1,
                'fondateur' => 0,
                'foetus' => 0,
                'consang' => 0.0,
                'sire_id' => 33,
                'dam_id' => 2,
                'taille_additive' => 103,
            ),
            52 => 
            array (
                'id' => 56,
                'created_at' => '2020-05-22 20:52:38',
                'updated_at' => '2020-05-22 20:52:56',
                'nom' => 'Fukuty',
                'affixe_id' => 11,
                'couleur' => NULL,
                'taille_cm' => 117,
                'race_id' => 4,
                'sexe' => 'jeune femelle',
                'date_achat' => NULL,
                'date_naissance' => '1971-04-01',
                'a_vendre' => 0,
                'prix' => NULL,
                'elevage_id' => 4,
                'fondateur' => 0,
                'foetus' => 0,
                'consang' => 0.0,
                'sire_id' => 11,
                'dam_id' => 10,
                'taille_additive' => 117,
            ),
            53 => 
            array (
                'id' => 57,
                'created_at' => '2020-05-22 20:52:39',
                'updated_at' => '2020-05-22 20:52:56',
                'nom' => 'Falexe',
                'affixe_id' => 7,
                'couleur' => NULL,
                'taille_cm' => 122,
                'race_id' => 5,
                'sexe' => 'jeune mâle',
                'date_achat' => NULL,
                'date_naissance' => '1971-04-01',
                'a_vendre' => 0,
                'prix' => NULL,
                'elevage_id' => 4,
                'fondateur' => 0,
                'foetus' => 0,
                'consang' => 0.0,
                'sire_id' => 48,
                'dam_id' => 13,
                'taille_additive' => 133,
            ),
            54 => 
            array (
                'id' => 58,
                'created_at' => '2020-05-22 20:52:39',
                'updated_at' => '2020-05-22 20:52:56',
                'nom' => 'Funuyo',
                'affixe_id' => 6,
                'couleur' => NULL,
                'taille_cm' => 124,
                'race_id' => 5,
                'sexe' => 'jeune mâle',
                'date_achat' => NULL,
                'date_naissance' => '1971-04-01',
                'a_vendre' => 0,
                'prix' => NULL,
                'elevage_id' => 4,
                'fondateur' => 0,
                'foetus' => 0,
                'consang' => 0.0,
                'sire_id' => 48,
                'dam_id' => 51,
                'taille_additive' => 125,
            ),
            55 => 
            array (
                'id' => 59,
                'created_at' => '2020-05-22 20:52:41',
                'updated_at' => '2020-05-22 20:55:08',
                'nom' => 'Fijiya',
                'affixe_id' => NULL,
                'couleur' => NULL,
                'taille_cm' => 53,
                'race_id' => 3,
                'sexe' => 'jeune femelle',
                'date_achat' => NULL,
                'date_naissance' => '1971-06-01',
                'a_vendre' => 0,
                'prix' => NULL,
                'elevage_id' => 5,
                'fondateur' => 0,
                'foetus' => 0,
                'consang' => 0.0,
                'sire_id' => 39,
                'dam_id' => 38,
                'taille_additive' => 92,
            ),
            56 => 
            array (
                'id' => 60,
                'created_at' => '2020-05-22 20:52:43',
                'updated_at' => '2020-05-22 20:55:11',
                'nom' => 'Foropu',
                'affixe_id' => 16,
                'couleur' => NULL,
                'taille_cm' => 92,
                'race_id' => 2,
                'sexe' => 'jeune mâle',
                'date_achat' => NULL,
                'date_naissance' => '1971-07-01',
                'a_vendre' => 0,
                'prix' => NULL,
                'elevage_id' => 1,
                'fondateur' => 0,
                'foetus' => 0,
                'consang' => 0.0,
                'sire_id' => 22,
                'dam_id' => 21,
                'taille_additive' => 102,
            ),
            57 => 
            array (
                'id' => 61,
                'created_at' => '2020-05-22 20:52:43',
                'updated_at' => '2020-05-22 20:55:11',
                'nom' => 'Fojuhu',
                'affixe_id' => 13,
                'couleur' => NULL,
                'taille_cm' => 94,
                'race_id' => 2,
                'sexe' => 'jeune femelle',
                'date_achat' => NULL,
                'date_naissance' => '1971-07-01',
                'a_vendre' => 0,
                'prix' => NULL,
                'elevage_id' => 1,
                'fondateur' => 0,
                'foetus' => 0,
                'consang' => 0.0,
                'sire_id' => 22,
                'dam_id' => 24,
                'taille_additive' => 106,
            ),
            58 => 
            array (
                'id' => 62,
                'created_at' => '2020-05-22 20:52:44',
                'updated_at' => '2020-05-22 20:52:44',
                'nom' => 'Fugove',
                'affixe_id' => 20,
                'couleur' => NULL,
                'taille_cm' => 105,
                'race_id' => 2,
                'sexe' => 'jeune mâle',
                'date_achat' => NULL,
                'date_naissance' => '1971-08-01',
                'a_vendre' => 0,
                'prix' => NULL,
                'elevage_id' => 1,
                'fondateur' => 0,
                'foetus' => 1,
                'consang' => 0.0,
                'sire_id' => 25,
                'dam_id' => 34,
                'taille_additive' => 106,
            ),
            59 => 
            array (
                'id' => 63,
                'created_at' => '2020-05-22 20:52:45',
                'updated_at' => '2020-05-22 20:52:45',
                'nom' => 'Fadena',
                'affixe_id' => 5,
                'couleur' => NULL,
                'taille_cm' => 130,
                'race_id' => 5,
                'sexe' => 'jeune femelle',
                'date_achat' => NULL,
                'date_naissance' => '1971-08-01',
                'a_vendre' => 0,
                'prix' => NULL,
                'elevage_id' => 4,
                'fondateur' => 0,
                'foetus' => 1,
                'consang' => 0.0,
                'sire_id' => 48,
                'dam_id' => 7,
                'taille_additive' => 129,
            ),
            60 => 
            array (
                'id' => 64,
                'created_at' => '2020-05-22 20:52:45',
                'updated_at' => '2020-05-22 20:52:45',
                'nom' => 'Fybulo',
                'affixe_id' => 29,
                'couleur' => NULL,
                'taille_cm' => 125,
                'race_id' => 5,
                'sexe' => 'jeune femelle',
                'date_achat' => NULL,
                'date_naissance' => '1971-08-01',
                'a_vendre' => 0,
                'prix' => NULL,
                'elevage_id' => 4,
                'fondateur' => 0,
                'foetus' => 1,
                'consang' => 0.0,
                'sire_id' => 43,
                'dam_id' => 47,
                'taille_additive' => 123,
            ),
            61 => 
            array (
                'id' => 65,
                'created_at' => '2020-05-22 20:52:53',
                'updated_at' => '2020-05-22 20:52:53',
                'nom' => 'Gohegi',
                'affixe_id' => 37,
                'couleur' => NULL,
                'taille_cm' => 133,
                'race_id' => 5,
                'sexe' => 'jeune femelle',
                'date_achat' => NULL,
                'date_naissance' => '1972-02-01',
                'a_vendre' => 0,
                'prix' => NULL,
                'elevage_id' => 4,
                'fondateur' => 0,
                'foetus' => 1,
                'consang' => 0.0,
                'sire_id' => 48,
                'dam_id' => 49,
                'taille_additive' => 135,
            ),
            62 => 
            array (
                'id' => 66,
                'created_at' => '2020-05-22 20:52:56',
                'updated_at' => '2020-05-22 20:52:56',
                'nom' => 'Gumive',
                'affixe_id' => 1,
                'couleur' => NULL,
                'taille_cm' => 101,
                'race_id' => 2,
                'sexe' => 'jeune mâle',
                'date_achat' => NULL,
                'date_naissance' => '1972-03-01',
                'a_vendre' => 0,
                'prix' => NULL,
                'elevage_id' => 1,
                'fondateur' => 0,
                'foetus' => 1,
                'consang' => 0.0,
                'sire_id' => 33,
                'dam_id' => 2,
                'taille_additive' => 103,
            ),
            63 => 
            array (
                'id' => 67,
                'created_at' => '2020-05-22 20:52:56',
                'updated_at' => '2020-05-22 20:52:56',
                'nom' => 'Guhewe',
                'affixe_id' => 18,
                'couleur' => NULL,
                'taille_cm' => 84,
                'race_id' => 2,
                'sexe' => 'jeune mâle',
                'date_achat' => NULL,
                'date_naissance' => '1972-03-01',
                'a_vendre' => 0,
                'prix' => NULL,
                'elevage_id' => 1,
                'fondateur' => 0,
                'foetus' => 1,
                'consang' => 0.0,
                'sire_id' => 32,
                'dam_id' => 29,
                'taille_additive' => 102,
            ),
            64 => 
            array (
                'id' => 68,
                'created_at' => '2020-05-22 20:52:56',
                'updated_at' => '2020-05-22 20:52:56',
                'nom' => 'Gekasi',
                'affixe_id' => NULL,
                'couleur' => NULL,
                'taille_cm' => 66,
                'race_id' => 3,
                'sexe' => 'jeune femelle',
                'date_achat' => NULL,
                'date_naissance' => '1972-03-01',
                'a_vendre' => 0,
                'prix' => NULL,
                'elevage_id' => 5,
                'fondateur' => 0,
                'foetus' => 1,
                'consang' => 0.0,
                'sire_id' => 8,
                'dam_id' => 37,
                'taille_additive' => 100,
            ),
            65 => 
            array (
                'id' => 69,
                'created_at' => '2020-05-22 20:52:57',
                'updated_at' => '2020-05-22 20:52:57',
                'nom' => 'Gynyty',
                'affixe_id' => 7,
                'couleur' => NULL,
                'taille_cm' => 115,
                'race_id' => 4,
                'sexe' => 'jeune mâle',
                'date_achat' => NULL,
                'date_naissance' => '1972-04-01',
                'a_vendre' => 0,
                'prix' => NULL,
                'elevage_id' => 4,
                'fondateur' => 0,
                'foetus' => 1,
                'consang' => 0.0,
                'sire_id' => 9,
                'dam_id' => 13,
                'taille_additive' => 124,
            ),
            66 => 
            array (
                'id' => 70,
                'created_at' => '2020-05-22 20:55:08',
                'updated_at' => '2020-05-22 20:55:08',
                'nom' => 'Gikagi',
                'affixe_id' => 28,
                'couleur' => NULL,
                'taille_cm' => 120,
                'race_id' => 5,
                'sexe' => 'jeune mâle',
                'date_achat' => NULL,
                'date_naissance' => '1972-05-01',
                'a_vendre' => 0,
                'prix' => NULL,
                'elevage_id' => 4,
                'fondateur' => 0,
                'foetus' => 1,
                'consang' => 0.0,
                'sire_id' => 9,
                'dam_id' => 41,
                'taille_additive' => 122,
            ),
            67 => 
            array (
                'id' => 71,
                'created_at' => '2020-05-22 20:55:11',
                'updated_at' => '2020-05-22 20:55:11',
                'nom' => 'Galoga',
                'affixe_id' => 22,
                'couleur' => NULL,
                'taille_cm' => 99,
                'race_id' => 2,
                'sexe' => 'jeune mâle',
                'date_achat' => NULL,
                'date_naissance' => '1972-06-01',
                'a_vendre' => 0,
                'prix' => NULL,
                'elevage_id' => 1,
                'fondateur' => 0,
                'foetus' => 1,
                'consang' => 0.0,
                'sire_id' => 22,
                'dam_id' => 36,
                'taille_additive' => 102,
            ),
            68 => 
            array (
                'id' => 72,
                'created_at' => '2020-05-22 20:55:12',
                'updated_at' => '2020-05-22 20:55:12',
                'nom' => 'Gemoso',
                'affixe_id' => 11,
                'couleur' => NULL,
                'taille_cm' => 126,
                'race_id' => 5,
                'sexe' => 'jeune femelle',
                'date_achat' => NULL,
                'date_naissance' => '1972-06-01',
                'a_vendre' => 0,
                'prix' => NULL,
                'elevage_id' => 4,
                'fondateur' => 0,
                'foetus' => 1,
                'consang' => 0.0,
                'sire_id' => 43,
                'dam_id' => 10,
                'taille_additive' => 124,
            ),
            69 => 
            array (
                'id' => 73,
                'created_at' => '2020-05-22 20:55:12',
                'updated_at' => '2020-05-22 20:55:12',
                'nom' => 'Gijily',
                'affixe_id' => 6,
                'couleur' => NULL,
                'taille_cm' => 116,
                'race_id' => 4,
                'sexe' => 'jeune mâle',
                'date_achat' => NULL,
                'date_naissance' => '1972-06-01',
                'a_vendre' => 0,
                'prix' => NULL,
                'elevage_id' => 4,
                'fondateur' => 0,
                'foetus' => 1,
                'consang' => 0.0,
                'sire_id' => 9,
                'dam_id' => 51,
                'taille_additive' => 116,
            ),
            70 => 
            array (
                'id' => 74,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'Ramses',
                'affixe_id' => NULL,
                'couleur' => NULL,
                'taille_cm' => 156,
                'race_id' => 8,
                'sexe' => 'mâle',
                'date_achat' => NULL,
                'date_naissance' => '1968-05-22',
                'a_vendre' => 0,
                'prix' => NULL,
                'elevage_id' => 7,
                'fondateur' => 1,
                'foetus' => 0,
                'consang' => 0.0,
                'sire_id' => NULL,
                'dam_id' => NULL,
                'taille_additive' => 156,
            ),
            71 => 
            array (
                'id' => 75,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'Nefertari',
                'affixe_id' => NULL,
                'couleur' => NULL,
                'taille_cm' => 153,
                'race_id' => 8,
                'sexe' => 'femelle',
                'date_achat' => NULL,
                'date_naissance' => '1968-05-22',
                'a_vendre' => 0,
                'prix' => NULL,
                'elevage_id' => 7,
                'fondateur' => 1,
                'foetus' => 0,
                'consang' => 0.0,
                'sire_id' => NULL,
                'dam_id' => NULL,
                'taille_additive' => 153,
            ),
            72 => 
            array (
                'id' => 76,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'Nefertiti',
                'affixe_id' => NULL,
                'couleur' => NULL,
                'taille_cm' => 148,
                'race_id' => 8,
                'sexe' => 'jeune femelle',
                'date_achat' => NULL,
                'date_naissance' => '1969-06-23',
                'a_vendre' => 0,
                'prix' => NULL,
                'elevage_id' => 7,
                'fondateur' => 1,
                'foetus' => 0,
                'consang' => 0.0,
                'sire_id' => NULL,
                'dam_id' => NULL,
                'taille_additive' => 149,
            ),
        ));
        
        
    }
}