<?php

use Illuminate\Database\Seeder;

class AnimauxTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('animaux')->delete();
        
        \DB::table('animaux')->insert(array (
            0 => 
            array (
                'id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'Mignonne',
                'affixe' => 'of Marshwood',
                'affixe_pre' => 0,
                'couleur' => NULL,
                'taille_cm' => 99,
                'race' => 'Shetland',
                'sexe' => 'femelle',
                'date_achat' => '1970-01-11',
                'date_naissance' => '1966-05-13',
                'a_vendre' => 0,
                'prix' => NULL,
                'elevage_id' => 1,
                'fondateur' => 1,
                'foetus' => 0,
                'sire_id' => NULL,
                'dam_id' => NULL,
            ),
            1 => 
            array (
                'id' => 3,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'Popeye',
                'affixe' => 'Fairy',
                'affixe_pre' => 1,
                'couleur' => NULL,
                'taille_cm' => 102,
                'race' => 'Shetland',
                'sexe' => 'mâle',
                'date_achat' => '1970-02-11',
                'date_naissance' => '1964-04-15',
                'a_vendre' => 0,
                'prix' => NULL,
                'elevage_id' => 1,
                'fondateur' => 1,
                'foetus' => 0,
                'sire_id' => NULL,
                'dam_id' => NULL,
            ),
            2 => 
            array (
                'id' => 4,
                'created_at' => NULL,
                'updated_at' => '2020-02-16 17:13:00',
                'nom' => ' Diana',
                'affixe' => 'Ceulan',
                'affixe_pre' => 1,
                'couleur' => NULL,
                'taille_cm' => 114,
                'race' => 'Welsh A',
                'sexe' => 'femelle',
                'date_achat' => NULL,
                'date_naissance' => '1965-04-12',
                'a_vendre' => 0,
                'prix' => 1500,
                'elevage_id' => 4,
                'fondateur' => 1,
                'foetus' => 0,
                'sire_id' => NULL,
                'dam_id' => NULL,
            ),
            3 => 
            array (
                'id' => 5,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'Molly',
                'affixe' => 'Fairy',
                'affixe_pre' => 1,
                'couleur' => NULL,
                'taille_cm' => 106,
                'race' => 'Shetland',
                'sexe' => 'femelle',
                'date_achat' => '1970-02-16',
                'date_naissance' => '1963-06-16',
                'a_vendre' => 0,
                'prix' => NULL,
                'elevage_id' => 1,
                'fondateur' => 1,
                'foetus' => 0,
                'sire_id' => NULL,
                'dam_id' => NULL,
            ),
            4 => 
            array (
                'id' => 6,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => ' Myrrdhin',
                'affixe' => 'Coed Coch',
                'affixe_pre' => 1,
                'couleur' => NULL,
                'taille_cm' => 117,
                'race' => 'Welsh A',
                'sexe' => 'mâle',
                'date_achat' => NULL,
                'date_naissance' => '1965-02-13',
                'a_vendre' => 0,
                'prix' => NULL,
                'elevage_id' => 4,
                'fondateur' => 1,
                'foetus' => 0,
                'sire_id' => NULL,
                'dam_id' => NULL,
            ),
            5 => 
            array (
                'id' => 7,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'Keridwen',
                'affixe' => 'Coed Coch ',
                'affixe_pre' => 1,
                'couleur' => NULL,
                'taille_cm' => 111,
                'race' => 'Welsh A',
                'sexe' => 'femelle',
                'date_achat' => NULL,
                'date_naissance' => '1966-05-18',
                'a_vendre' => 0,
                'prix' => NULL,
                'elevage_id' => 4,
                'fondateur' => 1,
                'foetus' => 0,
                'sire_id' => NULL,
                'dam_id' => NULL,
            ),
            6 => 
            array (
                'id' => 8,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'Django',
                'affixe' => NULL,
                'affixe_pre' => 0,
                'couleur' => NULL,
                'taille_cm' => 81,
                'race' => 'Miniature',
                'sexe' => 'mâle',
                'date_achat' => NULL,
                'date_naissance' => '1967-05-23',
                'a_vendre' => 0,
                'prix' => NULL,
                'elevage_id' => 1,
                'fondateur' => 1,
                'foetus' => 0,
                'sire_id' => NULL,
                'dam_id' => NULL,
            ),
            7 => 
            array (
                'id' => 9,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'Owen',
                'affixe' => 'Ceulan ',
                'affixe_pre' => 1,
                'couleur' => NULL,
                'taille_cm' => 118,
                'race' => 'Welsh A',
                'sexe' => 'mâle',
                'date_achat' => NULL,
                'date_naissance' => '1964-03-21',
                'a_vendre' => 0,
                'prix' => NULL,
                'elevage_id' => 4,
                'fondateur' => 1,
                'foetus' => 0,
                'sire_id' => NULL,
                'dam_id' => NULL,
            ),
            8 => 
            array (
                'id' => 10,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => ' Lizzy',
                'affixe' => 'Bowdler',
                'affixe_pre' => 1,
                'couleur' => NULL,
                'taille_cm' => 113,
                'race' => 'Welsh A',
                'sexe' => 'femelle',
                'date_achat' => NULL,
                'date_naissance' => '1966-04-21',
                'a_vendre' => 0,
                'prix' => NULL,
                'elevage_id' => 4,
                'fondateur' => 1,
                'foetus' => 0,
                'sire_id' => NULL,
                'dam_id' => NULL,
            ),
            9 => 
            array (
                'id' => 11,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => ' Hero',
                'affixe' => 'Mathrafal',
                'affixe_pre' => 1,
                'couleur' => NULL,
                'taille_cm' => 120,
                'race' => 'Welsh A',
                'sexe' => 'mâle',
                'date_achat' => NULL,
                'date_naissance' => '1966-05-31',
                'a_vendre' => 0,
                'prix' => NULL,
                'elevage_id' => 4,
                'fondateur' => 1,
                'foetus' => 0,
                'sire_id' => NULL,
                'dam_id' => NULL,
            ),
            10 => 
            array (
                'id' => 12,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => ' Comet',
                'affixe' => 'Twyford',
                'affixe_pre' => 1,
                'couleur' => NULL,
                'taille_cm' => 119,
                'race' => 'Welsh A',
                'sexe' => 'mâle',
                'date_achat' => NULL,
                'date_naissance' => '1965-04-18',
                'a_vendre' => 0,
                'prix' => NULL,
                'elevage_id' => 4,
                'fondateur' => 1,
                'foetus' => 0,
                'sire_id' => NULL,
                'dam_id' => NULL,
            ),
            11 => 
            array (
                'id' => 13,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'Daffodil',
                'affixe' => 'Anglesey ',
                'affixe_pre' => 1,
                'couleur' => NULL,
                'taille_cm' => 109,
                'race' => 'Welsh A',
                'sexe' => 'femelle',
                'date_achat' => NULL,
                'date_naissance' => '1966-03-24',
                'a_vendre' => 0,
                'prix' => NULL,
                'elevage_id' => 4,
                'fondateur' => 1,
                'foetus' => 0,
                'sire_id' => NULL,
                'dam_id' => NULL,
            ),
            12 => 
            array (
                'id' => 14,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => ' Davy',
                'affixe' => 'Downland',
                'affixe_pre' => 1,
                'couleur' => NULL,
                'taille_cm' => 112,
                'race' => 'Welsh A',
                'sexe' => 'mâle',
                'date_achat' => NULL,
                'date_naissance' => '1965-04-25',
                'a_vendre' => 0,
                'prix' => NULL,
                'elevage_id' => 4,
                'fondateur' => 1,
                'foetus' => 0,
                'sire_id' => NULL,
                'dam_id' => NULL,
            ),
            13 => 
            array (
                'id' => 17,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'Poppy',
                'affixe' => 'of Burland',
                'affixe_pre' => 0,
                'couleur' => NULL,
                'taille_cm' => 91,
                'race' => 'Shetland',
                'sexe' => 'femelle',
                'date_achat' => NULL,
                'date_naissance' => '1964-06-25',
                'a_vendre' => 0,
                'prix' => NULL,
                'elevage_id' => 1,
                'fondateur' => 1,
                'foetus' => 0,
                'sire_id' => NULL,
                'dam_id' => NULL,
            ),
            14 => 
            array (
                'id' => 18,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'Millie',
                'affixe' => 'of Hools',
                'affixe_pre' => 0,
                'couleur' => NULL,
                'taille_cm' => 99,
                'race' => 'Shetland',
                'sexe' => 'femelle',
                'date_achat' => NULL,
                'date_naissance' => '1964-03-22',
                'a_vendre' => 0,
                'prix' => NULL,
                'elevage_id' => 1,
                'fondateur' => 1,
                'foetus' => 0,
                'sire_id' => NULL,
                'dam_id' => NULL,
            ),
            15 => 
            array (
                'id' => 19,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'Calliope',
                'affixe' => 'Mathrafal',
                'affixe_pre' => 1,
                'couleur' => NULL,
                'taille_cm' => 112,
                'race' => 'Welsh A',
                'sexe' => 'femelle',
                'date_achat' => NULL,
                'date_naissance' => '1965-05-25',
                'a_vendre' => 0,
                'prix' => NULL,
                'elevage_id' => 4,
                'fondateur' => 1,
                'foetus' => 0,
                'sire_id' => NULL,
                'dam_id' => NULL,
            ),
            16 => 
            array (
                'id' => 20,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'Brutus',
                'affixe' => 'Fenwick',
                'affixe_pre' => 1,
                'couleur' => NULL,
                'taille_cm' => 103,
                'race' => 'Shetland',
                'sexe' => 'mâle',
                'date_achat' => NULL,
                'date_naissance' => '1965-03-29',
                'a_vendre' => 0,
                'prix' => NULL,
                'elevage_id' => 1,
                'fondateur' => 1,
                'foetus' => 0,
                'sire_id' => NULL,
                'dam_id' => NULL,
            ),
            17 => 
            array (
                'id' => 21,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'Primrose',
                'affixe' => 'Halstock',
                'affixe_pre' => 1,
                'couleur' => NULL,
                'taille_cm' => 95,
                'race' => 'Shetland',
                'sexe' => 'femelle',
                'date_achat' => NULL,
                'date_naissance' => '1967-03-25',
                'a_vendre' => 0,
                'prix' => NULL,
                'elevage_id' => 1,
                'fondateur' => 1,
                'foetus' => 0,
                'sire_id' => NULL,
                'dam_id' => NULL,
            ),
            18 => 
            array (
                'id' => 22,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'Andy',
                'affixe' => 'Halstock',
                'affixe_pre' => 1,
                'couleur' => NULL,
                'taille_cm' => 98,
                'race' => 'Shetland',
                'sexe' => 'mâle',
                'date_achat' => NULL,
                'date_naissance' => '1966-03-25',
                'a_vendre' => 0,
                'prix' => NULL,
                'elevage_id' => 1,
                'fondateur' => 1,
                'foetus' => 0,
                'sire_id' => NULL,
                'dam_id' => NULL,
            ),
            19 => 
            array (
                'id' => 23,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'Lily',
                'affixe' => 'Fenwick',
                'affixe_pre' => 1,
                'couleur' => NULL,
                'taille_cm' => 89,
                'race' => 'Shetland',
                'sexe' => 'femelle',
                'date_achat' => NULL,
                'date_naissance' => '1966-03-28',
                'a_vendre' => 0,
                'prix' => NULL,
                'elevage_id' => 1,
                'fondateur' => 1,
                'foetus' => 0,
                'sire_id' => NULL,
                'dam_id' => NULL,
            ),
            20 => 
            array (
                'id' => 24,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'Beryl',
                'affixe' => 'Gue',
                'affixe_pre' => 1,
                'couleur' => NULL,
                'taille_cm' => 94,
                'race' => 'Shetland',
                'sexe' => 'femelle',
                'date_achat' => NULL,
                'date_naissance' => '1964-05-28',
                'a_vendre' => 0,
                'prix' => NULL,
                'elevage_id' => 1,
                'fondateur' => 1,
                'foetus' => 0,
                'sire_id' => NULL,
                'dam_id' => NULL,
            ),
            21 => 
            array (
                'id' => 25,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'Mistigri',
                'affixe' => 'of Burland',
                'affixe_pre' => 0,
                'couleur' => NULL,
                'taille_cm' => 97,
                'race' => 'Shetland',
                'sexe' => 'mâle',
                'date_achat' => NULL,
                'date_naissance' => '1966-04-28',
                'a_vendre' => 0,
                'prix' => NULL,
                'elevage_id' => 1,
                'fondateur' => 1,
                'foetus' => 0,
                'sire_id' => NULL,
                'dam_id' => NULL,
            ),
            22 => 
            array (
                'id' => 26,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'Bobine',
                'affixe' => 'de Bois Guilbert',
                'affixe_pre' => 0,
                'couleur' => NULL,
                'taille_cm' => 101,
                'race' => 'Shetland',
                'sexe' => 'femelle',
                'date_achat' => NULL,
                'date_naissance' => '1967-06-28',
                'a_vendre' => 0,
                'prix' => NULL,
                'elevage_id' => 1,
                'fondateur' => 1,
                'foetus' => 0,
                'sire_id' => NULL,
                'dam_id' => NULL,
            ),
            23 => 
            array (
                'id' => 27,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'Rose',
                'affixe' => 'of Houlland',
                'affixe_pre' => 0,
                'couleur' => NULL,
                'taille_cm' => 93,
                'race' => 'Shetland',
                'sexe' => 'femelle',
                'date_achat' => NULL,
                'date_naissance' => '1964-06-28',
                'a_vendre' => 0,
                'prix' => NULL,
                'elevage_id' => 1,
                'fondateur' => 1,
                'foetus' => 0,
                'sire_id' => NULL,
                'dam_id' => NULL,
            ),
            24 => 
            array (
                'id' => 28,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'Viking',
                'affixe' => 'of Annnandale',
                'affixe_pre' => 0,
                'couleur' => NULL,
                'taille_cm' => 89,
                'race' => 'Shetland',
                'sexe' => 'mâle',
                'date_achat' => NULL,
                'date_naissance' => '1964-03-28',
                'a_vendre' => 0,
                'prix' => NULL,
                'elevage_id' => 1,
                'fondateur' => 1,
                'foetus' => 0,
                'sire_id' => NULL,
                'dam_id' => NULL,
            ),
            25 => 
            array (
                'id' => 29,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'Ruby',
                'affixe' => 'of Annandale',
                'affixe_pre' => 0,
                'couleur' => NULL,
                'taille_cm' => 96,
                'race' => 'Shetland',
                'sexe' => 'femelle',
                'date_achat' => NULL,
                'date_naissance' => '1965-03-28',
                'a_vendre' => 0,
                'prix' => NULL,
                'elevage_id' => 1,
                'fondateur' => 1,
                'foetus' => 0,
                'sire_id' => NULL,
                'dam_id' => NULL,
            ),
            26 => 
            array (
                'id' => 30,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'Odin',
                'affixe' => 'Gue',
                'affixe_pre' => 1,
                'couleur' => NULL,
                'taille_cm' => 98,
                'race' => 'Shetland',
                'sexe' => 'mâle',
                'date_achat' => NULL,
                'date_naissance' => '1969-04-29',
                'a_vendre' => 0,
                'prix' => NULL,
                'elevage_id' => 1,
                'fondateur' => 1,
                'foetus' => 0,
                'sire_id' => NULL,
                'dam_id' => NULL,
            ),
            27 => 
            array (
                'id' => 31,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'Salsa',
                'affixe' => 'of Houlland',
                'affixe_pre' => 0,
                'couleur' => NULL,
                'taille_cm' => 103,
                'race' => 'Shetland',
                'sexe' => 'femelle',
                'date_achat' => NULL,
                'date_naissance' => '1966-03-29',
                'a_vendre' => 0,
                'prix' => NULL,
                'elevage_id' => 1,
                'fondateur' => 1,
                'foetus' => 0,
                'sire_id' => NULL,
                'dam_id' => NULL,
            ),
            28 => 
            array (
                'id' => 32,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'Captain',
                'affixe' => 'of Marshwood',
                'affixe_pre' => 0,
                'couleur' => NULL,
                'taille_cm' => NULL,
                'race' => 'Shetland',
                'sexe' => 'mâle',
                'date_achat' => NULL,
                'date_naissance' => '1966-05-29',
                'a_vendre' => 0,
                'prix' => NULL,
                'elevage_id' => 1,
                'fondateur' => 1,
                'foetus' => 0,
                'sire_id' => NULL,
                'dam_id' => NULL,
            ),
            29 => 
            array (
                'id' => 33,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'Piggy',
                'affixe' => 'Robin\'s Brae',
                'affixe_pre' => 1,
                'couleur' => NULL,
                'taille_cm' => 107,
                'race' => 'Shetland',
                'sexe' => 'mâle',
                'date_achat' => NULL,
                'date_naissance' => '1965-04-29',
                'a_vendre' => 0,
                'prix' => NULL,
                'elevage_id' => 1,
                'fondateur' => 1,
                'foetus' => 0,
                'sire_id' => NULL,
                'dam_id' => NULL,
            ),
            30 => 
            array (
                'id' => 34,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'Sonia',
                'affixe' => 'Kirkbride',
                'affixe_pre' => 1,
                'couleur' => NULL,
                'taille_cm' => 105,
                'race' => 'Shetland',
                'sexe' => 'femelle',
                'date_achat' => NULL,
                'date_naissance' => '1965-03-29',
                'a_vendre' => 0,
                'prix' => NULL,
                'elevage_id' => 1,
                'fondateur' => 1,
                'foetus' => 0,
                'sire_id' => NULL,
                'dam_id' => NULL,
            ),
            31 => 
            array (
                'id' => 35,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'Alezane',
                'affixe' => 'of Shergold',
                'affixe_pre' => 0,
                'couleur' => NULL,
                'taille_cm' => 104,
                'race' => 'Shetland',
                'sexe' => 'femelle',
                'date_achat' => NULL,
                'date_naissance' => '1964-06-29',
                'a_vendre' => 0,
                'prix' => NULL,
                'elevage_id' => 1,
                'fondateur' => 1,
                'foetus' => 0,
                'sire_id' => NULL,
                'dam_id' => NULL,
            ),
            32 => 
            array (
                'id' => 36,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'Sally',
                'affixe' => 'of Maitland',
                'affixe_pre' => 0,
                'couleur' => NULL,
                'taille_cm' => 103,
                'race' => 'Shetland',
                'sexe' => 'femelle',
                'date_achat' => NULL,
                'date_naissance' => '1965-03-14',
                'a_vendre' => 0,
                'prix' => NULL,
                'elevage_id' => 1,
                'fondateur' => 1,
                'foetus' => 0,
                'sire_id' => NULL,
                'dam_id' => NULL,
            ),
            33 => 
            array (
                'id' => 37,
                'created_at' => '2020-03-29 21:33:39',
                'updated_at' => '2020-03-29 21:35:56',
                'nom' => 'Fantine',
                'affixe' => 'of Marshwood',
                'affixe_pre' => 0,
                'couleur' => 'alezan dun',
                'taille_cm' => 99,
                'race' => 'Shetland',
                'sexe' => 'jeune femelle',
                'date_achat' => '1971-10-01',
                'date_naissance' => '1971-03-01',
                'a_vendre' => 0,
                'prix' => 500,
                'elevage_id' => 5,
                'fondateur' => 0,
                'foetus' => 0,
                'sire_id' => 22,
                'dam_id' => 2,
            ),
            34 => 
            array (
                'id' => 38,
                'created_at' => '2020-03-29 21:33:39',
                'updated_at' => '2020-03-29 21:36:34',
                'nom' => 'Fiona',
                'affixe' => 'Ceulan',
                'affixe_pre' => 1,
                'couleur' => 'gris',
                'taille_cm' => 117,
                'race' => 'Welsh A',
                'sexe' => 'jeune femelle',
                'date_achat' => '1971-10-01',
                'date_naissance' => '1971-03-01',
                'a_vendre' => 0,
                'prix' => 500,
                'elevage_id' => 5,
                'fondateur' => 0,
                'foetus' => 0,
                'sire_id' => 12,
                'dam_id' => 4,
            ),
            35 => 
            array (
                'id' => 39,
                'created_at' => '2020-03-29 21:33:48',
                'updated_at' => '2020-03-29 21:38:23',
                'nom' => 'Flicka',
                'affixe' => 'Coed Coch ',
                'affixe_pre' => 1,
                'couleur' => 'alezan',
                'taille_cm' => 114,
                'race' => 'Welsh A',
                'sexe' => 'jeune femelle',
                'date_achat' => '1972-01-01',
                'date_naissance' => '1971-04-01',
                'a_vendre' => 0,
                'prix' => 500,
                'elevage_id' => 5,
                'fondateur' => 0,
                'foetus' => 0,
                'sire_id' => 6,
                'dam_id' => 7,
            ),
            36 => 
            array (
                'id' => 40,
                'created_at' => '2020-03-29 21:33:48',
                'updated_at' => '2020-03-29 21:38:54',
                'nom' => 'Fillette',
                'affixe' => 'Anglesey ',
                'affixe_pre' => 1,
                'couleur' => 'bai avec marques',
                'taille_cm' => 115,
                'race' => 'Welsh A',
                'sexe' => 'jeune femelle',
                'date_achat' => '1972-01-01',
                'date_naissance' => '1971-04-01',
                'a_vendre' => 0,
                'prix' => 500,
                'elevage_id' => 5,
                'fondateur' => 0,
                'foetus' => 0,
                'sire_id' => 11,
                'dam_id' => 13,
            ),
            37 => 
            array (
                'id' => 41,
                'created_at' => '2020-03-29 21:33:56',
                'updated_at' => '2020-03-29 21:39:46',
                'nom' => 'Finette',
                'affixe' => 'Fairy',
                'affixe_pre' => 1,
                'couleur' => 'alezan',
                'taille_cm' => 104,
                'race' => 'Shetland',
                'sexe' => 'jeune femelle',
                'date_achat' => '1972-01-01',
                'date_naissance' => '1971-06-01',
                'a_vendre' => 0,
                'prix' => 500,
                'elevage_id' => 5,
                'fondateur' => 0,
                'foetus' => 0,
                'sire_id' => 3,
                'dam_id' => 5,
            ),
            38 => 
            array (
                'id' => 42,
                'created_at' => '2020-03-29 21:34:24',
                'updated_at' => '2020-03-29 21:36:57',
                'nom' => NULL,
                'affixe' => 'Bowdler',
                'affixe_pre' => 1,
                'couleur' => NULL,
                'taille_cm' => 116,
                'race' => 'Welsh A',
                'sexe' => 'jeune mâle',
                'date_achat' => NULL,
                'date_naissance' => '1971-12-01',
                'a_vendre' => 0,
                'prix' => NULL,
                'elevage_id' => 4,
                'fondateur' => 0,
                'foetus' => 0,
                'sire_id' => 9,
                'dam_id' => 10,
            ),
            39 => 
            array (
                'id' => 43,
                'created_at' => '2020-03-29 21:34:30',
                'updated_at' => '2020-03-29 21:34:30',
                'nom' => NULL,
                'affixe' => 'Ceulan',
                'affixe_pre' => 1,
                'couleur' => NULL,
                'taille_cm' => 113,
                'race' => 'Welsh A',
                'sexe' => 'jeune femelle',
                'date_achat' => NULL,
                'date_naissance' => '1972-02-01',
                'a_vendre' => 0,
                'prix' => NULL,
                'elevage_id' => 4,
                'fondateur' => 0,
                'foetus' => 1,
                'sire_id' => 14,
                'dam_id' => 4,
            ),
            40 => 
            array (
                'id' => 44,
                'created_at' => '2020-03-29 21:34:34',
                'updated_at' => '2020-03-29 21:34:34',
                'nom' => NULL,
                'affixe' => 'of Marshwood',
                'affixe_pre' => 0,
                'couleur' => NULL,
                'taille_cm' => 94,
                'race' => 'Shetland',
                'sexe' => 'jeune mâle',
                'date_achat' => NULL,
                'date_naissance' => '1972-03-01',
                'a_vendre' => 0,
                'prix' => NULL,
                'elevage_id' => 1,
                'fondateur' => 0,
                'foetus' => 1,
                'sire_id' => 28,
                'dam_id' => 2,
            ),
            41 => 
            array (
                'id' => 45,
                'created_at' => '2020-03-29 21:34:34',
                'updated_at' => '2020-03-29 21:34:34',
                'nom' => NULL,
                'affixe' => 'Anglesey ',
                'affixe_pre' => 1,
                'couleur' => NULL,
                'taille_cm' => 115,
                'race' => 'Welsh A',
                'sexe' => 'jeune mâle',
                'date_achat' => NULL,
                'date_naissance' => '1972-03-01',
                'a_vendre' => 0,
                'prix' => NULL,
                'elevage_id' => 4,
                'fondateur' => 0,
                'foetus' => 1,
                'sire_id' => 11,
                'dam_id' => 13,
            ),
            42 => 
            array (
                'id' => 46,
                'created_at' => '2020-03-29 21:34:45',
                'updated_at' => '2020-03-29 21:34:45',
                'nom' => NULL,
                'affixe' => 'Coed Coch ',
                'affixe_pre' => 1,
                'couleur' => NULL,
                'taille_cm' => 115,
                'race' => 'Welsh A',
                'sexe' => 'jeune femelle',
                'date_achat' => NULL,
                'date_naissance' => '1972-06-01',
                'a_vendre' => 0,
                'prix' => NULL,
                'elevage_id' => 4,
                'fondateur' => 0,
                'foetus' => 1,
                'sire_id' => 9,
                'dam_id' => 7,
            ),
        ));
        
        
    }
}