<?php

use Illuminate\Database\Seeder;

class AnimauxTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('animaux')->delete();
        
        \DB::table('animaux')->insert(array (
            0 => 
            array (
                'id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'Mignonne',
                'affixe' => NULL,
                'affixe_pre' => 0,
                'couleur' => NULL,
                'taille_cm' => 99,
                'race' => 'Shetland',
                'sexe' => 'femelle',
                'date_achat' => '1970-01-11',
                'date_naissance' => '1966-05-13',
                'a_vendre' => 0,
                'prix' => NULL,
                'elevage_id' => 1,
                'fondateur' => 1,
                'foetus' => 0,
                'sire_id' => NULL,
                'dam_id' => NULL,
            ),
            1 => 
            array (
                'id' => 3,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'Popeye',
                'affixe' => NULL,
                'affixe_pre' => 0,
                'couleur' => NULL,
                'taille_cm' => 102,
                'race' => 'Shetland',
                'sexe' => 'mâle',
                'date_achat' => '1970-02-11',
                'date_naissance' => '1964-04-15',
                'a_vendre' => 0,
                'prix' => NULL,
                'elevage_id' => 1,
                'fondateur' => 1,
                'foetus' => 0,
                'sire_id' => NULL,
                'dam_id' => NULL,
            ),
            2 => 
            array (
                'id' => 4,
                'created_at' => NULL,
                'updated_at' => '2020-02-16 17:13:00',
                'nom' => ' Diana',
                'affixe' => 'Ceulan',
                'affixe_pre' => 1,
                'couleur' => NULL,
                'taille_cm' => 114,
                'race' => 'Welsh A',
                'sexe' => 'femelle',
                'date_achat' => NULL,
                'date_naissance' => '1965-04-12',
                'a_vendre' => 0,
                'prix' => 1500,
                'elevage_id' => 4,
                'fondateur' => 1,
                'foetus' => 0,
                'sire_id' => NULL,
                'dam_id' => NULL,
            ),
            3 => 
            array (
                'id' => 5,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'Molly',
                'affixe' => NULL,
                'affixe_pre' => 0,
                'couleur' => NULL,
                'taille_cm' => 106,
                'race' => 'Shetland',
                'sexe' => 'femelle',
                'date_achat' => '1970-02-16',
                'date_naissance' => '1963-06-16',
                'a_vendre' => 0,
                'prix' => NULL,
                'elevage_id' => 1,
                'fondateur' => 1,
                'foetus' => 0,
                'sire_id' => NULL,
                'dam_id' => NULL,
            ),
            4 => 
            array (
                'id' => 6,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => ' Myrrdhin',
                'affixe' => 'Coed Coch',
                'affixe_pre' => 1,
                'couleur' => NULL,
                'taille_cm' => 117,
                'race' => 'Welsh A',
                'sexe' => 'mâle',
                'date_achat' => NULL,
                'date_naissance' => '1965-02-13',
                'a_vendre' => 0,
                'prix' => NULL,
                'elevage_id' => 4,
                'fondateur' => 1,
                'foetus' => 0,
                'sire_id' => NULL,
                'dam_id' => NULL,
            ),
            5 => 
            array (
                'id' => 7,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'Keridwen',
                'affixe' => 'Coed Coch ',
                'affixe_pre' => 1,
                'couleur' => NULL,
                'taille_cm' => 111,
                'race' => 'Welsh A',
                'sexe' => 'femelle',
                'date_achat' => NULL,
                'date_naissance' => '1966-05-18',
                'a_vendre' => 0,
                'prix' => NULL,
                'elevage_id' => 4,
                'fondateur' => 1,
                'foetus' => 0,
                'sire_id' => NULL,
                'dam_id' => NULL,
            ),
            6 => 
            array (
                'id' => 8,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'Django',
                'affixe' => NULL,
                'affixe_pre' => 0,
                'couleur' => NULL,
                'taille_cm' => 81,
                'race' => 'Miniature',
                'sexe' => 'mâle',
                'date_achat' => NULL,
                'date_naissance' => '1967-05-23',
                'a_vendre' => 0,
                'prix' => NULL,
                'elevage_id' => 1,
                'fondateur' => 1,
                'foetus' => 0,
                'sire_id' => NULL,
                'dam_id' => NULL,
            ),
            7 => 
            array (
                'id' => 9,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'Owen',
                'affixe' => 'Ceulan ',
                'affixe_pre' => 1,
                'couleur' => NULL,
                'taille_cm' => 118,
                'race' => 'Welsh A',
                'sexe' => 'mâle',
                'date_achat' => NULL,
                'date_naissance' => '1964-03-21',
                'a_vendre' => 0,
                'prix' => NULL,
                'elevage_id' => 4,
                'fondateur' => 1,
                'foetus' => 0,
                'sire_id' => NULL,
                'dam_id' => NULL,
            ),
            8 => 
            array (
                'id' => 10,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => ' Lizzy',
                'affixe' => 'Bowdler',
                'affixe_pre' => 1,
                'couleur' => NULL,
                'taille_cm' => 113,
                'race' => 'Welsh A',
                'sexe' => 'femelle',
                'date_achat' => NULL,
                'date_naissance' => '1966-04-21',
                'a_vendre' => 0,
                'prix' => NULL,
                'elevage_id' => 4,
                'fondateur' => 1,
                'foetus' => 0,
                'sire_id' => NULL,
                'dam_id' => NULL,
            ),
            9 => 
            array (
                'id' => 11,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => ' Hero',
                'affixe' => 'Mathrafal',
                'affixe_pre' => 1,
                'couleur' => NULL,
                'taille_cm' => 120,
                'race' => 'Welsh A',
                'sexe' => 'mâle',
                'date_achat' => NULL,
                'date_naissance' => '1966-05-31',
                'a_vendre' => 0,
                'prix' => NULL,
                'elevage_id' => 4,
                'fondateur' => 1,
                'foetus' => 0,
                'sire_id' => NULL,
                'dam_id' => NULL,
            ),
            10 => 
            array (
                'id' => 12,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => ' Comet',
                'affixe' => 'Twyford',
                'affixe_pre' => 1,
                'couleur' => NULL,
                'taille_cm' => 119,
                'race' => 'Welsh A',
                'sexe' => 'mâle',
                'date_achat' => NULL,
                'date_naissance' => '1965-04-18',
                'a_vendre' => 0,
                'prix' => NULL,
                'elevage_id' => 4,
                'fondateur' => 1,
                'foetus' => 0,
                'sire_id' => NULL,
                'dam_id' => NULL,
            ),
            11 => 
            array (
                'id' => 13,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'Daffodil',
                'affixe' => 'Anglesey ',
                'affixe_pre' => 1,
                'couleur' => NULL,
                'taille_cm' => 109,
                'race' => 'Welsh A',
                'sexe' => 'femelle',
                'date_achat' => NULL,
                'date_naissance' => NULL,
                'a_vendre' => 0,
                'prix' => NULL,
                'elevage_id' => 4,
                'fondateur' => 1,
                'foetus' => 0,
                'sire_id' => NULL,
                'dam_id' => NULL,
            ),
            12 => 
            array (
                'id' => 14,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => ' Davy',
                'affixe' => 'Downland',
                'affixe_pre' => 1,
                'couleur' => NULL,
                'taille_cm' => 112,
                'race' => 'Welsh A',
                'sexe' => 'mâle',
                'date_achat' => NULL,
                'date_naissance' => NULL,
                'a_vendre' => 0,
                'prix' => NULL,
                'elevage_id' => 4,
                'fondateur' => 1,
                'foetus' => 0,
                'sire_id' => NULL,
                'dam_id' => NULL,
            ),
        ));
        
        
    }
}