<?php

use Illuminate\Database\Seeder;

class AssoRaceTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('asso_race')->delete();
        
        \DB::table('asso_race')->insert(array (
            0 => 
            array (
                'id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 4,
                'race_mere_id' => 5,
                'race_produit_id' => 5,
                'taille_conditions' => 0,
                'automatique' => 1,
                'commentaire' => 'Welsh toutes sections',
                'approbation' => 0,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => 100.0,
            ),
            1 => 
            array (
                'id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 5,
                'race_mere_id' => 4,
                'race_produit_id' => 5,
                'taille_conditions' => 0,
                'automatique' => 1,
                'commentaire' => 'Welsh toutes sections',
                'approbation' => 0,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => 100.0,
            ),
            2 => 
            array (
                'id' => 3,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 4,
                'race_mere_id' => 6,
                'race_produit_id' => 6,
                'taille_conditions' => 0,
                'automatique' => 1,
                'commentaire' => 'Welsh toutes sections',
                'approbation' => 0,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => 100.0,
            ),
            3 => 
            array (
                'id' => 4,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 4,
                'race_mere_id' => 7,
                'race_produit_id' => 6,
                'taille_conditions' => 0,
                'automatique' => 1,
                'commentaire' => 'Welsh toutes sections',
                'approbation' => 0,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => 100.0,
            ),
            4 => 
            array (
                'id' => 5,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 6,
                'race_mere_id' => 4,
                'race_produit_id' => 6,
                'taille_conditions' => 0,
                'automatique' => 1,
                'commentaire' => 'Welsh toutes sections',
                'approbation' => 0,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => 100.0,
            ),
            5 => 
            array (
                'id' => 6,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 7,
                'race_mere_id' => 4,
                'race_produit_id' => 6,
                'taille_conditions' => 0,
                'automatique' => 1,
                'commentaire' => 'Welsh toutes sections',
                'approbation' => 0,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => 100.0,
            ),
            6 => 
            array (
                'id' => 7,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 5,
                'race_mere_id' => 6,
                'race_produit_id' => 6,
                'taille_conditions' => 0,
                'automatique' => 1,
                'commentaire' => 'Welsh toutes sections',
                'approbation' => 0,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => 100.0,
            ),
            7 => 
            array (
                'id' => 8,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 6,
                'race_mere_id' => 5,
                'race_produit_id' => 6,
                'taille_conditions' => 0,
                'automatique' => 1,
                'commentaire' => 'Welsh toutes sections',
                'approbation' => 0,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => 100.0,
            ),
            8 => 
            array (
                'id' => 9,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 5,
                'race_mere_id' => 7,
                'race_produit_id' => 6,
                'taille_conditions' => 1,
                'automatique' => 1,
                'commentaire' => 'Welsh toutes sections',
                'approbation' => 0,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => 100.0,
            ),
            9 => 
            array (
                'id' => 10,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 7,
                'race_mere_id' => 5,
                'race_produit_id' => 6,
                'taille_conditions' => 1,
                'automatique' => 1,
                'commentaire' => 'Welsh toutes sections',
                'approbation' => 0,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => 100.0,
            ),
            10 => 
            array (
                'id' => 11,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 5,
                'race_mere_id' => 7,
                'race_produit_id' => 7,
                'taille_conditions' => 1,
                'automatique' => 1,
                'commentaire' => 'Welsh toutes sections',
                'approbation' => 0,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => 100.0,
            ),
            11 => 
            array (
                'id' => 12,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 7,
                'race_mere_id' => 5,
                'race_produit_id' => 7,
                'taille_conditions' => 1,
                'automatique' => 1,
                'commentaire' => 'Welsh toutes sections',
                'approbation' => 0,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => 100.0,
            ),
            12 => 
            array (
                'id' => 13,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 8,
                'race_mere_id' => NULL,
                'race_produit_id' => 9,
                'taille_conditions' => 0,
                'automatique' => 0,
                'commentaire' => 'DSA 50% min',
                'approbation' => 0,
                'pourCentArabe' => 50,
                'pourCentWelsh' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => NULL,
                'race_mere_id' => 8,
                'race_produit_id' => 9,
                'taille_conditions' => 0,
                'automatique' => 0,
                'commentaire' => 'DSA 50% min',
                'approbation' => 0,
                'pourCentArabe' => 50,
                'pourCentWelsh' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 8,
                'race_mere_id' => 4,
                'race_produit_id' => 11,
                'taille_conditions' => 0,
                'automatique' => 0,
                'commentaire' => 'FS',
                'approbation' => 1,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 8,
                'race_mere_id' => 5,
                'race_produit_id' => 11,
                'taille_conditions' => 0,
                'automatique' => 0,
                'commentaire' => 'FS',
                'approbation' => 1,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 8,
                'race_mere_id' => 6,
                'race_produit_id' => 11,
                'taille_conditions' => 0,
                'automatique' => 0,
                'commentaire' => 'FS',
                'approbation' => 1,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 8,
                'race_mere_id' => 7,
                'race_produit_id' => 11,
                'taille_conditions' => 0,
                'automatique' => 0,
                'commentaire' => 'FS',
                'approbation' => 1,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 4,
                'race_mere_id' => NULL,
                'race_produit_id' => 10,
                'taille_conditions' => 0,
                'automatique' => 0,
                'commentaire' => 'WPB',
                'approbation' => 0,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => 12.5,
            ),
            19 => 
            array (
                'id' => 20,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => NULL,
                'race_mere_id' => 4,
                'race_produit_id' => 10,
                'taille_conditions' => 0,
                'automatique' => 0,
                'commentaire' => 'WPB',
                'approbation' => 0,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => 12.5,
            ),
            20 => 
            array (
                'id' => 21,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 5,
                'race_mere_id' => NULL,
                'race_produit_id' => 10,
                'taille_conditions' => 0,
                'automatique' => 0,
                'commentaire' => 'WPB',
                'approbation' => 0,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => 12.5,
            ),
            21 => 
            array (
                'id' => 22,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => NULL,
                'race_mere_id' => 5,
                'race_produit_id' => 10,
                'taille_conditions' => 0,
                'automatique' => 0,
                'commentaire' => 'WPB',
                'approbation' => 0,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => 12.5,
            ),
            22 => 
            array (
                'id' => 23,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 6,
                'race_mere_id' => NULL,
                'race_produit_id' => 10,
                'taille_conditions' => 0,
                'automatique' => 0,
                'commentaire' => 'WPB',
                'approbation' => 0,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => 12.5,
            ),
            23 => 
            array (
                'id' => 24,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => NULL,
                'race_mere_id' => 6,
                'race_produit_id' => 10,
                'taille_conditions' => 0,
                'automatique' => 0,
                'commentaire' => 'WPB',
                'approbation' => 0,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => 12.5,
            ),
            24 => 
            array (
                'id' => 25,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 7,
                'race_mere_id' => NULL,
                'race_produit_id' => 10,
                'taille_conditions' => 0,
                'automatique' => 0,
                'commentaire' => 'WPB',
                'approbation' => 0,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => 12.5,
            ),
            25 => 
            array (
                'id' => 26,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => NULL,
                'race_mere_id' => 7,
                'race_produit_id' => 10,
                'taille_conditions' => 0,
                'automatique' => 0,
                'commentaire' => 'WPB',
                'approbation' => 0,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => 12.5,
            ),
            26 => 
            array (
                'id' => 27,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 8,
                'race_mere_id' => 10,
                'race_produit_id' => 11,
                'taille_conditions' => 1,
                'automatique' => 0,
                'commentaire' => 'FS',
                'approbation' => 1,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => NULL,
            ),
            27 => 
            array (
                'id' => 28,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 11,
                'race_mere_id' => 4,
                'race_produit_id' => 11,
                'taille_conditions' => 0,
                'automatique' => 0,
                'commentaire' => 'FS',
                'approbation' => 1,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => NULL,
            ),
            28 => 
            array (
                'id' => 29,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 11,
                'race_mere_id' => 5,
                'race_produit_id' => 11,
                'taille_conditions' => 0,
                'automatique' => 0,
                'commentaire' => 'FS',
                'approbation' => 1,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => NULL,
            ),
            29 => 
            array (
                'id' => 30,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 11,
                'race_mere_id' => 6,
                'race_produit_id' => 11,
                'taille_conditions' => 0,
                'automatique' => 0,
                'commentaire' => 'FS',
                'approbation' => 1,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => NULL,
            ),
            30 => 
            array (
                'id' => 31,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 11,
                'race_mere_id' => 7,
                'race_produit_id' => 11,
                'taille_conditions' => 0,
                'automatique' => 0,
                'commentaire' => 'FS',
                'approbation' => 1,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => NULL,
            ),
            31 => 
            array (
                'id' => 32,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 5,
                'race_mere_id' => 11,
                'race_produit_id' => 11,
                'taille_conditions' => 0,
                'automatique' => 0,
                'commentaire' => 'FS',
                'approbation' => 1,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => NULL,
            ),
            32 => 
            array (
                'id' => 33,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 4,
                'race_mere_id' => 11,
                'race_produit_id' => 11,
                'taille_conditions' => 0,
                'automatique' => 0,
                'commentaire' => 'FS',
                'approbation' => 1,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => NULL,
            ),
            33 => 
            array (
                'id' => 34,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 6,
                'race_mere_id' => 11,
                'race_produit_id' => 11,
                'taille_conditions' => 0,
                'automatique' => 0,
                'commentaire' => 'FS',
                'approbation' => 1,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => NULL,
            ),
            34 => 
            array (
                'id' => 35,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 7,
                'race_mere_id' => 11,
                'race_produit_id' => 11,
                'taille_conditions' => 0,
                'automatique' => 0,
                'commentaire' => 'FS',
                'approbation' => 1,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => NULL,
            ),
            35 => 
            array (
                'id' => 37,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 8,
                'race_mere_id' => 11,
                'race_produit_id' => 11,
                'taille_conditions' => 0,
                'automatique' => 0,
                'commentaire' => 'FS',
                'approbation' => 1,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => NULL,
            ),
            36 => 
            array (
                'id' => 38,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 3,
                'race_mere_id' => NULL,
                'race_produit_id' => 3,
                'taille_conditions' => 1,
                'automatique' => 0,
                'commentaire' => 'miniature',
                'approbation' => 0,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => NULL,
            ),
            37 => 
            array (
                'id' => 39,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => NULL,
                'race_mere_id' => 3,
                'race_produit_id' => 3,
                'taille_conditions' => 1,
                'automatique' => 0,
                'commentaire' => 'miniature',
                'approbation' => 0,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => NULL,
            ),
            38 => 
            array (
                'id' => 40,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 8,
                'race_mere_id' => 9,
                'race_produit_id' => 9,
                'taille_conditions' => 0,
                'automatique' => 0,
                'commentaire' => 'DSA > 50%',
                'approbation' => 0,
                'pourCentArabe' => 50,
                'pourCentWelsh' => NULL,
            ),
            39 => 
            array (
                'id' => 41,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 9,
                'race_mere_id' => 8,
                'race_produit_id' => 9,
                'taille_conditions' => 0,
                'automatique' => 0,
                'commentaire' => 'DSA > 50%',
                'approbation' => 0,
                'pourCentArabe' => 50,
                'pourCentWelsh' => NULL,
            ),
            40 => 
            array (
                'id' => 42,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 10,
                'race_mere_id' => 4,
                'race_produit_id' => 10,
                'taille_conditions' => 0,
                'automatique' => 0,
                'commentaire' => 'WPB',
                'approbation' => 0,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => 12.5,
            ),
            41 => 
            array (
                'id' => 43,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 10,
                'race_mere_id' => 5,
                'race_produit_id' => 10,
                'taille_conditions' => 0,
                'automatique' => 0,
                'commentaire' => 'WPB',
                'approbation' => 0,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => 12.5,
            ),
            42 => 
            array (
                'id' => 44,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 10,
                'race_mere_id' => 6,
                'race_produit_id' => 10,
                'taille_conditions' => 0,
                'automatique' => 0,
                'commentaire' => 'WPB',
                'approbation' => 0,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => 12.5,
            ),
            43 => 
            array (
                'id' => 45,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 10,
                'race_mere_id' => 7,
                'race_produit_id' => 10,
                'taille_conditions' => 0,
                'automatique' => 0,
                'commentaire' => 'WPB',
                'approbation' => 0,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => 12.5,
            ),
            44 => 
            array (
                'id' => 46,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 4,
                'race_mere_id' => 10,
                'race_produit_id' => 10,
                'taille_conditions' => 0,
                'automatique' => 0,
                'commentaire' => 'WPB',
                'approbation' => 0,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => 12.5,
            ),
            45 => 
            array (
                'id' => 47,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 5,
                'race_mere_id' => 10,
                'race_produit_id' => 10,
                'taille_conditions' => 0,
                'automatique' => 0,
                'commentaire' => 'WPB',
                'approbation' => 0,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => 12.5,
            ),
            46 => 
            array (
                'id' => 48,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 6,
                'race_mere_id' => 10,
                'race_produit_id' => 10,
                'taille_conditions' => 0,
                'automatique' => 0,
                'commentaire' => 'WPB',
                'approbation' => 0,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => 12.5,
            ),
            47 => 
            array (
                'id' => 49,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 7,
                'race_mere_id' => 10,
                'race_produit_id' => 10,
                'taille_conditions' => 0,
                'automatique' => 0,
                'commentaire' => 'WPB',
                'approbation' => 0,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => 12.5,
            ),
            48 => 
            array (
                'id' => 50,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 7,
                'race_mere_id' => 6,
                'race_produit_id' => 7,
                'taille_conditions' => 1,
                'automatique' => 1,
                'commentaire' => 'Welsh toutes sections',
                'approbation' => 0,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => 100.0,
            ),
            49 => 
            array (
                'id' => 51,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 6,
                'race_mere_id' => 7,
                'race_produit_id' => 7,
                'taille_conditions' => 1,
                'automatique' => 1,
                'commentaire' => 'Welsh toutes sections',
                'approbation' => 0,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => 100.0,
            ),
            50 => 
            array (
                'id' => 52,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 7,
                'race_mere_id' => 6,
                'race_produit_id' => 6,
                'taille_conditions' => 1,
                'automatique' => 1,
                'commentaire' => 'Welsh toutes sections',
                'approbation' => 0,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => 100.0,
            ),
            51 => 
            array (
                'id' => 53,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 6,
                'race_mere_id' => 7,
                'race_produit_id' => 6,
                'taille_conditions' => 1,
                'automatique' => 1,
                'commentaire' => 'Welsh toutes sections',
                'approbation' => 0,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => 100.0,
            ),
            52 => 
            array (
                'id' => 55,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 11,
                'race_mere_id' => 8,
                'race_produit_id' => 11,
                'taille_conditions' => 1,
                'automatique' => 0,
                'commentaire' => 'FS',
                'approbation' => 1,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => NULL,
            ),
            53 => 
            array (
                'id' => 56,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 11,
                'race_mere_id' => 10,
                'race_produit_id' => 11,
                'taille_conditions' => 1,
                'automatique' => 0,
                'commentaire' => 'FS',
                'approbation' => 1,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => NULL,
            ),
            54 => 
            array (
                'id' => 58,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 10,
                'race_mere_id' => 11,
                'race_produit_id' => 11,
                'taille_conditions' => 0,
                'automatique' => 0,
                'commentaire' => 'FS',
                'approbation' => 1,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => NULL,
            ),
            55 => 
            array (
                'id' => 72,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 4,
                'race_mere_id' => 10,
                'race_produit_id' => 11,
                'taille_conditions' => 1,
                'automatique' => 0,
                'commentaire' => 'FS',
                'approbation' => 1,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => NULL,
            ),
            56 => 
            array (
                'id' => 73,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 5,
                'race_mere_id' => 10,
                'race_produit_id' => 11,
                'taille_conditions' => 1,
                'automatique' => 0,
                'commentaire' => 'FS',
                'approbation' => 1,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => NULL,
            ),
            57 => 
            array (
                'id' => 74,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 6,
                'race_mere_id' => 10,
                'race_produit_id' => 11,
                'taille_conditions' => 1,
                'automatique' => 0,
                'commentaire' => 'FS',
                'approbation' => 1,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => NULL,
            ),
            58 => 
            array (
                'id' => 75,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 7,
                'race_mere_id' => 10,
                'race_produit_id' => 11,
                'taille_conditions' => 1,
                'automatique' => 0,
                'commentaire' => 'FS',
                'approbation' => 1,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => NULL,
            ),
            59 => 
            array (
                'id' => 76,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 4,
                'race_mere_id' => 8,
                'race_produit_id' => 11,
                'taille_conditions' => 1,
                'automatique' => 0,
                'commentaire' => 'FS',
                'approbation' => 1,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => NULL,
            ),
            60 => 
            array (
                'id' => 77,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 5,
                'race_mere_id' => 8,
                'race_produit_id' => 11,
                'taille_conditions' => 1,
                'automatique' => 0,
                'commentaire' => 'FS',
                'approbation' => 1,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => NULL,
            ),
            61 => 
            array (
                'id' => 78,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 6,
                'race_mere_id' => 8,
                'race_produit_id' => 11,
                'taille_conditions' => 1,
                'automatique' => 0,
                'commentaire' => 'FS',
                'approbation' => 1,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => NULL,
            ),
            62 => 
            array (
                'id' => 79,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 7,
                'race_mere_id' => 8,
                'race_produit_id' => 11,
                'taille_conditions' => 1,
                'automatique' => 0,
                'commentaire' => 'FS',
                'approbation' => 1,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => NULL,
            ),
            63 => 
            array (
                'id' => 80,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 10,
                'race_mere_id' => 8,
                'race_produit_id' => 11,
                'taille_conditions' => 1,
                'automatique' => 0,
                'commentaire' => 'FS',
                'approbation' => 1,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => NULL,
            ),
            64 => 
            array (
                'id' => 81,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => NULL,
                'race_mere_id' => NULL,
                'race_produit_id' => 10,
                'taille_conditions' => 0,
                'automatique' => 0,
                'commentaire' => 'WPB',
                'approbation' => 0,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => 12.5,
            ),
            65 => 
            array (
                'id' => 82,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => NULL,
                'race_mere_id' => NULL,
                'race_produit_id' => 9,
                'taille_conditions' => 0,
                'automatique' => 0,
                'commentaire' => 'DSA',
                'approbation' => 0,
                'pourCentArabe' => 50,
                'pourCentWelsh' => NULL,
            ),
            66 => 
            array (
                'id' => 83,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => NULL,
                'race_mere_id' => NULL,
                'race_produit_id' => 3,
                'taille_conditions' => 1,
                'automatique' => 0,
                'commentaire' => 'miniarure',
                'approbation' => 0,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => NULL,
            ),
            67 => 
            array (
                'id' => 84,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 12,
                'race_mere_id' => 11,
                'race_produit_id' => 11,
                'taille_conditions' => 0,
                'automatique' => 0,
                'commentaire' => 'FS',
                'approbation' => 1,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => NULL,
            ),
            68 => 
            array (
                'id' => 85,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 11,
                'race_mere_id' => 12,
                'race_produit_id' => 11,
                'taille_conditions' => 0,
                'automatique' => 0,
                'commentaire' => 'FS',
                'approbation' => 1,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => NULL,
            ),
            69 => 
            array (
                'id' => 86,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 12,
                'race_mere_id' => 8,
                'race_produit_id' => 11,
                'taille_conditions' => 0,
                'automatique' => 0,
                'commentaire' => 'FS',
                'approbation' => 1,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => NULL,
            ),
            70 => 
            array (
                'id' => 87,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 8,
                'race_mere_id' => 12,
                'race_produit_id' => 11,
                'taille_conditions' => 0,
                'automatique' => 0,
                'commentaire' => 'FS',
                'approbation' => 1,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => NULL,
            ),
            71 => 
            array (
                'id' => 88,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 12,
                'race_mere_id' => 10,
                'race_produit_id' => 11,
                'taille_conditions' => 1,
                'automatique' => 0,
                'commentaire' => 'FS',
                'approbation' => 1,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => NULL,
            ),
            72 => 
            array (
                'id' => 89,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 12,
                'race_mere_id' => 7,
                'race_produit_id' => 11,
                'taille_conditions' => 1,
                'automatique' => 0,
                'commentaire' => 'FS',
                'approbation' => 1,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => NULL,
            ),
            73 => 
            array (
                'id' => 90,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 12,
                'race_mere_id' => 6,
                'race_produit_id' => 11,
                'taille_conditions' => 0,
                'automatique' => 0,
                'commentaire' => 'FS',
                'approbation' => 1,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => NULL,
            ),
            74 => 
            array (
                'id' => 91,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 12,
                'race_mere_id' => 4,
                'race_produit_id' => 11,
                'taille_conditions' => 0,
                'automatique' => 0,
                'commentaire' => 'FS',
                'approbation' => 1,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => NULL,
            ),
            75 => 
            array (
                'id' => 92,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 12,
                'race_mere_id' => 5,
                'race_produit_id' => 11,
                'taille_conditions' => 0,
                'automatique' => 0,
                'commentaire' => 'FS',
                'approbation' => 1,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => NULL,
            ),
            76 => 
            array (
                'id' => 93,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 4,
                'race_mere_id' => 12,
                'race_produit_id' => 11,
                'taille_conditions' => 0,
                'automatique' => 0,
                'commentaire' => 'FS',
                'approbation' => 1,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => NULL,
            ),
            77 => 
            array (
                'id' => 94,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 5,
                'race_mere_id' => 12,
                'race_produit_id' => 11,
                'taille_conditions' => 0,
                'automatique' => 0,
                'commentaire' => 'FS',
                'approbation' => 1,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => NULL,
            ),
            78 => 
            array (
                'id' => 95,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 7,
                'race_mere_id' => 12,
                'race_produit_id' => 11,
                'taille_conditions' => 1,
                'automatique' => 0,
                'commentaire' => 'FS',
                'approbation' => 1,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => NULL,
            ),
            79 => 
            array (
                'id' => 96,
                'created_at' => NULL,
                'updated_at' => NULL,
                'race_pere_id' => 6,
                'race_mere_id' => 12,
                'race_produit_id' => 11,
                'taille_conditions' => 0,
                'automatique' => 0,
                'commentaire' => 'FS',
                'approbation' => 1,
                'pourCentArabe' => NULL,
                'pourCentWelsh' => NULL,
            ),
        ));
        
        
    }
}