<?php

use Illuminate\Database\Seeder;

class CategoriesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('categories')->delete();
        
        \DB::table('categories')->insert(array (
            0 => 
            array (
                'id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'mâles 2 ans',
                'type' => 'Modèle et Allures Race',
                'sexe' => 'mâle',
                'age_min' => 2,
                'age_max' => 2,
                'taille_min' => NULL,
                'taille_max' => NULL,
                'saillie' => NULL,
                'suitee' => NULL,
                'entier' => 1,
                'autorisé' => NULL,
                'approuvé' => NULL,
                'race_id' => 2,
            ),
            1 => 
            array (
                'id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'mâle 3 ans',
                'type' => 'Modèle et Allures Race',
                'sexe' => 'mâle',
                'age_min' => 3,
                'age_max' => 3,
                'taille_min' => NULL,
                'taille_max' => NULL,
                'saillie' => NULL,
                'suitee' => NULL,
                'entier' => 1,
                'autorisé' => NULL,
                'approuvé' => NULL,
                'race_id' => 2,
            ),
            2 => 
            array (
                'id' => 3,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'étalons',
                'type' => 'Modèle et Allures Race',
                'sexe' => 'mâle',
                'age_min' => 4,
                'age_max' => 18,
                'taille_min' => NULL,
                'taille_max' => NULL,
                'saillie' => NULL,
                'suitee' => NULL,
                'entier' => 1,
                'autorisé' => 1,
                'approuvé' => NULL,
                'race_id' => 2,
            ),
            3 => 
            array (
                'id' => 4,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'pouliches 2 ans',
                'type' => 'Modèle et Allures Race',
                'sexe' => 'femelle',
                'age_min' => 2,
                'age_max' => 2,
                'taille_min' => NULL,
                'taille_max' => NULL,
                'saillie' => NULL,
                'suitee' => NULL,
                'entier' => 1,
                'autorisé' => NULL,
                'approuvé' => NULL,
                'race_id' => 2,
            ),
            4 => 
            array (
                'id' => 5,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'ponettes',
                'type' => 'Modèle et Allures Race',
                'sexe' => 'femelle',
                'age_min' => 3,
                'age_max' => 18,
                'taille_min' => NULL,
                'taille_max' => NULL,
                'saillie' => 1,
                'suitee' => NULL,
                'entier' => 1,
                'autorisé' => NULL,
                'approuvé' => NULL,
                'race_id' => 2,
            ),
            5 => 
            array (
                'id' => 6,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'ponettes suitées',
                'type' => 'Modèle et Allures Race',
                'sexe' => 'femelle',
                'age_min' => 4,
                'age_max' => 18,
                'taille_min' => NULL,
                'taille_max' => NULL,
                'saillie' => 1,
                'suitee' => 1,
                'entier' => 1,
                'autorisé' => NULL,
                'approuvé' => NULL,
                'race_id' => 2,
            ),
            6 => 
            array (
                'id' => 7,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'pouliches 3 ans suitées',
                'type' => 'Modèle et Allures Race',
                'sexe' => 'femelle',
                'age_min' => 3,
                'age_max' => 3,
                'taille_min' => NULL,
                'taille_max' => NULL,
                'saillie' => NULL,
                'suitee' => 1,
                'entier' => 1,
                'autorisé' => NULL,
                'approuvé' => NULL,
                'race_id' => 2,
            ),
            7 => 
            array (
                'id' => 8,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'mâles 2 ans',
                'type' => 'Modèle et Allures Race',
                'sexe' => 'mâle',
                'age_min' => 2,
                'age_max' => 2,
                'taille_min' => NULL,
                'taille_max' => NULL,
                'saillie' => NULL,
                'suitee' => NULL,
                'entier' => 1,
                'autorisé' => NULL,
                'approuvé' => NULL,
                'race_id' => 4,
            ),
            8 => 
            array (
                'id' => 9,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'mâle 3 ans',
                'type' => 'Modèle et Allures Race',
                'sexe' => 'mâle',
                'age_min' => 3,
                'age_max' => 3,
                'taille_min' => NULL,
                'taille_max' => NULL,
                'saillie' => NULL,
                'suitee' => NULL,
                'entier' => 1,
                'autorisé' => NULL,
                'approuvé' => NULL,
                'race_id' => 4,
            ),
            9 => 
            array (
                'id' => 10,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'étalons',
                'type' => 'Modèle et Allures Race',
                'sexe' => 'mâle',
                'age_min' => 4,
                'age_max' => 18,
                'taille_min' => NULL,
                'taille_max' => NULL,
                'saillie' => NULL,
                'suitee' => NULL,
                'entier' => 1,
                'autorisé' => 1,
                'approuvé' => NULL,
                'race_id' => 4,
            ),
            10 => 
            array (
                'id' => 11,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'pouliches 2 ans',
                'type' => 'Modèle et Allures Race',
                'sexe' => 'femelle',
                'age_min' => 2,
                'age_max' => 2,
                'taille_min' => NULL,
                'taille_max' => NULL,
                'saillie' => NULL,
                'suitee' => NULL,
                'entier' => 1,
                'autorisé' => NULL,
                'approuvé' => NULL,
                'race_id' => 4,
            ),
            11 => 
            array (
                'id' => 12,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'ponettes',
                'type' => 'Modèle et Allures Race',
                'sexe' => 'femelle',
                'age_min' => 3,
                'age_max' => 18,
                'taille_min' => NULL,
                'taille_max' => NULL,
                'saillie' => 1,
                'suitee' => NULL,
                'entier' => 1,
                'autorisé' => NULL,
                'approuvé' => NULL,
                'race_id' => 4,
            ),
            12 => 
            array (
                'id' => 13,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'ponettes suitées',
                'type' => 'Modèle et Allures Race',
                'sexe' => 'femelle',
                'age_min' => 4,
                'age_max' => 18,
                'taille_min' => NULL,
                'taille_max' => NULL,
                'saillie' => 1,
                'suitee' => 1,
                'entier' => 1,
                'autorisé' => NULL,
                'approuvé' => NULL,
                'race_id' => 4,
            ),
            13 => 
            array (
                'id' => 14,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'pouliches 3 ans suitées',
                'type' => 'Modèle et Allures Race',
                'sexe' => 'femelle',
                'age_min' => 3,
                'age_max' => 3,
                'taille_min' => NULL,
                'taille_max' => NULL,
                'saillie' => NULL,
                'suitee' => 1,
                'entier' => 1,
                'autorisé' => NULL,
                'approuvé' => NULL,
                'race_id' => 4,
            ),
            14 => 
            array (
                'id' => 15,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'mâles 2 ans',
                'type' => 'Modèle et Allures Race',
                'sexe' => 'mâle',
                'age_min' => 2,
                'age_max' => 2,
                'taille_min' => NULL,
                'taille_max' => NULL,
                'saillie' => NULL,
                'suitee' => NULL,
                'entier' => 1,
                'autorisé' => NULL,
                'approuvé' => NULL,
                'race_id' => 5,
            ),
            15 => 
            array (
                'id' => 16,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'mâle 3 ans',
                'type' => 'Modèle et Allures Race',
                'sexe' => 'mâle',
                'age_min' => 3,
                'age_max' => 3,
                'taille_min' => NULL,
                'taille_max' => NULL,
                'saillie' => NULL,
                'suitee' => NULL,
                'entier' => 1,
                'autorisé' => NULL,
                'approuvé' => NULL,
                'race_id' => 5,
            ),
            16 => 
            array (
                'id' => 17,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'étalons',
                'type' => 'Modèle et Allures Race',
                'sexe' => 'mâle',
                'age_min' => 4,
                'age_max' => 18,
                'taille_min' => NULL,
                'taille_max' => NULL,
                'saillie' => NULL,
                'suitee' => NULL,
                'entier' => 1,
                'autorisé' => 1,
                'approuvé' => NULL,
                'race_id' => 5,
            ),
            17 => 
            array (
                'id' => 18,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'pouliches 2 ans',
                'type' => 'Modèle et Allures Race',
                'sexe' => 'femelle',
                'age_min' => 2,
                'age_max' => 2,
                'taille_min' => NULL,
                'taille_max' => NULL,
                'saillie' => NULL,
                'suitee' => NULL,
                'entier' => 1,
                'autorisé' => NULL,
                'approuvé' => NULL,
                'race_id' => 5,
            ),
            18 => 
            array (
                'id' => 19,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'ponettes',
                'type' => 'Modèle et Allures Race',
                'sexe' => 'femelle',
                'age_min' => 3,
                'age_max' => 18,
                'taille_min' => NULL,
                'taille_max' => NULL,
                'saillie' => 1,
                'suitee' => NULL,
                'entier' => 1,
                'autorisé' => NULL,
                'approuvé' => NULL,
                'race_id' => 5,
            ),
            19 => 
            array (
                'id' => 20,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'ponettes suitées',
                'type' => 'Modèle et Allures Race',
                'sexe' => 'femelle',
                'age_min' => 4,
                'age_max' => 18,
                'taille_min' => NULL,
                'taille_max' => NULL,
                'saillie' => 1,
                'suitee' => 1,
                'entier' => 1,
                'autorisé' => NULL,
                'approuvé' => NULL,
                'race_id' => 5,
            ),
            20 => 
            array (
                'id' => 21,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'pouliches 3 ans',
                'type' => 'Modèle et Allures Race',
                'sexe' => 'femelle',
                'age_min' => 3,
                'age_max' => 3,
                'taille_min' => NULL,
                'taille_max' => NULL,
                'saillie' => NULL,
                'suitee' => 1,
                'entier' => 1,
                'autorisé' => NULL,
                'approuvé' => NULL,
                'race_id' => 5,
            ),
            21 => 
            array (
                'id' => 22,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'mâles 2 ans',
                'type' => 'Modèle et Allures Race',
                'sexe' => 'mâle',
                'age_min' => 2,
                'age_max' => 2,
                'taille_min' => NULL,
                'taille_max' => NULL,
                'saillie' => NULL,
                'suitee' => NULL,
                'entier' => 1,
                'autorisé' => NULL,
                'approuvé' => NULL,
                'race_id' => 6,
            ),
            22 => 
            array (
                'id' => 23,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'mâle 3 ans',
                'type' => 'Modèle et Allures Race',
                'sexe' => 'mâle',
                'age_min' => 3,
                'age_max' => 3,
                'taille_min' => NULL,
                'taille_max' => NULL,
                'saillie' => NULL,
                'suitee' => NULL,
                'entier' => 1,
                'autorisé' => NULL,
                'approuvé' => NULL,
                'race_id' => 6,
            ),
            23 => 
            array (
                'id' => 24,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'étalons',
                'type' => 'Modèle et Allures Race',
                'sexe' => 'mâle',
                'age_min' => 4,
                'age_max' => 4,
                'taille_min' => NULL,
                'taille_max' => NULL,
                'saillie' => NULL,
                'suitee' => NULL,
                'entier' => 1,
                'autorisé' => 1,
                'approuvé' => NULL,
                'race_id' => 6,
            ),
            24 => 
            array (
                'id' => 25,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'pouliches 2 ans',
                'type' => 'Modèle et Allures Race',
                'sexe' => 'femelle',
                'age_min' => 2,
                'age_max' => 2,
                'taille_min' => NULL,
                'taille_max' => NULL,
                'saillie' => NULL,
                'suitee' => NULL,
                'entier' => 1,
                'autorisé' => NULL,
                'approuvé' => NULL,
                'race_id' => 6,
            ),
            25 => 
            array (
                'id' => 26,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'ponettes',
                'type' => 'Modèle et Allures Race',
                'sexe' => 'femelle',
                'age_min' => 3,
                'age_max' => 18,
                'taille_min' => NULL,
                'taille_max' => NULL,
                'saillie' => 1,
                'suitee' => NULL,
                'entier' => 1,
                'autorisé' => NULL,
                'approuvé' => NULL,
                'race_id' => 6,
            ),
            26 => 
            array (
                'id' => 27,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'ponettes suitées',
                'type' => 'Modèle et Allures Race',
                'sexe' => 'femelle',
                'age_min' => 4,
                'age_max' => 18,
                'taille_min' => NULL,
                'taille_max' => NULL,
                'saillie' => 1,
                'suitee' => 1,
                'entier' => 1,
                'autorisé' => NULL,
                'approuvé' => NULL,
                'race_id' => 6,
            ),
            27 => 
            array (
                'id' => 28,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'pouliches 3 ans',
                'type' => 'Modèle et Allures Race',
                'sexe' => 'femelle',
                'age_min' => 4,
                'age_max' => 3,
                'taille_min' => NULL,
                'taille_max' => NULL,
                'saillie' => NULL,
                'suitee' => 1,
                'entier' => 1,
                'autorisé' => NULL,
                'approuvé' => NULL,
                'race_id' => 6,
            ),
            28 => 
            array (
                'id' => 29,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'mâles 2 ans',
                'type' => 'Modèle et Allures Race',
                'sexe' => 'mâle',
                'age_min' => 2,
                'age_max' => 2,
                'taille_min' => NULL,
                'taille_max' => NULL,
                'saillie' => NULL,
                'suitee' => NULL,
                'entier' => 1,
                'autorisé' => NULL,
                'approuvé' => NULL,
                'race_id' => 7,
            ),
            29 => 
            array (
                'id' => 30,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'mâle 3 ans',
                'type' => 'Modèle et Allures Race',
                'sexe' => 'mâle',
                'age_min' => 3,
                'age_max' => 3,
                'taille_min' => NULL,
                'taille_max' => NULL,
                'saillie' => NULL,
                'suitee' => NULL,
                'entier' => 1,
                'autorisé' => NULL,
                'approuvé' => NULL,
                'race_id' => 7,
            ),
            30 => 
            array (
                'id' => 31,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'étalons',
                'type' => 'Modèle et Allures Race',
                'sexe' => 'mâle',
                'age_min' => 4,
                'age_max' => 18,
                'taille_min' => NULL,
                'taille_max' => NULL,
                'saillie' => NULL,
                'suitee' => NULL,
                'entier' => 1,
                'autorisé' => 1,
                'approuvé' => NULL,
                'race_id' => 7,
            ),
            31 => 
            array (
                'id' => 32,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'pouliches 2 ans',
                'type' => 'Modèle et Allures Race',
                'sexe' => 'femelle',
                'age_min' => 2,
                'age_max' => 2,
                'taille_min' => NULL,
                'taille_max' => NULL,
                'saillie' => NULL,
                'suitee' => NULL,
                'entier' => 1,
                'autorisé' => NULL,
                'approuvé' => NULL,
                'race_id' => 7,
            ),
            32 => 
            array (
                'id' => 33,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'ponettes',
                'type' => 'Modèle et Allures Race',
                'sexe' => 'femelle',
                'age_min' => 3,
                'age_max' => 18,
                'taille_min' => NULL,
                'taille_max' => NULL,
                'saillie' => 1,
                'suitee' => NULL,
                'entier' => 1,
                'autorisé' => NULL,
                'approuvé' => NULL,
                'race_id' => 7,
            ),
            33 => 
            array (
                'id' => 34,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'ponettes suitées',
                'type' => 'Modèle et Allures Race',
                'sexe' => 'femelle',
                'age_min' => 4,
                'age_max' => 18,
                'taille_min' => NULL,
                'taille_max' => NULL,
                'saillie' => 1,
                'suitee' => 1,
                'entier' => 1,
                'autorisé' => NULL,
                'approuvé' => NULL,
                'race_id' => 7,
            ),
            34 => 
            array (
                'id' => 35,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'pouliches 3 ans',
                'type' => 'Modèle et Allures Race',
                'sexe' => 'femelle',
                'age_min' => 3,
                'age_max' => 3,
                'taille_min' => NULL,
                'taille_max' => NULL,
                'saillie' => NULL,
                'suitee' => 1,
                'entier' => 1,
                'autorisé' => NULL,
                'approuvé' => NULL,
                'race_id' => 7,
            ),
            35 => 
            array (
                'id' => 36,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'mâles 2 ans',
                'type' => 'Modèle et Allures Race',
                'sexe' => 'mâle',
                'age_min' => 2,
                'age_max' => 2,
                'taille_min' => NULL,
                'taille_max' => NULL,
                'saillie' => NULL,
                'suitee' => NULL,
                'entier' => 1,
                'autorisé' => NULL,
                'approuvé' => NULL,
                'race_id' => 10,
            ),
            36 => 
            array (
                'id' => 37,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'mâle 3 ans',
                'type' => 'Modèle et Allures Race',
                'sexe' => 'mâle',
                'age_min' => 3,
                'age_max' => 3,
                'taille_min' => NULL,
                'taille_max' => NULL,
                'saillie' => NULL,
                'suitee' => NULL,
                'entier' => 1,
                'autorisé' => NULL,
                'approuvé' => NULL,
                'race_id' => 10,
            ),
            37 => 
            array (
                'id' => 38,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'étalons',
                'type' => 'Modèle et Allures Race',
                'sexe' => 'mâle',
                'age_min' => 4,
                'age_max' => 18,
                'taille_min' => NULL,
                'taille_max' => NULL,
                'saillie' => NULL,
                'suitee' => NULL,
                'entier' => 1,
                'autorisé' => 1,
                'approuvé' => NULL,
                'race_id' => 10,
            ),
            38 => 
            array (
                'id' => 39,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'pouliches 2 ans',
                'type' => 'Modèle et Allures Race',
                'sexe' => 'femelle',
                'age_min' => 2,
                'age_max' => 2,
                'taille_min' => NULL,
                'taille_max' => NULL,
                'saillie' => NULL,
                'suitee' => NULL,
                'entier' => 1,
                'autorisé' => NULL,
                'approuvé' => NULL,
                'race_id' => 10,
            ),
            39 => 
            array (
                'id' => 40,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'ponettes',
                'type' => 'Modèle et Allures Race',
                'sexe' => 'femelle',
                'age_min' => 3,
                'age_max' => 18,
                'taille_min' => NULL,
                'taille_max' => NULL,
                'saillie' => 1,
                'suitee' => NULL,
                'entier' => 1,
                'autorisé' => NULL,
                'approuvé' => NULL,
                'race_id' => 10,
            ),
            40 => 
            array (
                'id' => 41,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'ponettes suitées',
                'type' => 'Modèle et Allures Race',
                'sexe' => 'femelle',
                'age_min' => 4,
                'age_max' => 18,
                'taille_min' => NULL,
                'taille_max' => NULL,
                'saillie' => 1,
                'suitee' => 1,
                'entier' => 1,
                'autorisé' => NULL,
                'approuvé' => NULL,
                'race_id' => 10,
            ),
            41 => 
            array (
                'id' => 42,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'pouliches 3 ans',
                'type' => 'Modèle et Allures Race',
                'sexe' => 'femelle',
                'age_min' => 29,
                'age_max' => 47,
                'taille_min' => NULL,
                'taille_max' => NULL,
                'saillie' => NULL,
                'suitee' => 1,
                'entier' => 1,
                'autorisé' => NULL,
                'approuvé' => NULL,
                'race_id' => 10,
            ),
        ));
        
        
    }
}