<?php

use Illuminate\Database\Seeder;

class CategoriesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('Categories')->delete();
        
        \DB::table('Categories')->insert(array (
            0 => 
            array (
                'id' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'mâles 2 ans',
                'concours_id' => 1,
                'type' => 'en main',
                'sexe' => 'mâle',
                'age_min' => 17,
                'age_max' => 35,
                'taille_min' => NULL,
                'taille_max' => NULL,
                'saillie' => NULL,
                'suitee' => NULL,
                'entier' => 1,
                'autorisé' => NULL,
                'approuvé' => NULL,
                'race_id' => 2,
            ),
            1 => 
            array (
                'id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'mâle 3 ans',
                'concours_id' => 1,
                'type' => 'en main',
                'sexe' => 'mâle',
                'age_min' => 29,
                'age_max' => 47,
                'taille_min' => NULL,
                'taille_max' => NULL,
                'saillie' => NULL,
                'suitee' => NULL,
                'entier' => 1,
                'autorisé' => NULL,
                'approuvé' => NULL,
                'race_id' => 2,
            ),
            2 => 
            array (
                'id' => 3,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'étalons',
                'concours_id' => 1,
                'type' => 'en main',
                'sexe' => 'mâle',
                'age_min' => 41,
                'age_max' => 255,
                'taille_min' => NULL,
                'taille_max' => NULL,
                'saillie' => NULL,
                'suitee' => NULL,
                'entier' => 1,
                'autorisé' => 1,
                'approuvé' => NULL,
                'race_id' => 2,
            ),
            3 => 
            array (
                'id' => 4,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'pouliches 2 ans',
                'concours_id' => 1,
                'type' => 'en main',
                'sexe' => 'femelle',
                'age_min' => 17,
                'age_max' => 35,
                'taille_min' => NULL,
                'taille_max' => NULL,
                'saillie' => NULL,
                'suitee' => NULL,
                'entier' => 1,
                'autorisé' => NULL,
                'approuvé' => NULL,
                'race_id' => 2,
            ),
            4 => 
            array (
                'id' => 5,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'ponettes',
                'concours_id' => 1,
                'type' => 'en main',
                'sexe' => 'femelle',
                'age_min' => 41,
                'age_max' => 216,
                'taille_min' => NULL,
                'taille_max' => NULL,
                'saillie' => 1,
                'suitee' => NULL,
                'entier' => 1,
                'autorisé' => NULL,
                'approuvé' => NULL,
                'race_id' => 2,
            ),
            5 => 
            array (
                'id' => 6,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'ponettes suitées',
                'concours_id' => 1,
                'type' => 'en main',
                'sexe' => 'femelle',
                'age_min' => 41,
                'age_max' => 216,
                'taille_min' => NULL,
                'taille_max' => NULL,
                'saillie' => 1,
                'suitee' => 1,
                'entier' => 1,
                'autorisé' => NULL,
                'approuvé' => NULL,
                'race_id' => 2,
            ),
            6 => 
            array (
                'id' => 7,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'pouliches 3 ans suitées',
                'concours_id' => 1,
                'type' => 'en main',
                'sexe' => 'femelle',
                'age_min' => 29,
                'age_max' => 47,
                'taille_min' => NULL,
                'taille_max' => NULL,
                'saillie' => NULL,
                'suitee' => 1,
                'entier' => 1,
                'autorisé' => NULL,
                'approuvé' => NULL,
                'race_id' => 2,
            ),
        ));
        \DB::table('Categories')->insert(array (
            0 => 
            array (
                'id' => 8,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'mâles 2 ans',
                'concours_id' => 1,
                'type' => 'en main',
                'sexe' => 'mâle',
                'age_min' => 17,
                'age_max' => 35,
                'taille_min' => NULL,
                'taille_max' => NULL,
                'saillie' => NULL,
                'suitee' => NULL,
                'entier' => 1,
                'autorisé' => NULL,
                'approuvé' => NULL,
                'race_id' => 4,
            ),
            1 => 
            array (
                'id' => 9,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'mâle 3 ans',
                'concours_id' => 1,
                'type' => 'en main',
                'sexe' => 'mâle',
                'age_min' => 29,
                'age_max' => 47,
                'taille_min' => NULL,
                'taille_max' => NULL,
                'saillie' => NULL,
                'suitee' => NULL,
                'entier' => 1,
                'autorisé' => NULL,
                'approuvé' => NULL,
                'race_id' => 4,
            ),
            2 => 
            array (
                'id' => 10,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'étalons',
                'concours_id' => 1,
                'type' => 'en main',
                'sexe' => 'mâle',
                'age_min' => 41,
                'age_max' => 255,
                'taille_min' => NULL,
                'taille_max' => NULL,
                'saillie' => NULL,
                'suitee' => NULL,
                'entier' => 1,
                'autorisé' => 1,
                'approuvé' => NULL,
                'race_id' => 4,
            ),
            3 => 
            array (
                'id' => 11,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'pouliches 2 ans',
                'concours_id' => 1,
                'type' => 'en main',
                'sexe' => 'femelle',
                'age_min' => 17,
                'age_max' => 35,
                'taille_min' => NULL,
                'taille_max' => NULL,
                'saillie' => NULL,
                'suitee' => NULL,
                'entier' => 1,
                'autorisé' => NULL,
                'approuvé' => NULL,
                'race_id' => 4,
            ),
            4 => 
            array (
                'id' => 12,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'ponettes',
                'concours_id' => 1,
                'type' => 'en main',
                'sexe' => 'femelle',
                'age_min' => 41,
                'age_max' => 216,
                'taille_min' => NULL,
                'taille_max' => NULL,
                'saillie' => 1,
                'suitee' => NULL,
                'entier' => 1,
                'autorisé' => NULL,
                'approuvé' => NULL,
                'race_id' => 4,
            ),
            5 => 
            array (
                'id' => 13,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'ponettes suitées',
                'concours_id' => 1,
                'type' => 'en main',
                'sexe' => 'femelle',
                'age_min' => 41,
                'age_max' => 216,
                'taille_min' => NULL,
                'taille_max' => NULL,
                'saillie' => 1,
                'suitee' => 1,
                'entier' => 1,
                'autorisé' => NULL,
                'approuvé' => NULL,
                'race_id' => 4,
            ),
            6 => 
            array (
                'id' => 14,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'pouliches 3 ans suitées',
                'concours_id' => 1,
                'type' => 'en main',
                'sexe' => 'femelle',
                'age_min' => 29,
                'age_max' => 47,
                'taille_min' => NULL,
                'taille_max' => NULL,
                'saillie' => NULL,
                'suitee' => 1,
                'entier' => 1,
                'autorisé' => NULL,
                'approuvé' => NULL,
                'race_id' => 4,
            ),
        ));
        \DB::table('Categories')->insert(array (
            0 => 
            array (
                'id' => 15,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'mâles 2 ans',
                'concours_id' => 1,
                'type' => 'en main',
                'sexe' => 'mâle',
                'age_min' => 17,
                'age_max' => 35,
                'taille_min' => NULL,
                'taille_max' => NULL,
                'saillie' => NULL,
                'suitee' => NULL,
                'entier' => 1,
                'autorisé' => NULL,
                'approuvé' => NULL,
                'race_id' => 5,
            ),
            1 => 
            array (
                'id' => 16,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'mâle 3 ans',
                'concours_id' => 1,
                'type' => 'en main',
                'sexe' => 'mâle',
                'age_min' => 29,
                'age_max' => 47,
                'taille_min' => NULL,
                'taille_max' => NULL,
                'saillie' => NULL,
                'suitee' => NULL,
                'entier' => 1,
                'autorisé' => NULL,
                'approuvé' => NULL,
                'race_id' => 5,
            ),
            2 => 
            array (
                'id' => 17,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'étalons',
                'concours_id' => 1,
                'type' => 'en main',
                'sexe' => 'mâle',
                'age_min' => 41,
                'age_max' => 255,
                'taille_min' => NULL,
                'taille_max' => NULL,
                'saillie' => NULL,
                'suitee' => NULL,
                'entier' => 1,
                'autorisé' => 1,
                'approuvé' => NULL,
                'race_id' => 5,
            ),
            3 => 
            array (
                'id' => 18,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'pouliches 2 ans',
                'concours_id' => 1,
                'type' => 'en main',
                'sexe' => 'femelle',
                'age_min' => 17,
                'age_max' => 35,
                'taille_min' => NULL,
                'taille_max' => NULL,
                'saillie' => NULL,
                'suitee' => NULL,
                'entier' => 1,
                'autorisé' => NULL,
                'approuvé' => NULL,
                'race_id' => 5,
            ),
            4 => 
            array (
                'id' => 19,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'ponettes',
                'concours_id' => 1,
                'type' => 'en main',
                'sexe' => 'femelle',
                'age_min' => 41,
                'age_max' => 216,
                'taille_min' => NULL,
                'taille_max' => NULL,
                'saillie' => 1,
                'suitee' => NULL,
                'entier' => 1,
                'autorisé' => NULL,
                'approuvé' => NULL,
                'race_id' => 5,
            ),
            5 => 
            array (
                'id' => 20,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'ponettes suitées',
                'concours_id' => 1,
                'type' => 'en main',
                'sexe' => 'femelle',
                'age_min' => 41,
                'age_max' => 216,
                'taille_min' => NULL,
                'taille_max' => NULL,
                'saillie' => 1,
                'suitee' => 1,
                'entier' => 1,
                'autorisé' => NULL,
                'approuvé' => NULL,
                'race_id' => 5,
            ),
            6 => 
            array (
                'id' => 21,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'pouliches 3 ans',
                'concours_id' => 1,
                'type' => 'en main',
                'sexe' => 'femelle',
                'age_min' => 29,
                'age_max' => 47,
                'taille_min' => NULL,
                'taille_max' => NULL,
                'saillie' => NULL,
                'suitee' => 1,
                'entier' => 1,
                'autorisé' => NULL,
                'approuvé' => NULL,
                'race_id' => 5,
            ),
        ));
        \DB::table('Categories')->insert(array (
            0 => 
            array (
                'id' => 22,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'mâles 2 ans',
                'concours_id' => 1,
                'type' => 'en main',
                'sexe' => 'mâle',
                'age_min' => 17,
                'age_max' => 35,
                'taille_min' => NULL,
                'taille_max' => NULL,
                'saillie' => NULL,
                'suitee' => NULL,
                'entier' => 1,
                'autorisé' => NULL,
                'approuvé' => NULL,
                'race_id' => 6,
            ),
            1 => 
            array (
                'id' => 23,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'mâle 3 ans',
                'concours_id' => 1,
                'type' => 'en main',
                'sexe' => 'mâle',
                'age_min' => 29,
                'age_max' => 47,
                'taille_min' => NULL,
                'taille_max' => NULL,
                'saillie' => NULL,
                'suitee' => NULL,
                'entier' => 1,
                'autorisé' => NULL,
                'approuvé' => NULL,
                'race_id' => 6,
            ),
            2 => 
            array (
                'id' => 24,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'étalons',
                'concours_id' => 1,
                'type' => 'en main',
                'sexe' => 'mâle',
                'age_min' => 41,
                'age_max' => 255,
                'taille_min' => NULL,
                'taille_max' => NULL,
                'saillie' => NULL,
                'suitee' => NULL,
                'entier' => 1,
                'autorisé' => 1,
                'approuvé' => NULL,
                'race_id' => 6,
            ),
            3 => 
            array (
                'id' => 25,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'pouliches 2 ans',
                'concours_id' => 1,
                'type' => 'en main',
                'sexe' => 'femelle',
                'age_min' => 17,
                'age_max' => 35,
                'taille_min' => NULL,
                'taille_max' => NULL,
                'saillie' => NULL,
                'suitee' => NULL,
                'entier' => 1,
                'autorisé' => NULL,
                'approuvé' => NULL,
                'race_id' => 6,
            ),
            4 => 
            array (
                'id' => 26,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'ponettes',
                'concours_id' => 1,
                'type' => 'en main',
                'sexe' => 'femelle',
                'age_min' => 41,
                'age_max' => 216,
                'taille_min' => NULL,
                'taille_max' => NULL,
                'saillie' => 1,
                'suitee' => NULL,
                'entier' => 1,
                'autorisé' => NULL,
                'approuvé' => NULL,
                'race_id' => 6,
            ),
            5 => 
            array (
                'id' => 27,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'ponettes suitées',
                'concours_id' => 1,
                'type' => 'en main',
                'sexe' => 'femelle',
                'age_min' => 41,
                'age_max' => 216,
                'taille_min' => NULL,
                'taille_max' => NULL,
                'saillie' => 1,
                'suitee' => 1,
                'entier' => 1,
                'autorisé' => NULL,
                'approuvé' => NULL,
                'race_id' => 6,
            ),
            6 => 
            array (
                'id' => 28,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'pouliches 3 ans',
                'concours_id' => 1,
                'type' => 'en main',
                'sexe' => 'femelle',
                'age_min' => 29,
                'age_max' => 47,
                'taille_min' => NULL,
                'taille_max' => NULL,
                'saillie' => NULL,
                'suitee' => 1,
                'entier' => 1,
                'autorisé' => NULL,
                'approuvé' => NULL,
                'race_id' => 6,
            ),
        ));
        \DB::table('Categories')->insert(array (
            0 => 
            array (
                'id' => 29,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'mâles 2 ans',
                'concours_id' => 1,
                'type' => 'en main',
                'sexe' => 'mâle',
                'age_min' => 17,
                'age_max' => 35,
                'taille_min' => NULL,
                'taille_max' => NULL,
                'saillie' => NULL,
                'suitee' => NULL,
                'entier' => 1,
                'autorisé' => NULL,
                'approuvé' => NULL,
                'race_id' => 7,
            ),
            1 => 
            array (
                'id' =>30,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'mâle 3 ans',
                'concours_id' => 1,
                'type' => 'en main',
                'sexe' => 'mâle',
                'age_min' => 29,
                'age_max' => 47,
                'taille_min' => NULL,
                'taille_max' => NULL,
                'saillie' => NULL,
                'suitee' => NULL,
                'entier' => 1,
                'autorisé' => NULL,
                'approuvé' => NULL,
                'race_id' => 7,
            ),
            2 => 
            array (
                'id' => 31,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'étalons',
                'concours_id' => 1,
                'type' => 'en main',
                'sexe' => 'mâle',
                'age_min' => 41,
                'age_max' => 255,
                'taille_min' => NULL,
                'taille_max' => NULL,
                'saillie' => NULL,
                'suitee' => NULL,
                'entier' => 1,
                'autorisé' => 1,
                'approuvé' => NULL,
                'race_id' => 7,
            ),
            3 => 
            array (
                'id' => 32,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'pouliches 2 ans',
                'concours_id' => 1,
                'type' => 'en main',
                'sexe' => 'femelle',
                'age_min' => 17,
                'age_max' => 35,
                'taille_min' => NULL,
                'taille_max' => NULL,
                'saillie' => NULL,
                'suitee' => NULL,
                'entier' => 1,
                'autorisé' => NULL,
                'approuvé' => NULL,
                'race_id' => 7,
            ),
            4 => 
            array (
                'id' => 33,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'ponettes',
                'concours_id' => 1,
                'type' => 'en main',
                'sexe' => 'femelle',
                'age_min' => 41,
                'age_max' => 216,
                'taille_min' => NULL,
                'taille_max' => NULL,
                'saillie' => 1,
                'suitee' => NULL,
                'entier' => 1,
                'autorisé' => NULL,
                'approuvé' => NULL,
                'race_id' => 7,
            ),
            5 => 
            array (
                'id' => 34,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'ponettes suitées',
                'concours_id' => 1,
                'type' => 'en main',
                'sexe' => 'femelle',
                'age_min' => 41,
                'age_max' => 216,
                'taille_min' => NULL,
                'taille_max' => NULL,
                'saillie' => 1,
                'suitee' => 1,
                'entier' => 1,
                'autorisé' => NULL,
                'approuvé' => NULL,
                'race_id' => 7,
            ),
            6 => 
            array (
                'id' => 35,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'pouliches 3 ans',
                'concours_id' => 1,
                'type' => 'en main',
                'sexe' => 'femelle',
                'age_min' => 29,
                'age_max' => 47,
                'taille_min' => NULL,
                'taille_max' => NULL,
                'saillie' => NULL,
                'suitee' => 1,
                'entier' => 1,
                'autorisé' => NULL,
                'approuvé' => NULL,
                'race_id' => 7,
            ),
        ));
        \DB::table('Categories')->insert(array (
            0 => 
            array (
                'id' => 36,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'mâles 2 ans',
                'concours_id' => 1,
                'type' => 'en main',
                'sexe' => 'mâle',
                'age_min' => 17,
                'age_max' => 35,
                'taille_min' => NULL,
                'taille_max' => NULL,
                'saillie' => NULL,
                'suitee' => NULL,
                'entier' => 1,
                'autorisé' => NULL,
                'approuvé' => NULL,
                'race_id' => 10,
            ),
            1 => 
            array (
                'id' => 37,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'mâle 3 ans',
                'concours_id' => 1,
                'type' => 'en main',
                'sexe' => 'mâle',
                'age_min' => 29,
                'age_max' => 47,
                'taille_min' => NULL,
                'taille_max' => NULL,
                'saillie' => NULL,
                'suitee' => NULL,
                'entier' => 1,
                'autorisé' => NULL,
                'approuvé' => NULL,
                'race_id' => 10,
            ),
            2 => 
            array (
                'id' => 38,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'étalons',
                'concours_id' => 1,
                'type' => 'en main',
                'sexe' => 'mâle',
                'age_min' => 41,
                'age_max' => 255,
                'taille_min' => NULL,
                'taille_max' => NULL,
                'saillie' => NULL,
                'suitee' => NULL,
                'entier' => 1,
                'autorisé' => 1,
                'approuvé' => NULL,
                'race_id' => 10,
            ),
            3 => 
            array (
                'id' => 39,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'pouliches 2 ans',
                'concours_id' => 1,
                'type' => 'en main',
                'sexe' => 'femelle',
                'age_min' => 17,
                'age_max' => 35,
                'taille_min' => NULL,
                'taille_max' => NULL,
                'saillie' => NULL,
                'suitee' => NULL,
                'entier' => 1,
                'autorisé' => NULL,
                'approuvé' => NULL,
                'race_id' => 10,
            ),
            4 => 
            array (
                'id' => 40,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'ponettes',
                'concours_id' => 1,
                'type' => 'en main',
                'sexe' => 'femelle',
                'age_min' => 41,
                'age_max' => 216,
                'taille_min' => NULL,
                'taille_max' => NULL,
                'saillie' => 1,
                'suitee' => NULL,
                'entier' => 1,
                'autorisé' => NULL,
                'approuvé' => NULL,
                'race_id' => 10,
            ),
            5 => 
            array (
                'id' => 41,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'ponettes suitées',
                'concours_id' => 1,
                'type' => 'en main',
                'sexe' => 'femelle',
                'age_min' => 41,
                'age_max' => 216,
                'taille_min' => NULL,
                'taille_max' => NULL,
                'saillie' => 1,
                'suitee' => 1,
                'entier' => 1,
                'autorisé' => NULL,
                'approuvé' => NULL,
                'race_id' => 10,
            ),
            6 => 
            array (
                'id' => 42,
                'created_at' => NULL,
                'updated_at' => NULL,
                'nom' => 'pouliches 3 ans',
                'concours_id' => 1,
                'type' => 'en main',
                'sexe' => 'femelle',
                'age_min' => 29,
                'age_max' => 47,
                'taille_min' => NULL,
                'taille_max' => NULL,
                'saillie' => NULL,
                'suitee' => 1,
                'entier' => 1,
                'autorisé' => NULL,
                'approuvé' => NULL,
                'race_id' => 10,
            ),
        ));
        
        
    }
}