<?php

use Illuminate\Database\Seeder;

class AnimauxTableSeederTest extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('animaux')->delete();
        
        \DB::table('animaux')->insert(array (
            0 => 
            array (
                'id' => 2,
                'created_at' => NULL,
                'updated_at' => '2021-01-06 15:52:26',
                'nom' => 'Mignonne',
                'affixe_id' => 1,
                'couleur' => 'bai dun pangaré',
                'base' => 'bai',
                'taille_cm' => 99,
                'race_id' => 2,
                'sexe' => 'jeune femelle',
                'date_achat' => '1970-01-11',
                'date_naissance' => '1968-05-13',
                'a_vendre' => 0,
                'prix' => NULL,
                'elevage_id' => 1,
                'fondateur' => 1,
                'foetus' => 0,
                'consang' => 0.0,
                'sire_id' => NULL,
                'dam_id' => NULL,
                'modele_allures' => 11,
                'modele_allures_additifs' => 11,
                'taille_additive' => 99,
                'notes' => NULL,
            ),
            1 => 
            array (
                'id' => 3,
                'created_at' => NULL,
                'updated_at' => '2021-01-05 17:21:24',
                'nom' => 'Popeye',
                'affixe_id' => 3,
                'couleur' => 'alezan tobiano',
                'base' => 'alezan agouti',
                'taille_cm' => 102,
                'race_id' => 2,
                'sexe' => 'jeune mâle',
                'date_achat' => '1970-02-11',
                'date_naissance' => '1969-04-15',
                'a_vendre' => 0,
                'prix' => NULL,
                'elevage_id' => 1,
                'fondateur' => 1,
                'foetus' => 0,
                'consang' => 0.0,
                'sire_id' => NULL,
                'dam_id' => NULL,
                'modele_allures' => 16,
                'modele_allures_additifs' => 16,
                'taille_additive' => 102,
                'notes' => NULL,
            ),
            2 => 
            array (
                'id' => 4,
                'created_at' => NULL,
                'updated_at' => '2021-01-06 15:45:34',
                'nom' => 'Diana',
                'affixe_id' => 4,
                'couleur' => 'gris',
                'base' => 'noir',
                'taille_cm' => 114,
                'race_id' => 4,
                'sexe' => 'jeune femelle',
                'date_achat' => NULL,
                'date_naissance' => '1968-04-12',
                'a_vendre' => 0,
                'prix' => 1500,
                'elevage_id' => 10,
                'fondateur' => 1,
                'foetus' => 0,
                'consang' => 0.0,
                'sire_id' => NULL,
                'dam_id' => NULL,
                'modele_allures' => 12,
                'modele_allures_additifs' => 12,
                'taille_additive' => 114,
                'notes' => NULL,
            ),
            3 => 
            array (
                'id' => 5,
                'created_at' => NULL,
                'updated_at' => '2021-01-05 17:21:24',
                'nom' => 'Molly',
                'affixe_id' => 3,
                'couleur' => 'isabelle',
                'base' => 'bai',
                'taille_cm' => 106,
                'race_id' => 2,
                'sexe' => 'jeune femelle',
                'date_achat' => '1970-02-16',
                'date_naissance' => '1969-06-16',
                'a_vendre' => 0,
                'prix' => NULL,
                'elevage_id' => 1,
                'fondateur' => 1,
                'foetus' => 0,
                'consang' => 0.0,
                'sire_id' => NULL,
                'dam_id' => NULL,
                'modele_allures' => 13,
                'modele_allures_additifs' => 13,
                'taille_additive' => 106,
                'notes' => NULL,
            ),
            4 => 
            array (
                'id' => 6,
                'created_at' => NULL,
                'updated_at' => '2021-01-06 15:45:34',
                'nom' => ' Myrrdhin',
                'affixe_id' => 5,
                'couleur' => 'bai sabino',
                'base' => 'bai',
                'taille_cm' => 117,
                'race_id' => 4,
                'sexe' => 'jeune mâle',
                'date_achat' => NULL,
                'date_naissance' => '1968-04-13',
                'a_vendre' => 0,
                'prix' => NULL,
                'elevage_id' => 10,
                'fondateur' => 1,
                'foetus' => 0,
                'consang' => 0.0,
                'sire_id' => NULL,
                'dam_id' => NULL,
                'modele_allures' => 16,
                'modele_allures_additifs' => 16,
                'taille_additive' => 117,
                'notes' => NULL,
            ),
            5 => 
            array (
                'id' => 7,
                'created_at' => NULL,
                'updated_at' => '2021-01-06 15:52:26',
                'nom' => 'Keridwen',
                'affixe_id' => 5,
                'couleur' => 'alezan crins lavés',
                'base' => 'alezan aa',
                'taille_cm' => 111,
                'race_id' => 4,
                'sexe' => 'jeune femelle',
                'date_achat' => NULL,
                'date_naissance' => '1968-05-18',
                'a_vendre' => 0,
                'prix' => NULL,
                'elevage_id' => 10,
                'fondateur' => 1,
                'foetus' => 0,
                'consang' => 0.0,
                'sire_id' => NULL,
                'dam_id' => NULL,
                'modele_allures' => 15,
                'modele_allures_additifs' => 15,
                'taille_additive' => 121,
                'notes' => NULL,
            ),
           
            7 => 
            array (
                'id' => 9,
                'created_at' => NULL,
                'updated_at' => '2021-01-05 17:21:25',
                'nom' => 'Owen',
                'affixe_id' => 4,
                'couleur' => 'bai ',
                'base' => 'bai',
                'taille_cm' => 118,
                'race_id' => 4,
                'sexe' => 'jeune mâle',
                'date_achat' => NULL,
                'date_naissance' => '1969-03-21',
                'a_vendre' => 0,
                'prix' => NULL,
                'elevage_id' => 10,
                'fondateur' => 1,
                'foetus' => 0,
                'consang' => 0.0,
                'sire_id' => NULL,
                'dam_id' => NULL,
                'modele_allures' => 16,
                'modele_allures_additifs' => 16,
                'taille_additive' => 118,
                'notes' => NULL,
            ),
            8 => 
            array (
                'id' => 10,
                'created_at' => NULL,
                'updated_at' => '2021-01-06 15:45:34',
                'nom' => ' Lizzy',
                'affixe_id' => 11,
                'couleur' => 'gris',
                'base' => 'bai',
                'taille_cm' => 113,
                'race_id' => 4,
                'sexe' => 'jeune femelle',
                'date_achat' => NULL,
                'date_naissance' => '1968-04-21',
                'a_vendre' => 0,
                'prix' => NULL,
                'elevage_id' => 10,
                'fondateur' => 1,
                'foetus' => 0,
                'consang' => 0.0,
                'sire_id' => NULL,
                'dam_id' => NULL,
                'modele_allures' => 12,
                'modele_allures_additifs' => 12,
                'taille_additive' => 113,
                'notes' => NULL,
            ),
            9 => 
            array (
                'id' => 11,
                'created_at' => NULL,
                'updated_at' => '2021-01-06 15:52:26',
                'nom' => ' Hero',
                'affixe_id' => 8,
                'couleur' => 'gris',
                'base' => 'alezan aa',
                'taille_cm' => 120,
                'race_id' => 4,
                'sexe' => 'jeune mâle',
                'date_achat' => NULL,
                'date_naissance' => '1968-05-31',
                'a_vendre' => 0,
                'prix' => NULL,
                'elevage_id' => 10,
                'fondateur' => 1,
                'foetus' => 0,
                'consang' => 0.0,
                'sire_id' => NULL,
                'dam_id' => NULL,
                'modele_allures' => 13,
                'modele_allures_additifs' => 13,
                'taille_additive' => 120,
                'notes' => NULL,
            ),
            10 => 
            array (
                'id' => 12,
                'created_at' => NULL,
                'updated_at' => '2021-01-06 15:45:34',
                'nom' => 'Comet',
                'affixe_id' => 12,
                'couleur' => 'palomino rubican',
                'base' => 'alezan aa',
                'taille_cm' => 119,
                'race_id' => 4,
                'sexe' => 'jeune mâle',
                'date_achat' => NULL,
                'date_naissance' => '1968-04-18',
                'a_vendre' => 0,
                'prix' => NULL,
                'elevage_id' => 10,
                'fondateur' => 1,
                'foetus' => 0,
                'consang' => 0.0,
                'sire_id' => NULL,
                'dam_id' => NULL,
                'modele_allures' => 12,
                'modele_allures_additifs' => 12,
                'taille_additive' => 119,
                'notes' => NULL,
            ),
            11 => 
            array (
                'id' => 13,
                'created_at' => NULL,
                'updated_at' => '2021-01-05 17:21:25',
                'nom' => 'Daffodil',
                'affixe_id' => 7,
                'couleur' => 'bai',
                'base' => 'bai',
                'taille_cm' => 109,
                'race_id' => 4,
                'sexe' => 'jeune femelle',
                'date_achat' => NULL,
                'date_naissance' => '1969-03-24',
                'a_vendre' => 0,
                'prix' => NULL,
                'elevage_id' => 10,
                'fondateur' => 1,
                'foetus' => 0,
                'consang' => 0.0,
                'sire_id' => NULL,
                'dam_id' => NULL,
                'modele_allures' => 11,
                'modele_allures_additifs' => 11,
                'taille_additive' => 129,
                'notes' => NULL,
            ),
            12 => 
            array (
                'id' => 14,
                'created_at' => NULL,
                'updated_at' => '2021-01-06 15:45:34',
                'nom' => ' Davy',
                'affixe_id' => 6,
                'couleur' => 'alezan',
                'base' => 'alezan agouti',
                'taille_cm' => 112,
                'race_id' => 4,
                'sexe' => 'jeune mâle',
                'date_achat' => NULL,
                'date_naissance' => '1968-04-25',
                'a_vendre' => 0,
                'prix' => NULL,
                'elevage_id' => 10,
                'fondateur' => 1,
                'foetus' => 0,
                'consang' => 0.0,
                'sire_id' => NULL,
                'dam_id' => NULL,
                'modele_allures' => 17,
                'modele_allures_additifs' => 17,
                'taille_additive' => 122,
                'notes' => NULL,
            ),
          
            
        ));
        
        
    }
}